#
# RPMB Makefile
#

obj-$(CONFIG_HISI_RPMB)			+= hisi_rpmb.o
obj-$(CONFIG_HISI_RPMB_MMC)		+= rpmb_mmc.o
obj-$(CONFIG_HISI_RPMB_UFS)		+= rpmb_ufs.o

obj-$(CONFIG_HISI_STORAGE_INTERFACE)		+= hisi_rpmb_fs.o

obj-$(CONFIG_HISI_RPMB_DEBUG_FS)		+= rpmb_debugfs.o
