obj-$(CONFIG_DIRECT_CHARGER) += direct_charger.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_sc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_lvc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_adapter.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_path_switch.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_uevent.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_check.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_power_supply.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_error_handle.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_para_parse.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_debug.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_cable.o

obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_test/
obj-$(CONFIG_SWITCHCAP) += switchcap/
