#
# huawei power common drivers
#

obj-y += power_algorithm/
obj-y += power_cmdline/
obj-y += power_dts/
obj-y += power_i2c/
obj-y += power_gpio/
obj-y += power_sysfs/
obj-y += power_ui/
obj-y += power_interface/
obj-y += power_event/
obj-y += power_temp/
obj-y += power_log/
obj-y += power_test/
obj-$(CONFIG_HUAWEI_DSM) += power_dsm/
obj-$(CONFIG_LOG_EXCEPTION) += power_bigdata/
obj-$(CONFIG_HUAWEI_POWER_DEBUG) += power_debug/
obj-$(CONFIG_HUAWEI_POWER_DEVICES_INFO) += power_devices_info/
obj-$(CONFIG_HUAWEI_POWER_FIRMWARE) += power_firmware/
obj-$(CONFIG_HUAWEI_POWER_SUPPLY) += power_supply/
obj-$(CONFIG_HUAWEI_POWER_THERMALZONE) += power_thermalzone/
