# Hisilicon IPP segment Makefile

obj-$(CONFIG_HISPIPP_V350) += segment_anf.o
obj-$(CONFIG_HISPIPP_V350) += segment_arfeature.o
obj-$(CONFIG_HISPIPP_V350) += segment_common.o
obj-$(CONFIG_HISPIPP_V350) += segment_compare.o
obj-$(CONFIG_HISPIPP_V350) += segment_gf.o
obj-$(CONFIG_HISPIPP_V350) += segment_hiof.o
obj-$(CONFIG_HISPIPP_V350) += segment_ipp_adapter.o
obj-$(CONFIG_HISPIPP_V350) += segment_ipp_adapter_sub.o
obj-$(CONFIG_HISPIPP_V350) += segment_ipp_path.o
obj-$(CONFIG_HISPIPP_V350) += segment_matcher.o
obj-$(CONFIG_HISPIPP_V350) += segment_mc.o
obj-$(CONFIG_HISPIPP_V350) += segment_orb_enh.o
obj-$(CONFIG_HISPIPP_V350) += segment_reorder.o
obj-$(CONFIG_HISPIPP_V350) += segment_tof.o

