EXTRA_CFLAGS += -Isound/soc/codecs/hisi/asp_codec_990/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Iinclude/linux/hisi/

snd-soc-aspcodec-objs :=asp_codec.o
snd-soc-aspcodec-utils-objs :=asp_codec_utils.o
snd-soc-aspcodec-resource-widget-objs :=asp_codec_resource_widget.o
snd-soc-aspcodec-path-widget-objs :=asp_codec_path_widget.o
snd-soc-aspcodec-switch-widget-objs :=asp_codec_switch_widget.o
snd-soc-aspcodec-kcontrol-objs :=asp_codec_kcontrol.o
snd-soc-aspcodec-route-objs :=asp_codec_route.o

obj-y += snd-soc-aspcodec.o
obj-y += snd-soc-aspcodec-utils.o
obj-y += snd-soc-aspcodec-resource-widget.o
obj-y += snd-soc-aspcodec-path-widget.o
obj-y += snd-soc-aspcodec-switch-widget.o
obj-y += snd-soc-aspcodec-kcontrol.o
obj-y += snd-soc-aspcodec-route.o
