ccflags-y += -I$(srctree)/drivers/hisi/tzdriver \
	     -I$(srctree)/drivers/hisi/mspc

obj-$(CONFIG_HISI_FILE_BASED_ENCRYPTO) += fbex_dev.o \
	fbex_driver.o fbex_screen_handle.o fbex_preload.o
obj-$(CONFIG_HISI_FILE_BASED_ENCRYPTO_DBG) += fbex_debug.o
