// ************************************************************
// Copyright     :  Copyright (C) 2019, Hisilicon Technologies Co. Ltd.
// File name     :  vbk_reg_offset.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Version       :  1.0
// Date          :  2019/01/02
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V4.1
// ************************************************************

#ifndef __VBK_REG_OFFSET_H__
#define __VBK_REG_OFFSET_H__

#define VBK_VBK_CFG_REG                      0x0   /* VBK Top Config */
#define VBK_VBK_Y_DS16_GAUSS_COEFF0_CFG_REG  0x4   /* Y DS16 Coeff 0 */
#define VBK_VBK_Y_DS16_GAUSS_COEFF1_CFG_REG  0x8   /* Y DS16 Coeff 1 */
#define VBK_VBK_UV_DS16_GAUSS_COEFF1_CFG_REG 0xC   /* UV DS16 Coeff 1 */
#define VBK_VBK_UV_DS16_GAUSS_COEFF0_CFG_REG 0x10  /* UV DS16 Coeff 0 */
#define VBK_VBK_SIGMA_GAUSS_COEFF0_CFG_REG   0x14  /* Sigma Coeff 0 */
#define VBK_VBK_SIGMA_GAUSS_COEFF1_CFG_REG   0x18  /* Sigma Coeff 1 */
#define VBK_VBK_SIGMA2ALPHA_LUT_0_REG        0x1C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_1_REG        0x20  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_2_REG        0x24  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_3_REG        0x28  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_4_REG        0x2C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_5_REG        0x30  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_6_REG        0x34  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_7_REG        0x38  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_8_REG        0x3C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_9_REG        0x40  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_10_REG       0x44  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_11_REG       0x48  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_12_REG       0x4C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_13_REG       0x50  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_14_REG       0x54  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_15_REG       0x58  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_16_REG       0x5C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_17_REG       0x60  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_18_REG       0x64  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_19_REG       0x68  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_20_REG       0x6C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_21_REG       0x70  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_22_REG       0x74  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_23_REG       0x78  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_24_REG       0x7C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_25_REG       0x80  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_26_REG       0x84  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_27_REG       0x88  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_28_REG       0x8C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_29_REG       0x90  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_30_REG       0x94  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_31_REG       0x98  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_32_REG       0x9C  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_33_REG       0xA0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_34_REG       0xA4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_35_REG       0xA8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_36_REG       0xAC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_37_REG       0xB0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_38_REG       0xB4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_39_REG       0xB8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_40_REG       0xBC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_41_REG       0xC0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_42_REG       0xC4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_43_REG       0xC8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_44_REG       0xCC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_45_REG       0xD0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_46_REG       0xD4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_47_REG       0xD8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_48_REG       0xDC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_49_REG       0xE0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_50_REG       0xE4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_51_REG       0xE8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_52_REG       0xEC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_53_REG       0xF0  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_54_REG       0xF4  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_55_REG       0xF8  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_56_REG       0xFC  /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_57_REG       0x100 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_58_REG       0x104 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_59_REG       0x108 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_60_REG       0x10C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_61_REG       0x110 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_62_REG       0x114 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_63_REG       0x118 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_64_REG       0x11C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_65_REG       0x120 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_66_REG       0x124 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_67_REG       0x128 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_68_REG       0x12C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_69_REG       0x130 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_70_REG       0x134 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_71_REG       0x138 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_72_REG       0x13C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_73_REG       0x140 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_74_REG       0x144 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_75_REG       0x148 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_76_REG       0x14C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_77_REG       0x150 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_78_REG       0x154 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_79_REG       0x158 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_80_REG       0x15C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_81_REG       0x160 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_82_REG       0x164 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_83_REG       0x168 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_84_REG       0x16C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_85_REG       0x170 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_86_REG       0x174 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_87_REG       0x178 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_88_REG       0x17C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_89_REG       0x180 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_90_REG       0x184 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_91_REG       0x188 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_92_REG       0x18C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_93_REG       0x190 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_94_REG       0x194 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_95_REG       0x198 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_96_REG       0x19C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_97_REG       0x1A0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_98_REG       0x1A4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_99_REG       0x1A8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_100_REG      0x1AC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_101_REG      0x1B0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_102_REG      0x1B4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_103_REG      0x1B8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_104_REG      0x1BC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_105_REG      0x1C0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_106_REG      0x1C4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_107_REG      0x1C8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_108_REG      0x1CC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_109_REG      0x1D0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_110_REG      0x1D4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_111_REG      0x1D8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_112_REG      0x1DC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_113_REG      0x1E0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_114_REG      0x1E4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_115_REG      0x1E8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_116_REG      0x1EC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_117_REG      0x1F0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_118_REG      0x1F4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_119_REG      0x1F8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_120_REG      0x1FC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_121_REG      0x200 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_122_REG      0x204 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_123_REG      0x208 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_124_REG      0x20C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_125_REG      0x210 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_126_REG      0x214 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_127_REG      0x218 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_128_REG      0x21C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_129_REG      0x220 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_130_REG      0x224 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_131_REG      0x228 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_132_REG      0x22C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_133_REG      0x230 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_134_REG      0x234 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_135_REG      0x238 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_136_REG      0x23C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_137_REG      0x240 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_138_REG      0x244 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_139_REG      0x248 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_140_REG      0x24C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_141_REG      0x250 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_142_REG      0x254 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_143_REG      0x258 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_144_REG      0x25C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_145_REG      0x260 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_146_REG      0x264 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_147_REG      0x268 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_148_REG      0x26C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_149_REG      0x270 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_150_REG      0x274 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_151_REG      0x278 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_152_REG      0x27C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_153_REG      0x280 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_154_REG      0x284 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_155_REG      0x288 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_156_REG      0x28C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_157_REG      0x290 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_158_REG      0x294 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_159_REG      0x298 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_160_REG      0x29C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_161_REG      0x2A0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_162_REG      0x2A4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_163_REG      0x2A8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_164_REG      0x2AC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_165_REG      0x2B0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_166_REG      0x2B4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_167_REG      0x2B8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_168_REG      0x2BC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_169_REG      0x2C0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_170_REG      0x2C4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_171_REG      0x2C8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_172_REG      0x2CC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_173_REG      0x2D0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_174_REG      0x2D4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_175_REG      0x2D8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_176_REG      0x2DC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_177_REG      0x2E0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_178_REG      0x2E4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_179_REG      0x2E8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_180_REG      0x2EC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_181_REG      0x2F0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_182_REG      0x2F4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_183_REG      0x2F8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_184_REG      0x2FC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_185_REG      0x300 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_186_REG      0x304 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_187_REG      0x308 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_188_REG      0x30C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_189_REG      0x310 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_190_REG      0x314 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_191_REG      0x318 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_192_REG      0x31C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_193_REG      0x320 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_194_REG      0x324 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_195_REG      0x328 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_196_REG      0x32C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_197_REG      0x330 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_198_REG      0x334 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_199_REG      0x338 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_200_REG      0x33C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_201_REG      0x340 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_202_REG      0x344 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_203_REG      0x348 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_204_REG      0x34C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_205_REG      0x350 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_206_REG      0x354 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_207_REG      0x358 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_208_REG      0x35C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_209_REG      0x360 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_210_REG      0x364 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_211_REG      0x368 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_212_REG      0x36C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_213_REG      0x370 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_214_REG      0x374 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_215_REG      0x378 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_216_REG      0x37C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_217_REG      0x380 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_218_REG      0x384 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_219_REG      0x388 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_220_REG      0x38C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_221_REG      0x390 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_222_REG      0x394 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_223_REG      0x398 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_224_REG      0x39C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_225_REG      0x3A0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_226_REG      0x3A4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_227_REG      0x3A8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_228_REG      0x3AC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_229_REG      0x3B0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_230_REG      0x3B4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_231_REG      0x3B8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_232_REG      0x3BC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_233_REG      0x3C0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_234_REG      0x3C4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_235_REG      0x3C8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_236_REG      0x3CC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_237_REG      0x3D0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_238_REG      0x3D4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_239_REG      0x3D8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_240_REG      0x3DC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_241_REG      0x3E0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_242_REG      0x3E4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_243_REG      0x3E8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_244_REG      0x3EC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_245_REG      0x3F0 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_246_REG      0x3F4 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_247_REG      0x3F8 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_248_REG      0x3FC /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_249_REG      0x400 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_250_REG      0x404 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_251_REG      0x408 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_252_REG      0x40C /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_253_REG      0x410 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_254_REG      0x414 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_SIGMA2ALPHA_LUT_255_REG      0x418 /* VBK Sigma2Alpha LUT */
#define VBK_VBK_ADDNOISE_CFG_REG             0x41C /* VBK Add Noise Config */
#define VBK_VBK_FOREMASK_CFG_REG             0x420 /* VBK Foremask Config */
#define VBK_VBK_TOP_DEBUG_REG                0x424 /* VBK Top Debug */
#define VBK_VBK_Y_DS16_GAUSS_DEBUG_REG       0x428 /* VBK Y DS16 Gauss Debug */
#define VBK_VBK_UV_DS16_GAUSS_DEBUG_REG      0x42C /* VBK UV DS16 Gauss Debug */
#define VBK_VBK_SIGMA_GAUSS_DEBUG_REG        0x430 /* VBK Sigma Gauss Debug */
#define VBK_VBK_Y_CROP_H_REG        0x434 /* CROP for vbk_y */
#define VBK_VBK_Y_CROP_V_REG        0x438 /* CROP for vbk_y */
#define VBK_VBK_UV_CROP_H_REG     0x43C /* CROP for vbk_uv */
#define VBK_VBK_UV_CROP_V_REG     0x440 /* CROP for vbk_uv */
#define VBK_VBK_TF_CROP_H_REG      0x444 /* CROP for next_calforemasktf */
#define VBK_VBK_TF_CROP_V_REG      0x448 /* CROP for next_calforemasktf */

#endif // __VBK_REG_OFFSET_H__
