EXTRA_CFLAGS += -Idrivers/hisi/slimbus/
EXTRA_CFLAGS += -Idrivers/devkit/audiokit/
EXTRA_CFLAGS += -Idrivers/hisi/hi64xx_dsp/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Idrivers/hisi/hi64xx_dsp/config/

snd-soc-hi6403-objs :=hi6403.o
snd-soc-hi6403-kcontrol-objs :=hi6403_kcontrol.o
snd-soc-hi6403-resource-widget-objs :=hi6403_resource_widget.o
snd-soc-hi6403-path-widget-objs :=hi6403_path_widget.o
snd-soc-hi6403-switch-widget-objs :=hi6403_switch_widget.o
snd-soc-hi6403-route-objs :=hi6403_route.o
snd-soc-hi6403-headset-config-objs :=hi6403_headset_config.o

obj-y += snd-soc-hi6403.o
obj-y += snd-soc-hi6403-kcontrol.o
obj-y += snd-soc-hi6403-resource-widget.o
obj-y += snd-soc-hi6403-path-widget.o
obj-y += snd-soc-hi6403-switch-widget.o
obj-y += snd-soc-hi6403-route.o
obj-y += snd-soc-hi6403-headset-config.o
