obj-$(CONFIG_HISI_PERIDVFS)		+= peri_dvfs_volt.o
ifeq ($(CONFIG_HISI_HW_PERI_DVS),y)
obj-$(CONFIG_HISI_PERIDVFS)		+= hisi_hw_peri_dvs.o
else
obj-$(CONFIG_HISI_PERIDVFS)		+= hisi_peri_dvfs_volt.o
endif
