#goodix gtx8_brl

obj-$(CONFIG_GOODIX_GTX8_BRL_TS_KIT_3_0) += gtx8_brl_ts.o
gtx8_brl_ts-objs += gtx8_brl.o gtx8_brl_update.o gtx8_brl_test.o gtx8_brl_tools.o

EXTRA_CFLAGS += -Idrivers/devkit/tpkit/3_0
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver

