#ifndef __PLATFORM_MEMORY_DEF_H__
#define __PLATFORM_MEMORY_DEF_H__ 
#include <global_ddr_map.h>
#if defined(CONFIG_GCOV_ATF) || defined(CONFIG_HISI_GCOV_FASTBOOT)
#define HISI_BL31_BASE HISI_RESERVED_BL31_PHYMEM_BASE
#define HISI_BL31_RAM_ADDR HISI_BL31_BASE
#define HISI_BL31_RAM_SIZE (0x200000)
#else
#define HISI_BL31_BASE HISI_RESERVED_BL31_DATA_BASE
#define HISI_BL31_RAM_ADDR HISI_BL31_BASE
#define HISI_BL31_RAM_SIZE (0xE0000)
#endif
#define HISI_BL31_LOG_ADDR (HISI_RESERVED_BL31_DATA_BASE + 0xE0000)
#define HISI_BL31_LOG_SIZE (0x20000)
#define HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR (HISI_BL31_LOG_ADDR + HISI_BL31_LOG_SIZE)
#define HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE (0x110)
#define HISI_BL31_RPMB_KEY_INFO_ADDR (HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR + \
                HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE)
#define HISI_BL31_RPMB_KEY_INFO_SIZE (0x20)
#define HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR (HISI_BL31_RPMB_KEY_INFO_ADDR + \
                HISI_BL31_RPMB_KEY_INFO_SIZE)
#define HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE (0x80)
#define HISI_BL31_HUK_CODE_ADDR (HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR + HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE)
#define HISI_BL31_HUK_CODE_SIZE (0x20)
#define HISI_BL31_RPMB_KEY_ADDR (HISI_BL31_HUK_CODE_ADDR + HISI_BL31_HUK_CODE_SIZE)
#define HISI_BL31_RPMB_KEY_SIZE (0x80)
#define HISI_BL31_DDRC_INFO_ADDR (HISI_BL31_RPMB_KEY_ADDR + HISI_BL31_RPMB_KEY_SIZE)
#define HISI_BL31_DDRC_INFO_SIZE (0x200)
#define HISI_NPU_PM_PARA_BASE (HISI_BL31_DDRC_INFO_ADDR + HISI_BL31_DDRC_INFO_SIZE)
#define HISI_NPU_PM_PARA_SIZE (0x100)
#define HISI_BL31_UFS_KEY_ADDR (HISI_NPU_PM_PARA_BASE + HISI_NPU_PM_PARA_SIZE)
#define HISI_BL31_UFS_KEY_SIZE (0x700)
#define HISI_BL31_RPMB_DEVICE_INFO_ADDR (HISI_BL31_UFS_KEY_ADDR + HISI_BL31_UFS_KEY_SIZE)
#define HISI_BL31_RPMB_DEVICE_INFO_SIZE (0x28)
#define HISI_BL31_RPMB_BOOT_INFO_ADDR (HISI_BL31_RPMB_DEVICE_INFO_ADDR + HISI_BL31_RPMB_DEVICE_INFO_SIZE)
#define HISI_BL31_RPMB_BOOT_INFO_SIZE (0x20)
#define HISI_BL31_FASTBOOT_HITEST_MNTN_ADDR (HISI_BL31_RPMB_BOOT_INFO_ADDR + HISI_BL31_RPMB_BOOT_INFO_SIZE)
#define HISI_BL31_FASTBOOT_HITEST_MNTN_SIZE (0x20)
#define HISI_BL31_LB_LITE_FLAG_ADDR (HISI_BL31_FASTBOOT_HITEST_MNTN_ADDR + HISI_BL31_FASTBOOT_HITEST_MNTN_SIZE)
#define HISI_BL31_LB_LITE_FLAG_SIZE (0x2)
#define HISI_BL31_SOCID_SHMEM_ADDR (HISI_BL31_LB_LITE_FLAG_ADDR + HISI_BL31_LB_LITE_FLAG_SIZE)
#define HISI_BL31_SOCID_SHMEM_SIZE (0x20)
#define HISI_BL31_RESERVE_MEM_ADDR (HISI_BL31_SOCID_SHMEM_ADDR + HISI_BL31_SOCID_SHMEM_SIZE)
#define HISI_BL31_RESERVE_MEM_SIZE (0x326)
#define HISI_ATF_TEE_SHMEM_ADDR (HISI_BL31_RESERVE_MEM_ADDR + HISI_BL31_RESERVE_MEM_SIZE)
#define HISI_ATF_TEE_SHMEM_SIZE (0x1000)
#define HISI_BL31_HISEE_ADDR (HISI_ATF_TEE_SHMEM_ADDR + HISI_ATF_TEE_SHMEM_SIZE)
#define HISI_BL31_HISEE_SIZE (0x4FE000)
#define HISI_BL31_SIZE (HISI_RESERVED_BL31_PHYMEM_SIZE - HISI_BL31_HISEE_SIZE)
#define HISI_BL2_RAM_BASE (HISI_RESERVED_BL2_PHYMEM_BASE)
#define HISI_BL2_RAM_SIZE (HISI_RESERVED_BL2_PHYMEM_SIZE)
#define HISI_BL2_RAM_END (HISI_BL2_RAM_BASE + HISI_BL2_RAM_SIZE)
#define HISI_BL2_LOG_SIZE (HISI_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_SIZE)
#define HISI_BL2_LOG_ADDR (HISI_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_BASE)
#define HISI_BL2_SHMEM_SIZE 0x10000
#define HISI_BL2_SHMEM_ADDR (HISI_BL2_RAM_END - HISI_BL2_SHMEM_SIZE)
#define HISI_BL2_CC_DATA_SIZE 0x100000
#define HISI_BL2_CC_DATA_ADDR (HISI_BL2_SHMEM_ADDR - HISI_BL2_CC_DATA_SIZE)
#define HISI_BL2_DDR_SHMEM_SIZE 0xD000
#define HISI_BL2_DDR_SHMEM_ADDR (HISI_BL2_CC_DATA_ADDR - HISI_BL2_DDR_SHMEM_SIZE)
#define HISI_BL2_EFUSE_SHMEM_SIZE 0x1000
#define HISI_BL2_EFUSE_SHMEM_ADDR (HISI_BL2_DDR_SHMEM_ADDR - HISI_BL2_EFUSE_SHMEM_SIZE)
#define HISI_BL2_SHMEM_RESERVE_SIZE (0x10000 - HISI_BL2_DDR_SHMEM_SIZE - HISI_BL2_EFUSE_SHMEM_SIZE)
#define HISI_BL2_SHMEM_RESERVE_ADDR (HISI_BL2_EFUSE_SHMEM_ADDR - HISI_BL2_SHMEM_RESERVE_SIZE)
#define HISI_BL2_SECRAM_END (HISI_BL2_SHMEM_RESERVE_ADDR)
#define HISI_BL2_CC_PAL_SIZE 0x100000
#define HISI_BL2_CC_PAL_ADDR (HISI_BL2_SECRAM_END - HISI_BL2_CC_PAL_SIZE)
#endif
