#ifndef __DDR_VOTE_STATISTIC_STRUCT_H__
#define __DDR_VOTE_STATISTIC_STRUCT_H__ 
enum sw_vote_stat_ip {
 LIT_CLUSTER_ID = 0x80,
 BIG_CLUSTER_ID = 0x81,
 GPU_ID = 0x82,
 IOMCU_ID = 0x83,
 MODEM_ID = 0x84,
 TEMPERTURE_ID = 0x85,
 MID_CLUSTER_ID = 0x86,
 L3_CLUSTER_ID = 0x87,
 CPU_MONITOR_ID =0x88,
 AP_SR_ID = 0x89,
 PERI_VOLT_ID = 0x8a,
 MODEM_5G_ID = 0x8b
};
enum hw_vote_stat_ip {
 FLOOR_VOTE_HW_AP_ID = 0x0,
 FLOOR_VOTE_HW_HIFI_ID = 0x1,
 FLOOR_VOTE_HW_IOMCU_ID = 0x2,
 FLOOR_VOTE_HW_LIT_LAT_ID = 0x3,
 FLOOR_VOTE_HW_BIG_LAT_ID = 0x4,
 FLOOR_VOTE_HW_MID_LAT_ID = 0x5,
 FLOOR_VOTE_HW_LATSTAT_ID = 0x6,
};
#endif
