#ifndef __DDR_DEFINE_H__
#define __DDR_DEFINE_H__ 
#include <ddr_dram_define.h>
#include <ddr_nmanager_extend.h>
#define MAX_RANK_NUM_PER_DMC 2
#define MAX_DDR_DENSITY 11
#define DDR_DENSITY_4GBIT 2
#define DDR_DENSITY_6GBIT 3
#define DDR_DENSITY_8GBIT 4
#define DDR_DENSITY_12GBIT 5
#define DDR_DENSITY_16GBIT 6
#define DDR_SUPPORT_R17_ROW_BIT 18
#define DDR_ROW_TO_REGVAL(row) ((row) - 11)
#define DDR_COL_TO_REGVAL(col) ((col) - 8)
#define DDR_BANK_REGVAL_LPDDR4 2
#ifdef DDR_ROSIN_JOINT_PIN_CHECK
#define VADC_ROSIN_JOINT_CHANNEL 12
#define VADC_UP_THRESHOLD_0 658
#define VADC_UP_THRESHOLD_1 808
#define VADC_UP_THRESHOLD_2 1046
#define VADC_UP_THRESHOLD_3 1495
#endif
#define DDR_TYPE_LPDDR3 0
#define DDR_TYPE_LPDDR4 8
#define DDR_TYPE_LPDDR5 9
#define HYNIX_LPDDR5_ES_REVISION_ID1 0x6
#define HYNIX_LPDDR5_ES_REVISION_ID2 0x0
#define DDR_HPM_SENSOR_NUM 5
#define DDR_HPM_PARA_NUM (DDR_HPM_SENSOR_NUM + 1)
#define DDR_AVS_TEMP_RECOUP_0 0
#define DDR_AVS_TEMP_RECOUP_1 1
#define DDR_AVS_TEMP_RECOUP_2 2
#define DDR_AVS_TEMP_RECOUP_3 3
#define DDR_AVS_TEMP_RECOUP_NUM 4
#define DDR_AVS_TZONE_0 0
#define DDR_AVS_TZONE_1 20
#define DDR_AVS_TZONE_2 40
#define DDR_AVS_TZONE_3 60
#define DDR_AVS_CHIP_TYPE_NOT_SAVE 0x0
#define DDR_AVS_CHIP_TYPE_SAVE 0x1
#if (defined HIBENCH_XLOADER || defined __SLT_FEATURE__)
#define DDR_AVS_SLT_VOLT_NOT_INIT 0x0
#define DDR_AVS_SLT_VOLT_INIT 0x1
#endif
#define DDR_DIV_ROUNDUP(a,b) (((a) + (b) - 1) / (b))
#define DDR_DIV_ROUNDDN(a,b) ((a) / (b))
#define DDR_COMPARE_MIN(a,b) (((a) < (b)) ? (a) : (b))
#define DDR_COMPARE_MAX(a,b) (((a) > (b)) ? (a) : (b))
#define DDR_SECTION_RDQSCYC_NUM 12
#define DDR_SECTION_BASE_NUM 1
#define DDR_SECTION_MAX_NUM (DDR_SECTION_RDQSCYC_NUM + DDR_SECTION_BASE_NUM)
#define DDR_SECTION_VOLT_STEP 25
#define DDR_SECTION_VOLT_ROUND_UP(vol) ((((unsigned int)(vol) + (unsigned int)DDR_SECTION_VOLT_STEP - 1) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_VOLT_ROUND_DOWN(vol) (((unsigned int)(vol) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_VOLT_ROUND(vol) ((((unsigned int)(vol) + ((unsigned int)DDR_SECTION_VOLT_STEP >> 1)) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_RDQSCYC_RATIO_SHIFT 0x8
#define PLL_INIT_ID 1
#define TRAINING_TYPE_DLYMEAS_ID 2
#define TRAINING_TYPE_ZCAl_ID 3
#define TRAINING_TYPE_WL_ID 4
#define TRAINING_TYPE_GT_ID 5
#define TRAINING_TYPE_GDST_ID 6
#define TRAINING_TYPE_WL2_ID 7
#define TRAINING_TYPE_RDET_ID 8
#define TRAINING_TYPE_WDET_ID 9
#define TRAINING_TYPE_DRAMINIT_ID 10
#define TRAINING_TYPE_CAT_ID 11
#define TRAINING_TYPE_DRAMRST_ID 12
#define TRAINING_TYPE_DVREFT_ID 16
#define TRAINING_TYPE_HVREFT_ID 17
#define TRAINING_TYPE_DXDVREFS_ID 18
#define TRAINING_TYPE_ACDVREFT_ID 19
#define TRAINING_TYPE_ACHVREFT_ID 20
#define TRAINING_TYPE_ACDVREFS_ID 21
#define TRAINING_TYPE_CST_ID 22
#define TRAINING_TYPE_RDQDCC_ID 23
#define TRAINING_TYPE_RDQSDIT_ID 24
#define TRAINING_TYPE_RDQ_DUTY_ID 25
#define TRAINING_TYPE_DCA_DUTY_ID 26
#define TRAINING_TYPE_RESERVED_ID 27
#define TRAINING_TYPE_MAX_ID (TRAINING_TYPE_RESERVED_ID + 1)
#define PLL_INIT (0x1U << PLL_INIT_ID)
#define TRAINING_TYPE_DLYMEAS (0x1U << TRAINING_TYPE_DLYMEAS_ID)
#define TRAINING_TYPE_ZCAl (0x1U << TRAINING_TYPE_ZCAl_ID)
#define TRAINING_TYPE_WL (0x1U << TRAINING_TYPE_WL_ID)
#define TRAINING_TYPE_GT (0x1U << TRAINING_TYPE_GT_ID)
#define TRAINING_TYPE_GDST (0x1U << TRAINING_TYPE_GDST_ID)
#define TRAINING_TYPE_WL2 (0x1U << TRAINING_TYPE_WL2_ID)
#define TRAINING_TYPE_RDET (0x1U << TRAINING_TYPE_RDET_ID)
#define TRAINING_TYPE_WDET (0x1U << TRAINING_TYPE_WDET_ID)
#define TRAINING_TYPE_DRAMINIT (0x1U << TRAINING_TYPE_DRAMINIT_ID)
#define TRAINING_TYPE_CAT (0x1U << TRAINING_TYPE_CAT_ID)
#define TRAINING_TYPE_DRAMRST (0x1U << TRAINING_TYPE_DRAMRST_ID)
#define TRAINING_TYPE_DVREFT (0x1U << TRAINING_TYPE_DVREFT_ID)
#define TRAINING_TYPE_HVREFT (0x1U << TRAINING_TYPE_HVREFT_ID)
#define TRAINING_TYPE_DXDVREFS (0x1U << TRAINING_TYPE_DXDVREFS_ID)
#define TRAINING_TYPE_ACDVREFT (0x1U << TRAINING_TYPE_ACDVREFT_ID)
#define TRAINING_TYPE_ACHVREFT (0x1U << TRAINING_TYPE_ACHVREFT_ID)
#define TRAINING_TYPE_ACDVREFS (0x1U << TRAINING_TYPE_ACDVREFS_ID)
#define TRAINING_TYPE_CST (0x1U << TRAINING_TYPE_CST_ID)
#define TRAINING_TYPE_RDQDCC (0x1U << TRAINING_TYPE_RDQDCC_ID)
#define TRAINING_TYPE_RDQSDIT (0x1U << TRAINING_TYPE_RDQSDIT_ID)
#define TRAINING_TYPE_RDQ_DUTY (0x1U << TRAINING_TYPE_RDQ_DUTY_ID)
#define TRAINING_TYPE_DCA_DUTY (0x1U << TRAINING_TYPE_DCA_DUTY_ID)
#define TMOD_REFRESH_RATE_0 0
#define TMOD_REFRESH_RATE_1 1
#define TMOD_REFRESH_RATE_2 2
#define TMOD_REFRESH_RATE_3 3
#define TMOD_REFRESH_RATE_4 4
#define TMOD_REFRESH_RATE_5 5
#define TMOD_REFRESH_RATE_6 6
#define TMOD_REFRESH_RATE_7 7
#define TMOD_REFRESH_RATE_8 8
#define TMOD_REFRESH_RATE_9 9
#define TMOD_REFRESH_RATE_10 10
#define TMOD_REFRESH_RATE_11 11
#define TMOD_REFRESH_RATE_12 12
#define TMOD_REFRESH_RATE_13 13
#define XTREFI_1P4 ((TMOD_REFRESH_RATE_5 << 3) | TMOD_REFRESH_RATE_5)
#define TRANS_TO_LPM3_PROFILE_NUM(x) (((x) > 1U) ? ((x) - 1U) : (x))
#define TRANS_TO_LPM3_FREQ_IDX(x) (((x) > 0U) ? ((x) - 1U) : 0U)
#define TRANS_TO_LPM3_PROFILE_START_IDX(x,profile_num) (((profile_num) > 1U) ? ((x) + 1U) : (x))
#define FREQ_NUM_MAX 11U
#define LPMCU_FREQ_NUM_MAX TRANS_TO_LPM3_PROFILE_NUM(FREQ_NUM_MAX)
#define FREQ_RANGE_EXT 6U
#define DMSS_FREQ_NUM_MAX 6U
#define LPMCU_DMSS_FREQ_NUM_MAX TRANS_TO_LPM3_PROFILE_NUM(DMSS_FREQ_NUM_MAX)
#define DDR_TRAIN_PARAM_NUM_MAX (LPMCU_FREQ_NUM_MAX + FREQ_RANGE_EXT)
#define DDR_TRAIN_PARAM_IDX_TO_VREF_IDX(train_param_idx) ((train_param_idx) + 1)
#define DDR_VREF_NUM_MAX DDR_TRAIN_PARAM_IDX_TO_VREF_IDX(DDR_TRAIN_PARAM_NUM_MAX)
#define DDR_FREQ_2750 2750
#define DDR_FREQ_2746 2746
#define DDR_FREQ_2405 2405
#define DDR_FREQ_2285 2285
#define DDR_FREQ_2133 2133
#define DDR_FREQ_2132 2132
#define DDR_FREQ_2131 2131
#define DDR_FREQ_2107 2107
#define DDR_FREQ_1866 1866
#define DDR_FREQ_1795 1795
#define DDR_FREQ_1661 1661
#define DDR_FREQ_1660 1660
#define DDR_FREQ_1600 1600
#define DDR_FREQ_1373 1373
#define DDR_FREQ_1370 1370
#define DDR_FREQ_1333 1333
#define DDR_FREQ_1245 1245
#define DDR_FREQ_1244 1244
#define DDR_FREQ_1104 1104
#define DDR_FREQ_1066 1066
#define DDR_FREQ_902 902
#define DDR_FREQ_900 900
#define DDR_FREQ_830 830
#define DDR_FREQ_800 800
#define DDR_FREQ_686 686
#define DDR_FREQ_673 673
#define DDR_FREQ_667 667
#define DDR_FREQ_600 600
#define DDR_FREQ_533 533
#define DDR_FREQ_451 451
#define DDR_FREQ_418 418
#define DDR_FREQ_415 415
#define DDR_FREQ_400 400
#define DDR_FREQ_266 266
#define DDR_FREQ_133 133
#define DDR_FREQ_58 58
#define DDR_FREQ_55 55
#define DDR_FREQ_MAX DDR_FREQ_2746
#define DDR_DTS_SELF_ADAPT_MAX_FREQ DDR_FREQ_1866
#define LOAD_LPM3_CONFIG_TARGET 0x5
#define LOAD_LPM3_CONFIG_DMSS_FREQ 0x6
#define NO_RDQSBDL_THRES DDR_FREQ_1795
#define DMSS_FREQ_1067 1067
#define DMSS_FREQ_933 933
#define DMSS_FREQ_830 830
#define DMSS_FREQ_640 640
#define DMSS_FREQ_533 533
#define DMSS_FREQ_415 415
#define DMSS_FREQ_52 52
#define DMSS_FREQ_26 26
#define DDR_SDR 0
#define DDR_HDR 1
#define DDR_QDR 2
#define IO_WIDTH_X16 0
#define IO_WIDTH_X8 1
#define IO_WIDTH_MAX 2
#define ONE_BYTE_PER_DIE 1
#define TWO_BYTE_PER_DIE 2
#define ONE_DIE_PER_RANK 1
#define TWO_DIE_PER_RANK 2
#define DDR_MEM_ROW_REG_START_BIT 11
#define DDR_MEM_COL_REG_START_BIT 8
#define RANK_ID_0 0
#define RANK_ID_1 1
#define RANK_MAX_NUM 2
#define BYTELANE_ID_0 0
#define BYTELANE_ID_1 1
#define BYTELANE_MAX_NUM 2
#define EDGETYPE_ID_EVEN 0
#define EDGETYPE_ID_ODD 1
#define EDGETYPE_MAX_NUM 2
#define LOOP_REDUCE_OFFSET 64U
#define HOST_RESEL_START 0
#define HOST_RESEL_END 1
#define HOST_REFREANGE_START 2
#define HOST_REFREANGE_END 5
#define DRAM_CA_VREF_X8_RANK_MAX_NUM_LPDDR5 2
#define HOST_DQ_VREF_X8_RANK_MAX_NUM_LPDDR5 1
#define DRAM_DQ_VREF_X8_RANK_MAX_NUM_LPDDR5 2
#define DRAM_CA_VREF_X8_RANK_MAX_NUM_LPDDR4 2
#define HOST_DQ_VREF_X8_RANK_MAX_NUM_LPDDR4 1
#define DRAM_DQ_VREF_X8_RANK_MAX_NUM_LPDDR4 2
#define DRAM_CA_VREF_X8_BYTELANE_MAX_NUM_LPDDR5 2
#define HOST_DQ_VREF_X8_BYTELANE_MAX_NUM_LPDDR5 2
#define DRAM_DQ_VREF_X8_BYTELANE_MAX_NUM_LPDDR5 2
#define DRAM_CA_VREF_X8_BYTELANE_MAX_NUM_LPDDR4 1
#define HOST_DQ_VREF_X8_BYTELANE_MAX_NUM_LPDDR4 2
#define DRAM_DQ_VREF_X8_BYTELANE_MAX_NUM_LPDDR4 1
#define DRAM_CA_VREF_X16_RANK_MAX_NUM_LPDDR5 2
#define HOST_DQ_VREF_X16_RANK_MAX_NUM_LPDDR5 1
#define DRAM_DQ_VREF_X16_RANK_MAX_NUM_LPDDR5 2
#define DRAM_CA_VREF_X16_RANK_MAX_NUM_LPDDR4 2
#define HOST_DQ_VREF_X16_RANK_MAX_NUM_LPDDR4 1
#define DRAM_DQ_VREF_X16_RANK_MAX_NUM_LPDDR4 2
#define DRAM_CA_VREF_X16_BYTELANE_MAX_NUM_LPDDR5 1
#define HOST_DQ_VREF_X16_BYTELANE_MAX_NUM_LPDDR5 2
#define DRAM_DQ_VREF_X16_BYTELANE_MAX_NUM_LPDDR5 2
#define DRAM_CA_VREF_X16_BYTELANE_MAX_NUM_LPDDR4 1
#define HOST_DQ_VREF_X16_BYTELANE_MAX_NUM_LPDDR4 2
#define DRAM_DQ_VREF_X16_BYTELANE_MAX_NUM_LPDDR4 1
#define EDGETYPE_MAX_NR EDGETYPE_MAX_NUM
#define RANK_MAX_NR RANK_MAX_NUM
#define BYTELANE_LPDDR4_MAX_NR BYTELANE_MAX_NUM
#ifdef DDR_SINGLE_CHANNEL
#define CHANNEL_MAX_NUM 1
#define DMSS_CHANS_MAX_NUM 1
#define DBC_MAX_NUM 1
#define ZCAL_START_CHANNEL CHANNEL_ID_A
#elif defined(DDR_TWO_CHANNEL)
#define CHANNEL_MAX_NUM 2
#define DMSS_CHANS_MAX_NUM 2
#define DBC_MAX_NUM 2
#define ZCAL_START_CHANNEL CHANNEL_ID_B
#elif defined(DDR_FOUR_CHANNEL)
#define CHANNEL_MAX_NUM 4
#define DMSS_CHANS_MAX_NUM 4
#define DBC_MAX_NUM 4
#define ZCAL_START_CHANNEL CHANNEL_ID_B
#endif
#define DMC_GRPS_MAX_NUM 0x2
#define DMC_FSPS_MAX_NUM 0x2
#define UCE_NUM_MAX CHANNEL_LPDDR4_MAX_NR
#define UCE_MBX_ID_0 0
#define UCE_MBX_ID_1 1
#define IPC_LPM3_PROCESS_ID 0x0
#define IPC_UCE_PROCESS_ID 0x1
#define LPDDR4_PHY_BYTELANE_NUM 2
#define LPDDR4_PACK_BYTELANE_NUM 2
#define CHANNEL_ID_A 0
#define CHANNEL_ID_B 1
#define CHANNEL_ID_C 2
#define CHANNEL_ID_D 3
#define LPDDR4_DMC_INIT_MASK DDR_NUM_TO_MASK(CHANNEL_MAX_NUM)
#define LPDDR4_PACK_INIT_MASK DDR_NUM_TO_MASK(CHANNEL_MAX_NUM)
#define LPDDR4_PHY_INIT_MASK DDR_NUM_TO_MASK(CHANNEL_MAX_NUM)
#define PACK_MAX_NUM CHANNEL_MAX_NUM
#define PHY_MAX_NUM CHANNEL_MAX_NUM
#define DMC_MAX_NUM CHANNEL_MAX_NUM
#define CHANNEL_LPDDR4_MAX_NR CHANNEL_MAX_NUM
#define DDR_DMC_MASK LPDDR4_DMC_INIT_MASK
#define DDR_PACK_MASK LPDDR4_PACK_INIT_MASK
#define DDR_PHY_MASK LPDDR4_PHY_INIT_MASK
#define LPDDR_WDQNBDL_MAX 127
#define LPDDR_RDQNBDL_MAX 127
#define DDR_INIT_TYPE_ONCE 0
#define DDR_INIT_TYPE_STEP 1
#define DDR_INIT_TYPE_STEP_EC 2
#define DDR_INIT_TYPE_STEP_JUMP 3
#define DDR_TARGET_PRARA_STATIC 0
#define DDR_TARGET_PRARA_MODIFY 1
#define DDR_CBT_X16_MODE 0x0
#define DDR_CBT_X8_MODE 0x1
#define TRAINING_TYPE_HW 1
#define TRAINING_TYPE_SW 2
#define TRAINING_TYPE_EYET 1
#define TRAINING_TYPE_VREFT 2
#define TRAINING_TYPE_NODCCT 0
#define TRAINING_TYPE_IODCCT 1
#define TRAINING_TYPE_PHYDCCT 2
#define INVALID_RDQDCA_RES 0xFFFF
#define INVALID_RDQSDCC_RES 0xFFFF
#define TYPE_CAT 1
#define TYPE_CST 2
#define LEFTBOUND 1
#define ADDRBDL (0x1U << 1)
#define RDQNBDL (0x1U << 2)
#define DXNWDQBDL (0x1U << 3)
#define RANKSW (0x1U << 4)
#define BDL_MASK 0x3FFU
#define PHASE_MASK 0xFFU
#define PHASE_RATIO 48
#define DMC_RINT_CLEAR_VALUE 0xFFFFFFFF
#define DDR_NUM_TO_MASK(num) ((0x1UL << (num)) - 1)
#ifdef PRODUCT_DDR_AGING_TEST
#define DDR_AVS_PA_MARGIN_LOW 0
#define DDR_AVS_STABLE_MARGIN_LOW 0
#define DDR_AVS_PA_MARGIN_NORMAL 5
#define DDR_AVS_STABLE_MARGIN_NORMAL 5
#define DDR_AVS_PA_MARGIN_HIGH 0
#define DDR_AVS_STABLE_MARGIN_HIGH 0
#define DDR_CORE_VOL_HIGH_0 655
#define DDR_CORE_VOL_HIGH_1 690
#define DDR_CORE_VOL_HIGH_2 760
#define DDR_CORE_VOL_HIGH_3 790
#define DDR_CORE_VOL_HIGH_4 820
#define DDR_CORE_VOL_HIGH_5 830
#define DDR_CORE_VOL_HIGH_6 840
#define DDR_CORE_VOL_HIGH_7 875
#define DDR_CORE_VOL_NORMAL_0 640
#define DDR_CORE_VOL_NORMAL_1 670
#define DDR_CORE_VOL_NORMAL_2 740
#define DDR_CORE_VOL_NORMAL_3 770
#define DDR_CORE_VOL_NORMAL_4 800
#define DDR_CORE_VOL_NORMAL_5 810
#define DDR_CORE_VOL_NORMAL_6 820
#define DDR_CORE_VOL_NORMAL_7 850
#define DDR_CORE_VOL_LOW_0 625
#define DDR_CORE_VOL_LOW_1 650
#define DDR_CORE_VOL_LOW_2 720
#define DDR_CORE_VOL_LOW_3 750
#define DDR_CORE_VOL_LOW_4 780
#define DDR_CORE_VOL_LOW_5 790
#define DDR_CORE_VOL_LOW_6 800
#define DDR_CORE_VOL_LOW_7 825
#define DDR_VDDQ_VOL_HIGH 620
#define DDR_VDDQ_VOL_NORMAL 620
#define DDR_VDDQ_VOL_LOW 620
#define DDR_VDDQH_VOL_HIGH_LPDDR5 520
#define DDR_VDDQH_VOL_NORMAL_LPDDR5 520
#define DDR_VDDQH_VOL_LOW_LPDDR5 520
#define DDR_VDDQL_VOL_HIGH_LPDDR5 400
#define DDR_VDDQL_VOL_NORMAL_LPDDR5 400
#define DDR_VDDQL_VOL_LOW_LPDDR5 400
#define DDR_VDD2H_VOL_HIGH 1150
#define DDR_VDD2H_VOL_NORMAL 1120
#define DDR_VDD2H_VOL_LOW 1090
#define DDR_VDD2H_VOL_HIGH_LPDDR5 1110
#define DDR_VDD2H_VOL_NORMAL_LPDDR5 1080
#define DDR_VDD2H_VOL_LOW_LPDDR5 1050
#define DDR_VDD2L_VOL_HIGH 945
#define DDR_VDD2L_VOL_NORMAL 920
#define DDR_VDD2L_VOL_LOW 895
#define DDR_VDD1_VOL_HIGH 1850
#define DDR_VDD1_VOL_NORMAL 1800
#define DDR_VDD1_VOL_LOW 1750
#define DDR_PHYPLL_VOL_HIGH 1235
#define DDR_PHYPLL_VOL_NORMAL 1200
#define DDR_PHYPLL_VOL_LOW 1165
#define DDR_MEM_VOL_HIGH 800
#define DDR_MEM_VOL_NORMAL 800
#define DDR_MEM_VOL_LOW 800
#else
#define DDR_AVS_PA_MARGIN_LOW 0
#define DDR_AVS_STABLE_MARGIN_LOW 0
#if defined (__SLT_FEATURE__)
#define DDR_AVS_PA_MARGIN_NORMAL 5
#define DDR_AVS_STABLE_MARGIN_NORMAL 0
#else
#define DDR_AVS_PA_MARGIN_NORMAL 0
#define DDR_AVS_STABLE_MARGIN_NORMAL 0
#endif
#define DDR_AVS_PA_MARGIN_HIGH 0
#define DDR_AVS_STABLE_MARGIN_HIGH 0
#define DDR_CORE_VOL_HIGH_0 660
#define DDR_CORE_VOL_HIGH_1 700
#define DDR_CORE_VOL_HIGH_2 770
#define DDR_CORE_VOL_HIGH_3 805
#define DDR_CORE_VOL_HIGH_4 840
#define DDR_CORE_VOL_HIGH_5 850
#define DDR_CORE_VOL_HIGH_6 860
#define DDR_CORE_VOL_HIGH_7 880
#define DDR_CORE_VOL_NORMAL_0 640
#define DDR_CORE_VOL_NORMAL_1 670
#define DDR_CORE_VOL_NORMAL_2 740
#define DDR_CORE_VOL_NORMAL_3 770
#define DDR_CORE_VOL_NORMAL_4 800
#define DDR_CORE_VOL_NORMAL_5 810
#define DDR_CORE_VOL_NORMAL_6 820
#define DDR_CORE_VOL_NORMAL_7 850
#define DDR_CORE_VOL_LOW_0 610
#define DDR_CORE_VOL_LOW_1 640
#define DDR_CORE_VOL_LOW_2 705
#define DDR_CORE_VOL_LOW_3 735
#define DDR_CORE_VOL_LOW_4 760
#define DDR_CORE_VOL_LOW_5 770
#define DDR_CORE_VOL_LOW_6 780
#define DDR_CORE_VOL_LOW_7 810
#define DDR_VDDQ_VOL_HIGH 650
#define DDR_VDDQ_VOL_NORMAL 620
#define DDR_VDDQ_VOL_LOW 590
#define DDR_VDDQH_VOL_HIGH_LPDDR5 545
#define DDR_VDDQH_VOL_NORMAL_LPDDR5 520
#define DDR_VDDQH_VOL_LOW_LPDDR5 495
#define DDR_VDDQL_VOL_HIGH_LPDDR5 420
#define DDR_VDDQL_VOL_NORMAL_LPDDR5 400
#define DDR_VDDQL_VOL_LOW_LPDDR5 380
#define DDR_VDD2H_VOL_HIGH 1170
#define DDR_VDD2H_VOL_NORMAL 1120
#define DDR_VDD2H_VOL_LOW 1070
#define DDR_VDD2H_VOL_HIGH_LPDDR5 1130
#define DDR_VDD2H_VOL_NORMAL_LPDDR5 1080
#define DDR_VDD2H_VOL_LOW_LPDDR5 1030
#define DDR_VDD2L_VOL_HIGH 965
#define DDR_VDD2L_VOL_NORMAL 920
#define DDR_VDD2L_VOL_LOW 875
#if defined (__SLT_FEATURE__)
#define DDR_VDD1_VOL_HIGH 1830
#else
#define DDR_VDD1_VOL_HIGH 1890
#endif
#define DDR_VDD1_VOL_NORMAL 1800
#define DDR_VDD1_VOL_LOW 1710
#define DDR_PHYPLL_VOL_HIGH 1260
#define DDR_PHYPLL_VOL_NORMAL 1200
#define DDR_PHYPLL_VOL_LOW 1140
#define DDR_MEM_VOL_HIGH 840
#define DDR_MEM_VOL_NORMAL 800
#define DDR_MEM_VOL_LOW 760
#endif
#define DDR_VOL_LEVEL0 0
#define DDR_VOL_LEVEL1 1
#define DDR_VOL_LEVEL2 2
#define DDR_VOL_LEVEL3 3
#define DDR_VOL_LEVEL4 4
#define DDR_VOL_LEVEL5 5
#define DDR_VOL_LEVEL6 6
#define DDR_VOL_LEVEL7 7
#define FREQ_VOLT_RANGE 8
#define DDR_SCENE_ID_NT_0 0
#define DDR_SCENE_ID_LT 1
#define DDR_SCENE_ID_NT_20 2
#define DDR_SCENE_ID_NT_40 3
#define DDR_SCENE_ID_NT_60 4
#define DDR_SCENE_ID_MAX 5
#define DDR_NORMALTEMP 0
#define DDR_LOWTEMP 1
#define TRAINING_RESULT_IDX_MAP_INVALID_VALUE 0xFF
#define MANU_ID_SAMSUNG 0x1
#define MANU_ID_MICRON 0xff
#define MANU_ID_HYNIX 0x6
#define DDR_REMAP_REGION0 0x0
#define DDR_REMAP_REGION1 0x1
#define DDR_REMAP_REGION2 0x2
#define DDR_REMAP_REGION3 0x3
#define DDR_REMAP_REGION4 0x4
#define DDR_REMAP_REGION5 0x5
#define DDR_REMAP_REGION6 0x6
#define DDR_REMAP_REGION7 0x7
#define DDR_REMAP_REGION8 0x8
#define DDR_REMAP_REGION9 0x9
#define DDR_REMAP_REGION10 0xA
#define DDR_REMAP_REGION11 0xB
#define DDR_REMAP_REGION12 0xC
#define DDR_REMAP_REGION13 0xD
#define DDR_REMAP_REGION14 0xE
#define DDR_REMAP_REGION15 0xF
#define DDR_HOST_IO_RON_40OHM 7
#define DDR_HOST_IO_RON_48OHM 6
#define DDR_HOST_IO_RON_60OHM 5
#define DDR_HOST_IO_RON_80OHM 4
#define DDR_HOST_IO_RON_120OHM 2
#define DDR_HOST_IO_RON_240OHM 1
#define DDR_DRAM_IO_RON_34OHM 7
#define DDR_DRAM_IO_RON_40OHM 6
#define DDR_DRAM_IO_RON_48OHM 5
#define DDR_DRAM_IO_RON_60OHM 4
#define DDR_DRAM_IO_RON_80OHM 3
#define DDR_DRAM_IO_RON_120OHM 2
#define DDR_DRAM_IO_RON_240OHM 1
#define HOST_ODT_VDDQ_2 1
#define HOST_ODT_3VDDQ_5 2
#define DRAM_ODT_VDDQ_2 1
#define DRAM_ODT_3VDDQ_5 2
#define DDR_HOST_VREF_150MV 0x16U
#define DDR_HOST_VREF_135MV 0x13U
#define DDR_HOST_VREF_180MV 0x1CU
#define DDR_HOST_VREF_190MV 0x1EU
#define DDR_HOST_VREF_210MV 0x22U
#define HOST_PU_CAL_VDDQ_2 0
#define HOST_PU_CAL_3VDDQ_5 1
#define DRAM_PU_CAL_VDDQ_2 0
#define DRAM_PU_CAL_3VDDQ_5 1
#define CK_ODT_1RANK 1
#define CK_ODT_2RANK 2
#define PHASE_SEL_ADDRPH_A 1
#define PHASE_SEL_CMD1TPH 2
#define PHASE_SEL_STATIC_REG 3
#define PHASE_SEL_ACCTL_POSEDGE 4
#define PHASE_MAX 0xE0U
#define PHASE_360 0x40U
#define PHASE_180 0x20U
#define PHASE_90 0x10U
#define PHASE_60 0x8U
#define PHASE_45 0x6U
#define PHASE_30 0x4U
#define PHASE_15 0x2U
#define PHASE_0 0x0U
#define DYNAMIC_TRACK_TYPE0 0
#define DYNAMIC_TRACK_TYPE1 1
#define PHYGATE_TYPE_GCNT 1
#define PHYGATE_TYPE_AUTO 2
#define PHYGATE_TYPE_DIG_EN 3
#define PLL_SOURCE_SCPLL 0
#define PLL_SOURCE_FNPLL 1
#define PLL_SWITCH_A 1
#define PLL_SWITCH_B 2
typedef enum {
 DDR_CORE_VOL = 0,
 DDR_VDDQ_VOL,
 DDR_VDD2H_VOL,
 DDR_VDD2L_VOL,
 DDR_VDD1_VOL,
 DDR_PHYPLL_VOL,
 DDR_MEM_VOL,
 DDR_VOL_MAX
} DDR_VOL_ID;
typedef enum {
 DDRC_NUM_0 = 0,
#ifndef DDR_SINGLE_CHANNEL
 DDRC_NUM_1,
#endif
 DDRC_NUM_MAX
} DDRC_NUM;
typedef enum {
 DMC_NUM_0 = 0,
#ifndef DDR_SINGLE_CHANNEL
 DMC_NUM_1,
#endif
 DMC_NUM_MAX
} DMC_NUM;
typedef enum {
 DDR_PLL0 = 0x1,
 DDR_PLL1 = 0x2,
 DDR_PLL2_B = 0x4,
 DDR_PLL2 = 0x8
} DDR_PLL_IDX;
typedef enum {
 ASIC = 0,
 FPGA,
 EMULATOR
} DDR_BOARD_TYPE;
#define DDR_BURST_LEN_16 0
#define DDR_BURST_LEN_32 1
#define DDR_BURST_LEN_OTF 2
typedef enum {
 DDR_AUTOFSGT_ENABLE = 1,
 DDR_AUTOFSGT_DISABLE,
 DDR_AUTOFSGT_LOGIC_EN,
 DDR_AUTOFSGT_LOGIC_DIS
} DDR_AUTOFSGT_CMD_ID;
typedef enum {
 DDR_AUTOFSGT_BIT_LPMCU = 0,
 DDR_AUTOFSGT_BIT_LPMCU_NMI,
 DDR_AUTOFSGT_BIT_BL2,
 DDR_AUTOFSGT_BIT_FASTBOOT,
 DDR_AUTOFSGT_BIT_BL31,
 DDR_AUTOFSGT_BIT_SECURE_OS,
 DDR_AUTOFSGT_BIT_SENSORHUB,
 DDR_AUTOFSGT_PROXY_CLIENT_DDRFLUX,
 DDR_AUTOFSGT_PROXY_CLIENT_DMSSPT,
 DDR_AUTOFSGT_PROXY_CLIENT_BUTT
} DDR_AUTOFSGT_PROXY_CLIENT_ID;
typedef enum {
 DDR_NODE_OPP_FREQ = 0,
 DDR_NODE_OPP_VOL,
 DDR_NODE_OPP_MAX
} DDR_NODE_OPP_ID;
typedef enum {
 DMSS_NODE_OPP_FREQ = 0,
 DMSS_NODE_OPP_VOL,
 DMSS_NODE_OPP_MAX
} DMSS_NODE_OPP_ID;
enum perf_scene_case_id {
 PERF_SCENE_CASEI = 0,
 PERF_SCENE_CASEII,
 PERF_SCENE_CASEIII,
 PERF_SCENE_CASEIV,
 PERF_SCENE_CASEV,
 PERF_SCENE_CASEVI,
 PERF_SCENE_CASE_MAX
};
#define DMSS_SEC_REGION_MAX 32
#define MPU_RAM_SIZE 0x2000
#define DMSS_ASI_MAX 19
#define DMSS_DMI_MAX 2
#define DMSS_AMI_MAX 1
#define DMSS_PER_ASI_SIZE 0x800
#define AXI_MAX_PORT DMSS_ASI_MAX
#define DMSS_CHANS_MAX DMSS_CHANS_MAX_NUM
#define SEC_REGION_MAX DMSS_SEC_REGION_MAX
#define SEC_MODE_CNT 1
#define DMSS_ASI_MAX_NUM DMSS_ASI_MAX
#define DMSS_ASI_RGNS_MAX_NUM DMSS_SEC_REGION_MAX
#define DMSS_AMI_MAX_NUM DMSS_AMI_MAX
#ifdef DDR_BASE_ADDR_LPMCU
#define DDR_DMSS_BASE_ADDR SOC_LPMCU_DMSS_BASE_ADDR
#define DDR_DMCPACK0_BASE_ADDR SOC_LPMCU_DMCPACK0_BASE_ADDR
#define SOC_SCTRL_BASE_ADDR SOC_LPMCU_SCTRL_BASE_ADDR
#else
#define DDR_DMSS_BASE_ADDR SOC_ACPU_DMSS_BASE_ADDR
#define DDR_DMCPACK0_BASE_ADDR SOC_ACPU_DMCPACK0_BASE_ADDR
#define SOC_SCTRL_BASE_ADDR SOC_ACPU_SCTRL_BASE_ADDR
#endif
#define DDR_REG_DBC_CHANNEL_OFFSET(n) ((((unsigned long)(n) >> 0x1) & 0x1UL) * 0x800UL + ((unsigned long)(n) & 0x1UL) * 0x4000UL)
#define DDR_REG_DMSS (DDR_DMSS_BASE_ADDR)
#define DDR_REG_AXI(n) (DDR_DMSS_BASE_ADDR + 0x800UL * (n))
#define DDR_REG_GLOBAL (DDR_DMSS_BASE_ADDR + 0x6000UL)
#define DDR_REG_DBC(n) (DDR_DMSS_BASE_ADDR + 0x30000UL + DDR_REG_DBC_CHANNEL_OFFSET(n))
#define DDR_REG_EXMBIST (DDR_DMSS_BASE_ADDR + 0x38000UL)
#define DDR_REG_MPU (DDR_DMSS_BASE_ADDR + 0x20000UL)
#define DDR_REG_MPU_SIZE 0x2000UL
#define DDR_REG_CHANNEL_OFFSET(n) (0x20000UL * (n))
#define DDR_REG_RADIO_CHANNEL_OFFSET 0xC0000U
#define DDR_REG_PACK(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n))
#define DDR_REG_PHY(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x1000UL)
#define DDR_REG_SW_TRAIN(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x2000UL)
#define DDR_REG_PTE(n) DDR_REG_SW_TRAIN(n)
#define DDR_REG_DMC(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x4000UL)
#define DDR_REG_DMC_TOP(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x6000UL)
#define DDR_REG_DUMREG(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x6000UL)
#define DDR_REG_UCE_TCM(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x8000UL)
#define DDR_REG_UCE_IPC(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x13000UL)
#define DDR_REG_UCE_UART(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x14000UL)
#define DDR_REG_UCE_SCTRL(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x15000UL)
#define DDR_REG_UCE_TIMER(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x16000UL)
#define DDR_REG_UCE_WDG(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x17000UL)
#define DDR_REG_UCE_PACK(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x18000UL)
#define DDR_REG_UCE_PHY(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x19000UL)
#define DDR_REG_UCE_PACK_SWPT(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x1A000UL)
#define DDR_REG_UCE_DMC(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x1B000UL)
#define DDR_REG_UCE_DMC_TOP(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x1D000UL)
#define DDR_REG_UCE_DUMREG(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x1D000UL)
#define DDR_REG_RADIO_PACK (DDR_REG_PACK(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_PHY (DDR_REG_PHY(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_SW_TRAIN (DDR_REG_SW_TRAIN(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_PTE (DDR_REG_PTE(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_DMC (DDR_REG_DMC(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_DMC_TOP (DDR_REG_DMC_TOP(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_DUMREG (DDR_REG_DUMREG(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_TCM (DDR_REG_UCE_TCM(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_IPC (DDR_REG_UCE_IPC(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_UART (DDR_REG_UCE_UART(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_SCTRL (DDR_REG_UCE_SCTRL(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_TIMER (DDR_REG_UCE_TIMER(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_WDG (DDR_REG_UCE_WDG(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_PACK (DDR_REG_UCE_PACK(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_PHY (DDR_REG_UCE_PHY(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_PACK_SWPT (DDR_REG_UCE_PACK_SWPT(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_DMC (DDR_REG_UCE_DMC(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_DMC_TOP (DDR_REG_UCE_DMC_TOP(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define DDR_REG_RADIO_UCE_DUMREG (DDR_REG_UCE_DUMREG(0) + DDR_REG_RADIO_CHANNEL_OFFSET)
#define UCE_DDR_REG_PACK (SOC_UCE_UCE_PACK_BASE_ADDR)
#define UCE_DDR_REG_PHY (SOC_UCE_UCE_PACK_BASE_ADDR + 0x1000UL)
#define UCE_DDR_PACK_SWPT (SOC_UCE_UCE_PACK_SWPT_BASE_ADDR)
#define UCE_DDR_REG_DMC (SOC_UCE_UCE_DMC_BASE_ADDR)
#define UCE_DDR_REG_DMC_TOP (SOC_UCE_UCE_DMC_BASE_ADDR + 0x2000UL)
#define UCE_DDR_REG_DUMREG (SOC_UCE_UCE_DMC_BASE_ADDR + 0x2000UL)
#ifndef REG_BASE_DMSS
#define REG_BASE_DMSS DDR_REG_DMSS
#endif
#define DDRC_REG_DMC(n) (DDR_REG_DMC(n))
#define DDR_REG_DMC_CFG(n) (DDRC_REG_DMC(n))
#ifndef DDR_EDA
#define DDR_REG_CFG_CAT_BDL_STEP 0x0
#define DDR_REG_CFG_DVREFT_STEP 0x1
#define DDR_REG_CFG_RPAT_CNT_NUM 0xf
#define DDR_REG_CFG_CAL_ALT_NUM 0x4
#define DDR_REG_CFG_WDET_MPC_CNT 0xf
#define DDR_REG_CFG_DUMMY_RD_CNT 0x23280
#define DDR_REG_CFG_LP_L2_IDLE 0x258
#define DDR_REG_CFG_LP_L3_IDLE 0x4b0
#define DDR_REG_CFG_RETRAIN_THRD 0xFFFF
#define DDR_REG_CFG_ZQ_INTLV_PRD 0x5F5E100
#define DDR_REG_CFG_GT_BDL_STEP 0x0
#define DDR_REG_CFG_RPAT_CNT_NUM_OPEN 0xf
#endif
#define DDR_PHYPLL_A 1
#define DDR_PHYPLL_B 2
#define DDR_DYNAMIC_TRACK_DISABLE 0
#define DDR_DYNAMIC_TRACK_ALL_BIT 1
#define DDR_DYNAMIC_TRACK_SINGLE_BIT 2
#define DDR_REG_CFG_EN_DXCTL_RXN_2ND_DQ 0xFF
#define DDR_REG_CFG_EN_DXCTL_RXP_2ND_DQ 0xFF
#define DDR_REG_CFG_EN_DXCTL_RXN_2ND_DM 0x1
#define DDR_REG_CFG_EN_DXCTL_RXP_2ND_DM 0x1
#define DDR_REG_CFG_EN_REG_DQSDLY_PRI_EN 0x1
#define DDR_REG_CFG_EN_DXCTL_SW_MARGIN_CODE 0x6
#define DDR_REG_CFG_SINGLE_BIT_EN_DXCTL_RXN_2ND_DQ 0x1
#define DDR_REG_CFG_DIS_DXCTL_RXN_2ND_DQ 0x0
#define DDR_REG_CFG_DIS_DXCTL_RXP_2ND_DQ 0x0
#define DDR_REG_CFG_DIS_DXCTL_RXN_2ND_DM 0x0
#define DDR_REG_CFG_DIS_DXCTL_RXP_2ND_DM 0x0
#define DDR_REG_CFG_DIS_REG_DQSDLY_PRI_EN 0x0
#define DDR_REG_CFG_DIS_DXCTL_SW_MARGIN_CODE 0x0
#define DDR_REG_CFG_ZCODE_PDRV_CAL_MAX 0x7F
#define DDR_REG_CFG_ZCODE_NDRV_CAL_MAX 0x3F
#define DDR_REG_CFG_ZCODE_PDRV_CAL_MASK 0x7F
#define DDR_REG_CFG_ZCODE_NDRV_CAL_MASK 0x3F
#define DDR_REG_CFG_UC_ROWACT_TYPE 0x0
#define DDR_REG_CFG_UC_RT_POPULATE 0x2
#define DDR_REG_CFG_UC_REGIF_WST 0x1
#define DDR_REG_CFG_UC_MODE_EN 0x0
#define DDR_FREQ_SCBAKDATA_ADDR SOC_SCTRL_SCBAKDATA4_ADDR(SOC_SCTRL_BASE_ADDR)
#define DDR_FREQ_SCBAKDATA_START 8
#define DDR_FREQ_SCBAKDATA_END 11
#define DDR_INFO_SCBAKDATA_ADDR SOC_SCTRL_SCBAKDATA7_ADDR(SOC_SCTRL_BASE_ADDR)
#define DDR_MANU_SCBAKDATA_START 0
#define DDR_MANU_SCBAKDATA_END 7
#define DDR_SIZE_SCBAKDATA_START 8
#define DDR_SIZE_SCBAKDATA_END 15
#define DMSS_FREQ_SCBAKDATA_START 16
#define DMSS_FREQ_SCBAKDATA_END 31
#define DDR_ADDR_ALIGN(addr,align) (((uintptr_t)(addr) + (align) - 1) / (align) * (align))
#define DDR_LPRAM_ADDR_TO_AP_ADDR(addr) (((addr) - SOC_LPMCU_DMCPACK0_BASE_ADDR) + SOC_ACPU_DMCPACK0_BASE_ADDR)
#define LPM3_ADDR_TO_ACORE_ADDR_IN_LPRAM(addr) ((((uintptr_t)(addr)) > (SOC_LPMCU_LP_RAM_BASE_ADDR)) ? (((unsigned long)(addr) - SOC_LPMCU_LP_RAM_BASE_ADDR) + SOC_ACPU_LP_RAM_BASE_ADDR) : (SOC_ACPU_LP_RAM_BASE_ADDR))
#define SOC_LPMCU_LP_RAM_BASE_SIZE (LPMCU_RAM_SIZE)
#define LPM3_ADDR_TO_ACORE_ADDR_IN_MMBUF(addr) (((uintptr_t)(addr) - SOC_LPMCU_SECRAM_remap_BASE_ADDR) + SOC_ACPU_SECRAM_BASE_ADDR)
#define XLOADRE_ADDR_TO_FASTBOOT_ADDR(addr) (((uintptr_t)(addr) > (SOC_LPMCU_LP_RAM_BASE_ADDR + SOC_LPMCU_LP_RAM_BASE_SIZE)) ? LPM3_ADDR_TO_ACORE_ADDR_IN_MMBUF(addr) : LPM3_ADDR_TO_ACORE_ADDR_IN_LPRAM(addr))
#define DDR_PARAM_PACK(a,b,c,d) ((((u32)(a)) << 24) | (((u32)(b)) << 16) | (((u32)(c)) << 8) | (d))
#define ATF_ALIGN_LENGTH 8
#define HIFASTBOOT_SEC_DATA_ADDR HISI_BL2_DDR_SHMEM_ADDR
#define HIFASTBOOT_SEC_DATA_SIZE DDR_ADDR_ALIGN(sizeof(seccfg_info), ATF_ALIGN_LENGTH)
#define HIFASTBOOT_INFO_DATA_ADDR (HIFASTBOOT_SEC_DATA_ADDR + HIFASTBOOT_SEC_DATA_SIZE)
#define HIFASTBOOT_INFO_DATA_SIZE (HISI_BL2_DDR_SHMEM_SIZE - (HIFASTBOOT_INFO_DATA_ADDR - HIFASTBOOT_SEC_DATA_ADDR))
#ifndef DDR_EDA
#define DDR_BUILD_BUG_ON(e) ((void)(sizeof(struct { int:1; int:-((int)!!(e)); })))
#else
#define DDR_BUILD_BUG_ON(e) 
#endif
#define DDR_INFO_SECRET_KEY 0x646472
#define DMSS_VSET PMIC_BUCK1_VSET_ADDR(0)
#define DMC_CORE_VSET PMIC_BUCK1_VSET_ADDR(0)
#define DMSS_VMIN 400
#define DMC_CORE_VMIN 400
#define PMU6421_STEP 5
#define DDR_SEC_CFG_MODEM_MASK 0x321U
#define DDR_SEC_CFG_AP_MASK (~(DDR_SEC_CFG_MODEM_MASK))
#define DDR_MPU_CFG_SIZE_4G 0
#define DDR_MPU_CFG_SIZE_8G 1
#define DDR_MPU_CFG_SIZE_16G 2
#define MATRIX_OHOT_START_BIT 1
#define MATRIX_SYS_ADDR_START_BIT 1
#define DDR_TEST_LPDDR5_MATRIX_0 0x3CE34CU
#define DDR_TEST_LPDDR5_MATRIX_1 0x0U
#define DDR_TEST_LPDDR5_MATRIX_2 0x61440C2U
#define DDR_TEST_LPDDR5_MATRIX_3 0xB289207U
#define DDR_TEST_LPDDR5_MATRIX_4 0x13491400U
#define DDR_TEST_LPDDR5_MATRIX_5 0x185D6554U
#define DDR_TEST_LPDDR4_MATRIX_0 0xE34C000U
#define DDR_TEST_LPDDR4_MATRIX_1 0x0U
#define DDR_TEST_LPDDR4_MATRIX_2 0x61440C2U
#define DDR_TEST_LPDDR4_MATRIX_3 0xB289207U
#define DDR_TEST_LPDDR4_MATRIX_4 0x124503C0U
#define DDR_TEST_LPDDR4_MATRIX_5 0x17595513U
#define DDR_WR_PRE_LEN_0T 0U
#define DDR_WR_PRE_LEN_1T 1U
#define DDR_WR_PRE_LEN_2T 2U
#define DDR_WR_PRE_LEN_3T 3U
#define DDR_WR_PST_LEN_0P5T 0U
#define DDR_WR_PST_LEN_1P5T 1U
#define DDR_RD_PRE_LEN_1T 0U
#define DDR_RD_PRE_LEN_2T 1U
#define DDR_RD_PRE_LEN_4T 2U
#define DDR_RD_PRE_MODE_STATIC 0U
#define DDR_RD_PRE_MODE_TOGGLE 1U
#define DDR_NORMAL_REG_BITNUM 32
#define DDR_SIZE_256MB 256
#define DDR_SIZE_384MB 384
#define DDR_SIZE_512MB 512
#define DDR_SIZE_768MB 768
#define DDR_SIZE_1024MB 1024
#define DDR_SIZE_1536MB 1536
#define DDR_SIZE_2048MB 2048
#define DDR_SIZE_3072MB 3072
#define DDR_SIZE_4096MB 4096
#define DDR_SIZE_6144MB 6144
#define DDR_SIZE_8192MB 8192
#define DDR_SIZE_16384MB 16384
#define DDR_SIZE_32768MB 32768
#define DDR_SIZE_4GB 4
#define DDR_SIZE_6GB 6
#define DDR_SIZE_8GB 8
#define DDR_SIZE_10GB 10
#define DDR_SIZE_12GB 12
#define DDR_SIZE_16GB 16
#define DDR_SIZE_32GB 32
#define DDR_CAPACITY_1KB 0x400
#define DDR_CAPACITY_1MB 0x100000
#define DDR_SIZE_GBTOMB(size_gbyte) ((size_gbyte) * DDR_CAPACITY_1KB)
#define DDR_SIZE_MBTOGB(size_mbyte) ((size_mbyte) / DDR_CAPACITY_1KB)
#define DDR_SIZE_MBTOB(size_mbyte) ((size_mbyte) * DDR_CAPACITY_1MB)
#define MODEREG01_MR1_START 0
#define MODEREG01_MR1_END 7
#define MODEREG01_MR2_START 8
#define MODEREG01_MR2_END 15
#define MODEREG01_MR3_START 16
#define MODEREG01_MR3_END 23
#define MODEREG01_MR11_START 24
#define MODEREG01_MR11_END 31
#define MODEREG23_LPDDR4_MR22_START 0
#define MODEREG23_LPDDR4_MR22_END 7
#define MODEREG23_LPDDR4_MR23_START 8
#define MODEREG23_LPDDR4_MR23_END 15
#define MODEREG23_LPDDR5_MR17_START 0
#define MODEREG23_LPDDR5_MR17_END 7
#define MODEREG23_LPDDR5_MR18_START 8
#define MODEREG23_LPDDR5_MR18_END 15
#define MODEREG23_LPDDR5_MR16_START 16
#define MODEREG23_LPDDR5_MR16_END 23
#define MODEREG23_LPDDR5_MR30_START 24
#define MODEREG23_LPDDR5_MR30_END 31
#define MODEREG45_LPDDR4_MR15_START 0
#define MODEREG45_LPDDR4_MR15_END 7
#define MODEREG45_LPDDR4_MR20_START 8
#define MODEREG45_LPDDR4_MR20_END 15
#define MODEREG45_LPDDR4_MR32_START 16
#define MODEREG45_LPDDR4_MR32_END 23
#define MODEREG45_LPDDR4_MR40_START 24
#define MODEREG45_LPDDR4_MR40_END 31
#define MODEREG45_LPDDR5_MR31_START 0
#define MODEREG45_LPDDR5_MR31_END 7
#define MODEREG45_LPDDR5_MR32_START 8
#define MODEREG45_LPDDR5_MR32_END 15
#define MODEREG45_LPDDR5_MR33_START 16
#define MODEREG45_LPDDR5_MR33_END 23
#define MODEREG45_LPDDR5_MR34_START 24
#define MODEREG45_LPDDR5_MR34ND 31
#define MODEREG67_MR13_START 0
#define MODEREG67_MR13_END 7
#define MODEREG67_MR14_START 8
#define MODEREG67_MR14_END 15
#define MODEREG67_MR12_START 16
#define MODEREG67_MR12_END 23
#define MODEREG67_MR15_START 24
#define MODEREG67_MR15_END 31
#define SW_MRW_JEDEC_MRW_FORMAT 0x0U
#define SW_MRW_NON_JEDEC_FORMAT 0x1U
#define TMRS_CODE_PHASE1_SEL 0x0U
#define TMRS_CODE_TMRS_LOCK 0x093U
#define TMRS_CODE_MR31_ENABLE 0x720U
#define TMRS_MA_CODE 0x9U
#define TMRS_CODE_INPUT_CMD_NUM 5
#define TMRS_CODE_INPUT_GET_CMD(code,cmd_id) ((code >> (4 * cmd_id)) & 0xFU)
#define TMRS_MODE_ENTER_STEP1 0x20U
#define TMRS_MODE_ENTER_STEP2 0x20U
#define TMRS_MODE_ENTER_STEP3 0x20U
#define TMRS_MODE_ENTER_STEP4 0x7FU
#define SFC_CMD_READ 0x1U
#define SFC_CMD_WRITE 0x2U
#define SFC_CMD_MWR 0x3U
#define SFC_CMD_ACTIVE 0x4U
#define SFC_CMD_ANYCMD 0x6U
#define SFC_CMD_PRE 0x8U
#define SFC_CMD_VREFCA 0xCU
#define SFC_CMD_WRP 0xDU
#define SFC_CMD_DFIUPD 0xEU
#define SFC_CMD_WL 0xFU
#define SFC_CMD_AREF 0x10U
#define SFC_CMD_PD 0x11U
#define SFC_CMD_XPD 0x12U
#define SFC_CMD_CAS 0x13U
#define SFC_CMD_MPC 0x14U
#define SFC_CMD_SREF 0x15U
#define SFC_CMD_SRDSM 0x16U
#define SFC_CMD_SRPD 0x17U
#define SFC_CMD_XSREF 0x18U
#define SFC_CMD_MRW 0x19U
#define SFC_CMD_MRR 0x1BU
#define SFC_CMD_WFF 0x1CU
#define SFC_CMD_RFF 0x1DU
#define SFC_CMD_RDC 0x1EU
#define SFC_CMD_NOP 0x1FU
#define SFC_CMD_MASK 0x1FU
#define SFC_CMD_OFFSET 0
#define SFC_TIM_TRP 0x0U
#define SFC_TIM_TXARD 0x1U
#define SFC_TIM_TSR 0x2U
#define SFC_TIM_TSRE 0x3U
#define SFC_TIM_TCKE 0x4U
#define SFC_TIM_TZQCS 0x5U
#define SFC_TIM_TZQINIT 0x6U
#define SFC_TIM_TMRD 0x7U
#define SFC_TIM_TMRW 0x8U
#define SFC_TIM_TMRR 0x9U
#define SFC_TIM_TRFC 0xAU
#define SFC_TIM_TRCD 0xBU
#define SFC_TIM_TRESERVE 0xCU
#define SFC_TIM_TRESERVE1 0xDU
#define SFC_TIM_TLAST 0xEU
#define SFC_TIM_CMDQUE1 0xFU
#define SFC_TIM_MASK 0xFU
#define SFC_TIM_OFFSET 5
#define SFC_MRW_MA_OFFSET 9
#define SFC_MRW_MA_MASK 0xFFU
#define SFC_MRW_OP_OFFSET 17
#define SFC_MRW_OP_MASK 0xFFU
#define SFC_MRR_MA_OFFSET 9
#define SFC_MRR_MA_MASK 0xFFU
#define SFC_MRR_OP_MASK 0xFFU
#define SFC_MRR_SFC_MASK 0xFFFFU
#define SFC_MRR_OP_LOWERBYTE_START 0
#define SFC_MRR_OP_LOWERBYTE_END 7
#define SFC_MRR_OP_UPPERBYTE_START 8
#define SFC_MRR_OP_UPPERBYTE_END 15
#define SFC_MPC_OP_OFFSET 9
#define SFC_MPC_OP_MASK 0xFFU
#define SFC_ACTIVE_ROW_OFFSET 9
#define SFC_ACTIVE_ROW_MASK 0x3FFFFU
#define SFC_ACTIVE_BANK_OFFSET 27
#define SFC_ACTIVE_BANK_MASK 0x1FU
#define SFC_PRE_A_OFFSET 9
#define SFC_PRE_A 0x400U
#define SFC_WRITE_COL_OFFSET 9
#define SFC_WRITE_COL_MASK 0xFFFU
#define SFC_WRITE_BANK_OFFSET 27
#define SFC_WRITE_BANK_MASK 0x1FU
#define SFC_READ_COL_OFFSET 9
#define SFC_READ_COL_MASK 0xFFFU
#define SFC_READ_BANK_OFFSET 27
#define SFC_READ_BANK_MASK 0x1FU
#define SFC_CAS_R_OFFSET 9
#define SFC_CAS_R_MASK 0x7U
#define SFC_CAS_R_FS 0x4U
#define SFC_CAS_R_OFF 0x7U
#define SFC_SR_A_OFFSET 9
#define SFC_SR_A_MASK 0x3FFFFU
#define SFC_SR_SRE_A_LPDDR4 0x18U
#define SFC_SR_SRX_A_LPDDR4 0x14U
#define SFC_SR_SRE_A_LPDDR5 0x0U
#define SFC_SR_SRX_A_LPDDR5 0x0U
#define SFC_REF_A_OFFSET 9
#define SFC_REF_A_MASK 0x3FFFFU
#define SFC_REF_A_PERBANK 0x0U
#define SFC_REF_A_ALLBANK 0x400U
#define SFC_REF_BANK_OFFSET 27
#define SFC_REF_BANK_MASK 0x1FU
#define SFC_REF_BANK_ALLBANK 0x0U
#define ACTIVE(bank,row) ((((bank) & SFC_ACTIVE_BANK_MASK) << SFC_ACTIVE_BANK_OFFSET) | (((row) & SFC_ACTIVE_ROW_MASK) << SFC_ACTIVE_ROW_OFFSET) | \
  (SFC_TIM_TRCD << SFC_TIM_OFFSET) | (SFC_CMD_ACTIVE << SFC_CMD_OFFSET))
#define PRECHARGE() ((SFC_PRE_A << SFC_PRE_A_OFFSET) | (SFC_TIM_TRP << SFC_TIM_OFFSET) | (SFC_CMD_PRE << SFC_CMD_OFFSET))
#define SFC_WRITE(bank,col) ((((bank) & SFC_WRITE_BANK_MASK) << SFC_WRITE_BANK_OFFSET) | (((col) & SFC_WRITE_COL_MASK) << 9) | \
  (SFC_TIM_TRESERVE1 << SFC_TIM_OFFSET) | (SFC_CMD_WRITE << SFC_CMD_OFFSET))
#define SFC_READ(bank,col) ((((bank) & SFC_READ_BANK_MASK) << SFC_READ_BANK_OFFSET) | (((col) & SFC_READ_COL_MASK) << SFC_READ_COL_OFFSET) | \
  (SFC_TIM_TRESERVE1 << SFC_TIM_OFFSET) | (SFC_CMD_READ << SFC_CMD_OFFSET))
#define MRW_TIM(op,ma,tim) ((((op) & SFC_MRW_OP_MASK) << SFC_MRW_OP_OFFSET) | (((ma) & SFC_MRW_MA_MASK) << SFC_MRW_MA_OFFSET) | \
        (((tim) & SFC_TIM_MASK) << SFC_TIM_OFFSET) | (SFC_CMD_MRW << SFC_CMD_OFFSET))
#define MRW(op,ma) MRW_TIM(op, ma, SFC_TIM_TMRW)
#define MRR_TIM(ma,tim) ((((ma) & SFC_MRR_MA_MASK) << SFC_MRR_MA_OFFSET) | (((tim) & SFC_TIM_MASK) << SFC_TIM_OFFSET) | (SFC_CMD_MRR << SFC_CMD_OFFSET))
#define MRR(ma) MRR_TIM(ma, SFC_TIM_TRESERVE1)
#define MPC(op,tim) ((((op) & SFC_MPC_OP_MASK) << SFC_MPC_OP_OFFSET) | (((tim) & SFC_TIM_MASK) << SFC_TIM_OFFSET) | (SFC_CMD_MPC << SFC_CMD_OFFSET))
#define CAS(r) ((((r) & SFC_CAS_R_MASK) << SFC_CAS_R_OFFSET) | (SFC_TIM_TLAST << SFC_TIM_OFFSET) | (SFC_CMD_CAS << SFC_CMD_OFFSET))
#define CAS_TIM(r,tim) ((((r) & SFC_CAS_R_MASK) << SFC_CAS_R_OFFSET) | (tim << SFC_TIM_OFFSET) | (SFC_CMD_CAS << SFC_CMD_OFFSET))
#define PD_TIM(tim) ((((tim) & SFC_TIM_MASK) << SFC_TIM_OFFSET) | (SFC_CMD_PD << SFC_CMD_OFFSET))
#define XPD_TIM(tim) ((((tim) & SFC_TIM_MASK) << SFC_TIM_OFFSET) | (SFC_CMD_XPD << SFC_CMD_OFFSET))
#define SREF(a) ((((a) & SFC_SR_A_MASK) << SFC_SR_A_OFFSET) | (SFC_TIM_TSR << SFC_TIM_OFFSET) | (SFC_CMD_SREF << SFC_CMD_OFFSET))
#define XSREF(a) ((((a) & SFC_SR_A_MASK) << SFC_SR_A_OFFSET) | (SFC_TIM_TSRE << SFC_TIM_OFFSET) | (SFC_CMD_XSREF << SFC_CMD_OFFSET))
#define AREF(bank,a) ((((bank) & SFC_REF_BANK_MASK) << SFC_REF_BANK_OFFSET) | (((a) & SFC_REF_A_MASK) << SFC_REF_A_OFFSET) | \
  (SFC_TIM_TRFC << SFC_TIM_OFFSET) | (SFC_CMD_AREF << SFC_CMD_OFFSET))
#define MPC_NOP_LPDDR4 MPC(DRAM_MPC_NOP_OP_LPDDR4, SFC_TIM_TMRD)
#define MPC_READ_LPDDR4 MPC(DRAM_MPC_RDFIFO_OP_LPDDR4, SFC_TIM_TRESERVE1)
#define MPC_WRITE_LPDDR4 MPC(DRAM_MPC_WRFIFO_OP_LPDDR4, SFC_TIM_TRESERVE1)
#define MPC_START_OSC_LPDDR4 MPC(DRAM_MPC_START_DQS_OSC_OP_LPDDR4, SFC_TIM_TMRD)
#define MPC_ZQCAL_START_LPDDR4 MPC(DRAM_MPC_ZQCALSTART_OP_LPDDR4, SFC_TIM_TRESERVE)
#define MPC_ZQCAL_LATCH_LPDDR4 MPC(DRAM_MPC_ZQCALLATCH_OP_LPDDR4, SFC_TIM_TZQCS)
#define MPC_START_OSC_LPDDR5 MPC(DRAM_MPC_START_WCK2DQI_OSC_OP_LPDDR5, SFC_TIM_TMRD)
#define MPC_ZQCAL_START_TIM_LPDDR5(tim) MPC(DRAM_MPC_ZQCALSTART_OP_LPDDR5, tim)
#define MPC_ZQCAL_LATCH_LPDDR5 MPC(DRAM_MPC_ZQCALLATCH_OP_LPDDR5, SFC_TIM_TZQCS)
#define CAS_FS_LPDDR5 CAS(SFC_CAS_R_FS)
#define CAS_OFF_LPDDR5 CAS(SFC_CAS_R_OFF)
#define XSREF_LPDDR4 XSREF(SFC_SR_SRX_A_LPDDR4)
#define XSREF_LPDDR5 XSREF(SFC_SR_SRX_A_LPDDR5)
#define XSREF_DSM (XPD_TIM(SFC_TIM_TRESERVE) | (1U << SFC_SR_A_OFFSET))
#define AREF_ALLBANK AREF(SFC_REF_BANK_ALLBANK, SFC_REF_A_ALLBANK)
#define DRAM_MPC_NOP_OP_LPDDR4 0U
#define DRAM_MPC_RDFIFO_OP_LPDDR4 0x41U
#define DRAM_MPC_WRFIFO_OP_LPDDR4 0x47U
#define DRAM_MPC_START_DQS_OSC_OP_LPDDR4 0x4BU
#define DRAM_MPC_ZQCALSTART_OP_LPDDR4 0x4FU
#define DRAM_MPC_ZQCALLATCH_OP_LPDDR4 0x51U
#define DRAM_MPC_START_WCK2DQI_OSC_OP_LPDDR5 0x81U
#define DRAM_MPC_ZQCALSTART_OP_LPDDR5 0x85U
#define DRAM_MPC_ZQCALLATCH_OP_LPDDR5 0x86U
#define DRAM_MR3_OP_PDDS_LPDDR4_START 3
#define DRAM_MR3_OP_PDDS_LPDDR4_END 5
#define DRAM_MR3_OP_PUCAL_LPDDR4_OFFSET 0
#define DRAM_MR3_OP_DBIRD_LPDDR4_OFFSET 6
#define DRAM_MR3_OP_DBIWR_LPDDR4_OFFSET 7
#define DRAM_MR3_OP_PUCAL_0P5VDDQ_LPDDR4 0x1U
#define DRAM_MR3_OP_DBIRD_EN_LPDDR4 0x1U
#define DRAM_MR3_OP_DBIRD_DIS_LPDDR4 0x0U
#define DRAM_MR3_OP_DBIWR_EN_LPDDR4 0x1U
#define DRAM_MR3_OP_DBIWR_DIS_LPDDR4 0x0U
#define DRAM_MR4_OP_SRABORT_LPDDR4_OFFSET 3
#define DRAM_MR4_OP_PPRE_LPDDR4_OFFSET 4
#define DRAM_MR4_OP_THERMALOFFSET_LPDDR4_START 5
#define DRAM_MR4_OP_THERMALOFFSET_LPDDR4_END 6
#define DRAM_MR4_OP_SRABORT_DIS_LPDDR4 0x0U
#define DRAM_MR4_OP_SRABORT_EN_LPDDR4 0x1U
#define DRAM_MR4_OP_PPRE_EXIT_LPDDR4 0x0U
#define DRAM_MR4_OP_PPRE_ENTER_LPDDR4 0x1U
#define DRAM_MR4_OP_THERMALOFFSET_NON_LPDDR4 0x0U
#define DRAM_MR4_OP_THERMALOFFSET_FIVEDEGREE_LPDDR4 0x1U
#define DRAM_MR4_OP_THERMALOFFSET_TENDEGREE_LPDDR4 0x2U
#define DRAM_MR11_OP_DQODT_LPDDR4_START 0
#define DRAM_MR11_OP_DQODT_LPDDR4_END 2
#define DRAM_MR11_OP_CAODT_LPDDR4_START 4
#define DRAM_MR11_OP_CAODT_LPDDR4_END 6
#define DRAM_MR12_OP_VREFCA_LPDDR4_START 0
#define DRAM_MR12_OP_VREFCA_LPDDR4_END 5
#define DRAM_MR12_OP_VRCA_LPDDR4_OFFSET 6
#define DRAM_MR12_OP_CBTMODE_LPDDR4_OFFSET 7
#define DRAM_MR12_OP_CBTMODE_MODE1_LPDDR4 0x0U
#define DRAM_MR12_OP_CBTMODE_MODE2_LPDDR4 0x1U
#define DRAM_MR13_OP_VRCG_LPDDR4_OFFSET 3
#define DRAM_MR13_OP_RRO_LPDDR4_OFFSET 4
#define DRAM_MR13_OP_FSPWR_LPDDR4_OFFSET 6
#define DRAM_MR13_OP_FSPOP_LPDDR4_OFFSET 7
#define DRAM_MR13_OP_VRCG_EN_LPDDR4 0x1U
#define DRAM_MR13_OP_VRCG_DIS_LPDDR4 0x0U
#define DRAM_MR13_OP_RRO_EN_LPDDR4 0x1U
#define DRAM_MR13_OP_RRO_DIS_LPDDR4 0x0U
#define DRAM_MR14_OP_VREFDQ_LPDDR4_START 0
#define DRAM_MR14_OP_VREFDQ_LPDDR4_END 5
#define DRAM_MR14_OP_VRDQ_LPDDR4_OFFSET 6
#define DRAM_MR15_OP_LOWERBYTE_INVERT_LPDDR4_START 0
#define DRAM_MR15_OP_LOWERBYTE_INVERT_LPDDR4_END 7
#define DRAM_MR15_OP_LOWERBYTE_INVERT_DEFAULT_LPDDR4 0x55U
#define DRAM_MR15_OP_LOWERBYTE_INVERT_NOCROSSTALK_LPDDR4 0x0U
#define DRAM_MR20_OP_UPPERBYTE_INVERT_LPDDR4_START 0
#define DRAM_MR20_OP_UPPERBYTE_INVERT_LPDDR4_END 7
#define DRAM_MR20_OP_UPPERBYTE_INVERT_DEFAULT_LPDDR4 0x55U
#define DRAM_MR20_OP_UPPERBYTE_INVERT_NOCROSSTALK_LPDDR4 0x0U
#define DRAM_MR21_OP_SINGLEENDEDMODE_LPDDR4_OFFSET 5
#define DRAM_MR22_OP_SOCODT_LPDDR4_START 0
#define DRAM_MR22_OP_SOCODT_LPDDR4_END 2
#define DRAM_MR22_OP_ODTECK_LPDDR4_OFFSET 3
#define DRAM_MR22_OP_ODTDCS_LPDDR4_OFFSET 4
#define DRAM_MR22_OP_ODTDCA_LPDDR4_OFFSET 5
#define DRAM_MR22_OP_X8ODTD_LOWERBYTE_LPDDR4_OFFSET 6
#define DRAM_MR22_OP_X8ODTD_UPPERBYTE_LPDDR4_OFFSET 7
#define DRAM_MR22_OP_ODTECK_EN_LPDDR4 0U
#define DRAM_MR22_OP_ODTECK_DIS_LPDDR4 1U
#define DRAM_MR22_OP_ODTDCS_EN_LPDDR4 0U
#define DRAM_MR22_OP_ODTDCS_DIS_LPDDR4 1U
#define DRAM_MR22_OP_ODTDCA_EN_LPDDR4 0U
#define DRAM_MR22_OP_ODTDCA_DIS_LPDDR4 1U
#define DRAM_MR22_OP_X8ODTD_LOWERBYTE_EN_LPDDR4 0U
#define DRAM_MR22_OP_X8ODTD_LOWERBYTE_DIS_LPDDR4 1U
#define DRAM_MR22_OP_X8ODTD_UPPERBYTE_EN_LPDDR4 0U
#define DRAM_MR22_OP_X8ODTD_UPPERBYTE_DIS_LPDDR4 1U
#define DRAM_MR31_OP_BYTEMODEVREFSELECTION_LPDDR4_START 6
#define DRAM_MR31_OP_BYTEMODEVREFSELECTION_LPDDR4_END 7
#define DRAM_MR31_OP_BYTEMODEVREFSELECTION_ALLBYTE_LPDDR4 0x0U
#define DRAM_MR31_OP_BYTEMODEVREFSELECTION_LOWERBYTE_LPDDR4 0x2U
#define DRAM_MR31_OP_BYTEMODEVREFSELECTION_UPPERBYTE_LPDDR4 0x1U
#define DRAM_MR51_OP_SEQERD_LPDDR4_OFFSET 1
#define DRAM_MR51_OP_SEQEWR_LPDDR4_OFFSET 2
#define DRAM_MR51_OP_SECE_LPDDR4_OFFSET 3
#define DRAM_MR51_OP_SEQERD_SE_LPDDR4 0x1U
#define DRAM_MR51_OP_SEQERD_DI_LPDDR4 0x0U
#define DRAM_MR51_OP_SEQEWR_SE_LPDDR4 0x1U
#define DRAM_MR51_OP_SEQEWR_DI_LPDDR4 0x0U
#define DRAM_MR51_OP_SECE_SE_LPDDR4 0x1U
#define DRAM_MR51_OP_SECE_DI_LPDDR4 0x0U
#define DRAM_MR1_OP_CKMODE_LPDDR5_OFFSET 3
#define DRAM_MR1_OP_CKMODE_SE_LPDDR5 0x1U
#define DRAM_MR1_OP_CKMODE_DI_LPDDR5 0x0U
#define DRAM_MR3_OP_PDDS_LPDDR5_START 0
#define DRAM_MR3_OP_PDDS_LPDDR5_END 2
#define DRAM_MR3_OP_DBIRD_LPDDR5_OFFSET 6
#define DRAM_MR3_OP_DBIWR_LPDDR5_OFFSET 7
#define DRAM_MR3_OP_DBIRD_EN_LPDDR5 0x1U
#define DRAM_MR3_OP_DBIRD_DIS_LPDDR5 0x0U
#define DRAM_MR3_OP_DBIWR_EN_LPDDR5 0x1U
#define DRAM_MR3_OP_DBIWR_DIS_LPDDR5 0x0U
#define DRAM_MR4_OP_ZQMASTER_LPDDR5_OFFSET 6
#define DRAM_MR4_OP_ZQMASTER_YES_LPDDR5 0x1U
#define DRAM_MR10_OP_RPSTMODE_LPDDR5_OFFSET 0
#define DRAM_MR10_OP_WCKPST_LPDDR5_START 2
#define DRAM_MR10_OP_WCKPST_LPDDR5_END 3
#define DRAM_MR10_OP_RDQSPRE_LPDDR5_START 4
#define DRAM_MR10_OP_RDQSPRE_LPDDR5_END 5
#define DRAM_MR10_OP_RDQSPST_LPDDR5_START 6
#define DRAM_MR10_OP_RDQSPST_LPDDR5_END 7
#define DRAM_MR11_OP_DQODT_LPDDR5_START 0
#define DRAM_MR11_OP_DQODT_LPDDR5_END 2
#define DRAM_MR11_OP_NTODTEN_LPDDR5_OFFSET 3
#define DRAM_MR11_OP_CAODT_LPDDR5_START 4
#define DRAM_MR11_OP_CAODT_LPDDR5_END 6
#define DRAM_MR11_OP_DQODT_MAX_LPDDR5 0x6U
#define DRAM_MR11_OP_DQODT_DIS_LPDDR5 0x0U
#define DRAM_MR11_OP_CAODT_MAX_LPDDR5 0x6U
#define DRAM_MR11_OP_CAODT_DIS_LPDDR5 0x0U
#define DRAM_MR12_OP_VREFCA_LPDDR5_START 0
#define DRAM_MR12_OP_VREFCA_LPDDR5_END 6
#define DRAM_MR12_OP_VBS_LPDDR5_OFFSET 7
#define DRAM_MR12_OP_VBS_LOWERBYTE_LPDDR5 0x0U
#define DRAM_MR12_OP_VBS_UPPERBYTE_LPDDR5 0x1U
#define DRAM_MR13_OP_DMI_MODE_LPDDR5_OFFSET 4
#define DRAM_MR13_OP_CBTMODE_LPDDR5_OFFSET 6
#define DRAM_MR13_OP_DMI_MODE1_LPDDR5 0x0U
#define DRAM_MR13_OP_DMI_MODE2_LPDDR5 0x1U
#define DRAM_MR14_OP_VREFDQ_LPDDR5_START 0
#define DRAM_MR14_OP_VREFDQ_LPDDR5_END 6
#define DRAM_MR14_OP_VDLC_LPDDR5_OFFSET 7
#define DRAM_MR14_OP_VDLC_UPPERBYTE_MR15_LPDDR5 0x0U
#define DRAM_MR14_OP_VDLC_UPPERBYTE_MR14_LPDDR5 0x1U
#define DRAM_MR15_OP_VREFDQ_LPDDR5_START 0
#define DRAM_MR15_OP_VREFDQ_LPDDR5_END 6
#define DRAM_MR16_OP_FSPWR_LPDDR5_START 0
#define DRAM_MR16_OP_FSPWR_LPDDR5_END 1
#define DRAM_MR16_OP_FSPOP_LPDDR5_START 2
#define DRAM_MR16_OP_FSPOP_LPDDR5_END 3
#define DRAM_MR16_OP_CBT_LPDDR5_START 4
#define DRAM_MR16_OP_CBT_LPDDR5_END 5
#define DRAM_MR16_OP_VRCG_LPDDR5_OFFSET 6
#define DRAM_MR16_OP_CBTPHASE_LPDDR5_OFFSET 7
#define DRAM_MR16_OP_FSPOP_LPDDR5_MASK 0x1U
#define DRAM_MR16_OP_CBT_EN_LPDDR5 0x2U
#define DRAM_MR16_OP_CBT_DIS_LPDDR5 0x0U
#define DRAM_MR16_OP_VRCG_EN_LPDDR5 0x1U
#define DRAM_MR16_OP_VRCG_DIS_LPDDR5 0x0U
#define DRAM_MR16_OP_CBTPHASE_CKRISE_LPDDR5 0x0U
#define DRAM_MR16_OP_CBTPHASE_CKFALL_LPDDR5 0x1U
#define DRAM_MR17_OP_ODTDCK_LPDDR5_OFFSET 3
#define DRAM_MR17_OP_ODTDCA_LPDDR5_OFFSET 5
#define DRAM_MR17_OP_SOCODT_LPDDR5_START 0
#define DRAM_MR17_OP_SOCODT_LPDDR5_END 2
#define DRAM_MR18_OP_WCKODT_LPDDR5_START 0
#define DRAM_MR18_OP_WCKODT_LPDDR5_END 2
#define DRAM_MR18_OP_WCKFM_LPDDR5_OFFSET 3
#define DRAM_MR18_OP_WCKON_LPDDR5_OFFSET 4
#define DRAM_MR18_OP_CKR_LPDDR5_OFFSET 7
#define DRAM_MR18_OP_WCKODT_MAX_LPDDR5 0x6U
#define DRAM_MR18_OP_WCKODT_DIS_LPDDR5 0x0U
#define DRAM_MR18_OP_CKR_RATIO_4T1_LPDDR5 0x0U
#define DRAM_MR18_OP_CKR_RATIO_2T1_LPDDR5 0x1U
#define DRAM_MR18_OP_WCKON_EN_LPDDR5 0x1U
#define DRAM_MR18_OP_WCKON_DIS_LPDDR5 0x0U
#define DRAM_MR19_OP_DVFSC_LPDDR5_START 0
#define DRAM_MR19_OP_DVFSC_LPDDR5_END 1
#define DRAM_MR19_OP_DVFSQ_LPDDR5_START 2
#define DRAM_MR19_OP_DVFSQ_LPDDR5_END 3
#define DRAM_MR19_OP_WCK2DQOSCFM_LPDDR5_OFFSET 4
#define DRAM_MR19_OP_DVFSC_HIGHSPEED_LPDDR5 0x0U
#define DRAM_MR19_OP_DVFSC_LOWSPEED_LPDDR5 0x1U
#define DRAM_MR19_OP_DVFSQ_VDDQ0P5_LPDDR5 0x0U
#define DRAM_MR19_OP_DVFSQ_VDDQ0P3_LPDDR5 0x1U
#define DRAM_MR19_OP_WCK2DQOSCFM_LOWFREQ_LPDDR5 0x0U
#define DRAM_MR19_OP_WCK2DQOSCFM_HIGHFREQ_LPDDR5 0x1U
#define DRAM_MR20_OP_RDQS_LPDDR5_START 0
#define DRAM_MR20_OP_RDQS_LPDDR5_END 1
#define DRAM_MR20_OP_WCKMODE_LPDDR5_START 2
#define DRAM_MR20_OP_WCKMODE_LPDDR5_END 3
#define DRAM_MR20_OP_RDQS_SE_LPDDR5 0x1U
#define DRAM_MR20_OP_RDQS_DI_LPDDR5 0x2U
#define DRAM_MR20_OP_WCKMODE_SE_LPDDR5 0x1U
#define DRAM_MR20_OP_WCKMODE_DI_LPDDR5 0x0U
#define DRAM_MR21_OP_WDCFS_LPDDR5_OFFSET 0
#define DRAM_MR21_OP_RDCFS_LPDDR5_OFFSET 1
#define DRAM_MR21_OP_WXFS_LPDDR5_OFFSET 2
#define DRAM_MR21_OP_ODTDCSFS_LPDDR5_OFFSET 3
#define DRAM_MR21_OP_WDCFE_LPDDR5_OFFSET 4
#define DRAM_MR21_OP_RDCFE_LPDDR5_OFFSET 5
#define DRAM_MR21_OP_WXFE_LPDDR5_OFFSET 6
#define DRAM_MR21_OP_WXS_LPDDR5_OFFSET 7
#define DRAM_MR21_OP_WDCFS_NO_LPDDR5 0x0U
#define DRAM_MR21_OP_WDCFS_YES_LPDDR5 0x1U
#define DRAM_MR21_OP_RDCFS_NO_LPDDR5 0x0U
#define DRAM_MR21_OP_RDCFS_YES_LPDDR5 0x1U
#define DRAM_MR21_OP_WXFS_NO_LPDDR5 0x0U
#define DRAM_MR21_OP_WXFS_YES_LPDDR5 0x1U
#define DRAM_MR21_OP_ODTDCSFS_NO_LPDDR5 0x0U
#define DRAM_MR21_OP_ODTDCSFS_YES_LPDDR5 0x1U
#define DRAM_MR21_OP_WDCFE_DIS_LPDDR5 0x0U
#define DRAM_MR21_OP_WDCFE_EN_LPDDR5 0x1U
#define DRAM_MR21_OP_RDCFE_DIS_LPDDR5 0x0U
#define DRAM_MR21_OP_RDCFE_EN_LPDDR5 0x1U
#define DRAM_MR21_OP_WXFE_DIS_LPDDR5 0x0U
#define DRAM_MR21_OP_WXFE_EN_LPDDR5 0x1U
#define DRAM_MR21_OP_WXS_0_LPDDR5 0x0U
#define DRAM_MR21_OP_WXS_ALL_LPDDR5 0x1U
#define DRAM_MR26_OP_DCM_START_LPDDR5_OFFSET 0
#define DRAM_MR26_OP_DCM_FLIP_LPDDR5_OFFSET 1
#define DRAM_MR26_OP_DCML0_LPDDR5_OFFSET 2
#define DRAM_MR26_OP_DCML1_LPDDR5_OFFSET 3
#define DRAM_MR26_OP_DCMU0_LPDDR5_OFFSET 4
#define DRAM_MR26_OP_DCMU1_LPDDR5_OFFSET 5
#define DRAM_MR26_OP_DCM_START_LPDDR5 0x1U
#define DRAM_MR26_OP_DCM_STOP_LPDDR5 0x0U
#define DRAM_MR26_OP_DCM_FLIP_EN_LPDDR5 0x1U
#define DRAM_MR26_OP_DCM_FLIP_DIS_LPDDR5 0x0U
#define DRAM_MR28_OP_ZQMODE_LPDDR5_OFFSET 5
#define DRAM_MR30_OP_DCAL_LPDDR5_START 0
#define DRAM_MR30_OP_DCAL_LPDDR5_END 3
#define DRAM_MR30_OP_DCAU_LPDDR5_START 4
#define DRAM_MR30_OP_DCAU_LPDDR5_END 7
#define DRAM_MR31_OP_LOWERBYTE_INVERT_LPDDR5_START 0
#define DRAM_MR31_OP_LOWERBYTE_INVERT_LPDDR5_END 7
#define DRAM_MR31_OP_LOWERBYTE_INVERT_DEFAULT_LPDDR5 0x55U
#define DRAM_MR31_OP_LOWERBYTE_INVERT_NOCROSSTALK_LPDDR5 0x0U
#define DRAM_MR32_OP_UPPERBYTE_INVERT_LPDDR5_START 0
#define DRAM_MR32_OP_UPPERBYTE_INVERT_LPDDR5_END 7
#define DRAM_MR32_OP_UPPERBYTE_INVERT_DEFAULT_LPDDR5 0x55U
#define DRAM_MR32_OP_UPPERBYTE_INVERT_NOCROSSTALK_LPDDR5 0x0U
#define DRAM_MR37_OP_WCK2DQI_RUN_TIME_LPDDR5 0x40U
#define DRAM_MR41_OP_NTDQODT_LPDDR5_START 5
#define DRAM_MR41_OP_NTDQODT_LPDDR5_END 7
#define DRAM_MR41_OP_NTDQODT_DIS_LPDDR5 0x0U
#define DRAM_MR_OP_MASK SFC_MRR_OP_MASK
#define DRAM_MR_ALL_BITS 0xFFU
#define DXCTRL_TRX0_DEFAULT 0x00170C13U
#define ACCTRL_TRX0_DEFAULT 0x04000221U
#define PHYINITCTRL_DEFAULT 0x0000000AU
#define AC_PLL_CTRL_AB_DEFAULT 0x411E411EU
#define PLLCTRL_DEFAULT 0xF30A0007U
#define PHYCLKGATED_DEFAULT 0x00002000U
#define AC_CTRL_1_DEFAULT 0x0000FF30U
#define PHYINITCTRL_DEFAULT 0x0000000AU
#endif
