#ifndef __MNTN_SUBTYPE_EXCEPTION_HISEE_H__
#define __MNTN_SUBTYPE_EXCEPTION_HISEE_H__ 
enum hisee_module_id {
 MODID_HISEE_START = (unsigned int)HISI_BB_MOD_HISEE_START,
 MODID_HISEE_EXC_SENSOR_CTRL = MODID_HISEE_START,
 MODID_HISEE_EXC_SIC,
 MODID_HISEE_EXC_MED_ROM,
 MODID_HISEE_EXC_MED_RAM,
 MODID_HISEE_EXC_OTPC,
 MODID_HISEE_EXC_HARD,
 MODID_HISEE_EXC_IPC_MAILBOX,
 MODID_HISEE_EXC_MPU,
 MODID_HISEE_EXC_BUS,
 MODID_HISEE_EXC_TIMER,
 MODID_HISEE_EXC_SEC_EXTERN,
 MODID_HISEE_EXC_WDG,
 MODID_HISEE_EXC_SYSALARM,
 MODID_HISEE_EXC_NV_COUNTER,
 MODID_HISEE_EXC_SECFLASH,
 MODID_HISEE_EXC_COS,
 MODID_HISEE_EXC_BB,
 MODID_HISEE_EXC_MNTN_COS,
 MODID_HISEE_EXC_MNTN_COS_RESET,
 MODID_HISEE_EXC_LIBC,
 MODID_HISEE_EXC_NVM,
 MODID_HISEE_EXC_SECENG_TRNG,
 MODID_HISEE_EXC_SECENG_TRIM,
 MODID_HISEE_EXC_SECENG_SCE,
 MODID_HISEE_EXC_SECENG_RSA,
 MODID_HISEE_EXC_SECENG_SM2,
 MODID_HISEE_EXC_SECENG_KM,
 MODID_HISEE_EXC_SECENG_SCRAMBLING,
 MODID_HISEE_EXC_DCS,
 MODID_HISEE_EXC_RAM,
 MODID_HISEE_EXC_SECBOOT,
 MODID_HISEE_EXC_SECFLASH_FACTORY,
 MODID_HISEE_EXC_SECFLASH_DATALINK,
 MODID_HISEE_EXC_SECFLASH_SW,
 MODID_HISEE_EXC_SECFLASH_SCP03,
 MODID_HISEE_EXC_SECFLASH_SA,
 MODID_HISEE_EXC_BOTTOM,
 MODID_HISEE_EXC_UNKNOWN = MODID_HISEE_START + 0xFFFF,
 MODID_HISEE_EXC_ROM = MODID_HISEE_START + 0x10000,
 MODID_HISEE_EXC_ALARM0 = MODID_HISEE_START + 0x20000,
 MODID_HISEE_EXC_ALARM1,
 MODID_HISEE_EXC_AS2AP_IRQ,
 MODID_HISEE_EXC_DS2AP_IRQ,
 MODID_HISEE_EXC_SENC2AP_IRQ,
 MODID_HISEE_EXC_SENC2AP_IRQ0,
 MODID_HISEE_EXC_SENC2AP_IRQ1,
 MODID_HISEE_EXC_LOCKUP,
 MODID_HISEE_EXC_EH2H_SLV,
 MODID_HISEE_EXC_TSENSOR1,
 MODID_HISEE_EXC_RST,
 MODID_SIMULATE_EXC_RPMB_KO = MODID_HISEE_START + 0x30000,
 MODID_HISEE_EXC_END = HISI_BB_MOD_HISEE_END
};
#define HISEE_EXCEPTIONE_INFO(modid,subtype,desc) { \
 .e_modid = (u32)(modid), \
 .e_modid_end = (u32)(modid), \
 .e_process_priority = RDR_ERR, \
 .e_reboot_priority = RDR_REBOOT_NO, \
 .e_notify_core_mask = RDR_HISEE, \
 .e_reset_core_mask = RDR_HISEE, \
 .e_from_core = RDR_HISEE, \
 .e_reentrant = (u32)RDR_REENTRANT_DISALLOW, \
 .e_exce_type = HISEE_S_EXCEPTION, \
 .e_exce_subtype = (subtype), \
 .e_upload_flag = (u32)RDR_UPLOAD_YES, \
 .e_save_log_flags = RDR_SAVE_BL31_LOG, \
 .e_from_module = (desc), \
 .e_desc = "HISEE", \
}
#define HISEE_EXCEPTIONE_INFO_MAP { \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SENSOR_CTRL, \
         EXC_SENSOR_CTRL, "HISEE SENSOR"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SIC, \
         EXC_SIC, "HISEE SIC"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_MED_ROM, \
         EXC_MED_ROM, "HISEE ROM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_MED_RAM, \
         EXC_MED_RAM, "HISEE RAM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_OTPC, \
         EXC_OTPC, "HISEE OTPC"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_HARD, \
         EXC_HARD, "HISEE HARD"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_IPC_MAILBOX, \
         EXC_IPC_MAILBOX, "HISEE IPC MAILBOX"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_MPU, \
         EXC_MPU, "HISEE MPU"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_BUS, \
         EXC_BUS, "HISEE RPMB"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_TIMER, \
         EXC_TIMER, "HISEE TIMER"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SEC_EXTERN, \
         EXC_SEC_EXTERN, "HISEE SEC EXTERN"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_WDG, \
         EXC_WDG, "HISEE WDG"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SYSALARM, \
         EXC_SYSALARM, "HISEE SYSALARM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_NV_COUNTER, \
         EXC_NV_COUNTER, "HISEE NV_COUNTER"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_COS, \
         EXC_COS, "HISEE COS"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_BB, \
         EXC_BB, "HISEE BB"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_MNTN_COS, \
         EXC_MNTN_COS, "HISEE MNTN_COS"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_MNTN_COS_RESET, \
         EXC_MNTN_COS_RESET, "HISEE NORMAL RESET"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_LIBC, \
         EXC_LIBC, "HISEE LIBC"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_NVM, \
         EXC_NVM, "HISEE NVM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_TRNG, \
         EXC_SECENG_TRNG, "HISEE SECENG TRNG"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_TRIM, \
         EXC_SECENG_TRIM, "HISEE SECENG TRIM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_SCE, \
         EXC_SECENG_SCE, "HISEE SECENG SCE"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_RSA, \
         EXC_SECENG_RSA, "HISEE SECENG RSA"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_SM2, \
         EXC_SECENG_SM2, "HISEE SECENG SM2"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_KM, \
         EXC_SECENG_KM, "HISEE SECENG KM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECENG_SCRAMBLING, \
         EXC_SECENG_SCRAMBLING, "HISEE SECENG SCRAM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_DCS, \
         EXC_DCS, "HISEE DCS"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_RAM, \
         EXC_RAM, "HISEE RAM"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECBOOT, \
         EXC_SECBOOT, "HISEE SECBOOT"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH, \
         EXC_SECFLASH, "HISEE SECFLASH"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH_FACTORY, \
         EXC_SECFLASH_FACTORY, "HISEE SECFLASH FAC"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH_DATALINK, \
         EXC_SECFLASH_DATALINK, "HISEE SECFLASH DL"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH_SW, \
         EXC_SECFLASH_SW, "HISEE SECFLASH SW"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH_SCP03, \
         EXC_SECFLASH_SCP03, "HISEE SECFLASH SCP03"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SECFLASH_SA, \
         EXC_SECFLASH_SA, "HISEE SECFLASH SA"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_ROM, \
         EXC_MSPC_ROM, "MSPC ROM"), \
 HISEE_EXCEPTIONE_INFO(MODID_SIMULATE_EXC_RPMB_KO, \
         EXC_RPMB_KO, "FAIL TO RESET RPMB"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_ALARM0, \
         EXC_ALARM0, "HISEE ALARM0"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_ALARM1, \
         EXC_ALARM1, "HISEE ALARM1"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_AS2AP_IRQ, \
         EXC_AS2AP_IRQ, "HISEE AS2AP IRQ"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_DS2AP_IRQ, \
         EXC_DS2AP_IRQ, "HISEE DS2AP IRQ"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SENC2AP_IRQ, \
         EXC_SENC2AP_IRQ, "HISEE SENC2AP IRQ"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SENC2AP_IRQ0, \
         EXC_SENC2AP_IRQ0, "HISEE SENC2AP IRQ0"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_SENC2AP_IRQ1, \
         EXC_SENC2AP_IRQ1, "HISEE SENC2AP IRQ1"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_LOCKUP, \
         EXC_LOCKUP, "HISEE LOCKUP"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_EH2H_SLV, \
         EXC_EH2H_SLV, "HISEE EH2H SLV"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_TSENSOR1, \
         EXC_TSENSOR1, "HISEE TSENSOR1"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_RST, \
         EXC_RST, "HISEE RST"), \
 HISEE_EXCEPTIONE_INFO(MODID_HISEE_EXC_UNKNOWN, \
         EXC_UNKNOWN, "HISEE UNKNOWN"), \
}
#endif
