#ifndef __SOC_EFUSE_INTERFACE_H__
#define __SOC_EFUSE_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#define EFUSE_ATTR_READABLE (0x00000001UL)
#define EFUSE_ATTR_READ_DEVICE (0x00000002UL)
#define EFUSE_ATTR_READ_SRAM (0x00000004UL)
#define EFUSE_ATTR_READ_ZERO (0x00000008UL)
#define EFUSE_ATTR_WRITEABLE (0x00000100UL)
#define EFUSE_ATTR_WRITE_NOT_UPDATE (0x00000200UL)
#define EFUSE_ATTR_WRITE_CHECK (0x00000400UL)
typedef struct {
 unsigned int start_bit;
 unsigned int bit_cnt;
 unsigned int id;
 unsigned int attr;
} efuse_attr_t;
#if defined(CONFIG_EFUSE_IN_XLOADER)
enum {
 EFUSE_GPU_VDDPC = 0,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HPM_TRIM,
 EFUSE_MEMORYREPAIR_BYPN,
 EFUSE_ONLINE_REPAIR,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_MEMORY_REPAIR1,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_REMOTE_TSENSOR_DIG = 10,
 EFUSE_TENSOR_TRIM,
 EFUSE_PARTIAL_PASSP1,
 EFUSE_PARTIAL_PASSP2,
 EFUSE_SECDBG_CTRL,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE,
 EFUSE_MBIST_DIS,
 EFUSE_AOMEMORY_REPAIR,
 EFUSE_PERI_MEMORY_REPAIR,
};
#elif defined(CONFIG_EFUSE_IN_BL2)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_TENSOR_TRIM,
 EFUSE_HPM_TRIM,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER = 20,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE,
 EFUSE_FLASH_COUNT,
 EFUSE_INSE_FLAG,
 EFUSE_ROOT_KEY,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_SHUTDOWN_SWINGCARD,
 EFUSE_AUTH_KEY = 30,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_DFTRD_DISABLE,
 EFUSE_SECDBG_CTRL,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN = 40,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE,
 EFUSE_GPU_VDDPC,
 EFUSE_MEMORYREPAIR_BYPN = 50,
 EFUSE_ONLINE_REPAIR,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_HISEE_EFUSE1,
 EFUSE_HISEE_EFUSE2,
 EFUSE_HISEE_EFUSE3,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_DIEID_LOT = 60,
 EFUSE_DIEID_WAFER,
 EFUSE_DIEID_X,
 EFUSE_DIEID_Y,
 EFUSE_BIG_CLUSTER_IDDQ,
 EFUSE_LITTLE_CLUSTER_IDDQ,
 EFUSE_GPU_IDDQ,
 EFUSE_SYS_IDDQ,
 EFUSE_PERI_IDDQ,
 EFUSE_TSENSOR_REF,
 EFUSE_ATE_FLAG = 70,
 EFUSE_HEALTH_LEVEL,
 EFUSE_MODEMAVS_PASENSOR,
 EFUSE_MODEMAVS,
 EFUSE_SVFD_VMIN,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_REMOTE_TSENSOR_DIG,
 EFUSE_UFSBOOTROMMODE_SEL,
 EFUSE_PARTIAL_PASSP1,
 EFUSE_PARTIAL_PASSP2,
 EFUSE_PASENSOR_A73 = 80,
 EFUSE_PASENSOR_A53GPU,
#ifdef CONFIG_DEBUG_HISI_EFUSE
 EFUSE_DEBUG_ID,
#endif
};
#elif defined(CONFIG_EFUSE_IN_BL31)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_TENSOR_TRIM,
 EFUSE_HPM_TRIM,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER = 20,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE,
 EFUSE_FLASH_COUNT,
 EFUSE_INSE_FLAG,
 EFUSE_ROOT_KEY,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_SHUTDOWN_SWINGCARD,
 EFUSE_AUTH_KEY = 30,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_DFTRD_DISABLE,
 EFUSE_SECDBG_CTRL,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN = 40,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE,
 EFUSE_GPU_VDDPC,
 EFUSE_MEMORYREPAIR_BYPN = 50,
 EFUSE_ONLINE_REPAIR,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_HISEE_EFUSE1,
 EFUSE_HISEE_EFUSE2,
 EFUSE_HISEE_EFUSE3,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_DIEID_LOT = 60,
 EFUSE_DIEID_WAFER,
 EFUSE_DIEID_X,
 EFUSE_DIEID_Y,
 EFUSE_BIG_CLUSTER_IDDQ,
 EFUSE_LITTLE_CLUSTER_IDDQ,
 EFUSE_GPU_IDDQ,
 EFUSE_SYS_IDDQ,
 EFUSE_PERI_IDDQ,
 EFUSE_TSENSOR_REF,
 EFUSE_ATE_FLAG = 70,
 EFUSE_HEALTH_LEVEL,
 EFUSE_MODEMAVS_PASENSOR,
 EFUSE_MODEMAVS,
 EFUSE_SVFD_VMIN,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_REMOTE_TSENSOR_DIG,
 EFUSE_PARTIAL_PASSP1,
 EFUSE_PARTIAL_PASSP2,
 EFUSE_PASENSOR_A73,
 EFUSE_PASENSOR_A53GPU = 80,
 EFUSE_CC712_MBIST_DIS,
};
#elif defined(CONFIG_EFUSE_IN_HIBENCH)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_TENSOR_TRIM,
 EFUSE_HPM_TRIM,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER = 20,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE,
 EFUSE_FLASH_COUNT,
 EFUSE_INSE_FLAG,
 EFUSE_ROOT_KEY,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_SHUTDOWN_SWINGCARD,
 EFUSE_AUTH_KEY = 30,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_DFTRD_DISABLE,
 EFUSE_SECDBG_CTRL,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN = 40,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE,
 EFUSE_GPU_VDDPC,
 EFUSE_MEMORYREPAIR_BYPN = 50,
 EFUSE_ONLINE_REPAIR,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_HISEE_EFUSE1,
 EFUSE_HISEE_EFUSE2,
 EFUSE_HISEE_EFUSE3,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_DIEID_LOT = 60,
 EFUSE_DIEID_WAFER,
 EFUSE_DIEID_X,
 EFUSE_DIEID_Y,
 EFUSE_BIG_CLUSTER_IDDQ,
 EFUSE_LITTLE_CLUSTER_IDDQ,
 EFUSE_GPU_IDDQ,
 EFUSE_SYS_IDDQ,
 EFUSE_PERI_IDDQ,
 EFUSE_TSENSOR_REF,
 EFUSE_ATE_FLAG = 70,
 EFUSE_HEALTH_LEVEL,
 EFUSE_MODEMAVS_PASENSOR,
 EFUSE_MODEMAVS,
 EFUSE_SVFD_VMIN,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_REMOTE_TSENSOR_DIG,
 EFUSE_UDS_VALUE,
 EFUSE_ROM_WDT,
 EFUSE_UFSBOOTROMMODE_SEL,
 EFUSE_PARTIAL_PASSP1 = 80,
 EFUSE_PARTIAL_PASSP2,
};
#endif
#define EFUSE_HUK_VALUE_START 0
#define EFUSE_HUK_VALUE_SIZE 256
#define EFUSE_SCP_VALUE_START 256
#define EFUSE_SCP_VALUE_SIZE 64
#define EFUSE_MP_FLAG_START 320
#define EFUSE_MP_FLAG_SIZE 32
#define EFUSE_HUK_ZEROES_START 320
#define EFUSE_HUK_ZEROES_SIZE 8
#define EFUSE_SCP_ZEROES_START 328
#define EFUSE_SCP_ZEROES_SIZE 7
#define EFUSE_OEMP_FLAG_START 352
#define EFUSE_OEMP_FLAG_SIZE 32
#define EFUSE_HBK1_ZEROES_START 360
#define EFUSE_HBK1_ZEROES_SIZE 8
#define EFUSE_KCE_ZEROES_START 376
#define EFUSE_KCE_ZEROES_SIZE 8
#define EFUSE_KCE_VALUE_START 384
#define EFUSE_KCE_VALUE_SIZE 128
#define EFUSE_HBK0_VALUE_START 512
#define EFUSE_HBK0_VALUE_SIZE 128
#define EFUSE_HBK1_VALUE_START 640
#define EFUSE_HBK1_VALUE_SIZE 128
#define EFUSE_TRB_COUNTER_START 768
#define EFUSE_TRB_COUNTER_SIZE 32
#define EFUSE_NTRB_COUNTER_START 800
#define EFUSE_NTRB_COUNTER_SIZE 224
#define EFUSE_EKCST_VALUE_START 1024
#define EFUSE_EKCST_VALUE_SIZE 128
#define EFUSE_EKCST_ZEROES_START 1152
#define EFUSE_EKCST_ZEROES_SIZE 32
#define EFUSE_DIEID_VALUE_START 1184
#define EFUSE_DIEID_VALUE_SIZE 160
#define EFUSE_IDDQ_VALUE_START 1344
#define EFUSE_IDDQ_VALUE_SIZE 50
#define EFUSE_TENSOR_TRIM_START 1394
#define EFUSE_TENSOR_TRIM_SIZE 55
#define EFUSE_HPM_TRIM_START 1449
#define EFUSE_HPM_TRIM_SIZE 10
#define EFUSE_SLT_FINISH_START 1960
#define EFUSE_SLT_FINISH_SIZE 3
#define EFUSE_SOFT_COUNTER_START 1963
#define EFUSE_SOFT_COUNTER_SIZE 32
#define EFUSE_MODEM_HUK_START 1995
#define EFUSE_MODEM_HUK_SIZE 128
#define EFUSE_MODEM_HUKZEROES_START 2123
#define EFUSE_MODEM_HUKZEROES_SIZE 8
#define EFUSE_DMHASH_VALUE_START 2131
#define EFUSE_DMHASH_VALUE_SIZE 1
#define EFUSE_FLASH_COUNT_START 2132
#define EFUSE_FLASH_COUNT_SIZE 8
#define EFUSE_INSE_FLAG_START 3130
#define EFUSE_INSE_FLAG_SIZE 2
#define EFUSE_ROOT_KEY_START 3132
#define EFUSE_ROOT_KEY_SIZE 264
#define EFUSE_CC712_KPTRL_START 3680
#define EFUSE_CC712_KPTRL_SIZE 128
#define EFUSE_CHIP_ID_START 3872
#define EFUSE_CHIP_ID_SIZE 64
#define EFUSE_SHUTDOWN_SWINGCARD_START 3979
#define EFUSE_SHUTDOWN_SWINGCARD_SIZE 2
#define EFUSE_AUTH_KEY_START 3424
#define EFUSE_AUTH_KEY_SIZE 128
#define EFUSE_DJTAG_CTRL_START 4050
#define EFUSE_DJTAG_CTRL_SIZE 2
#define EFUSE_MODEM_DBGBYPASS_START 4061
#define EFUSE_MODEM_DBGBYPASS_SIZE 1
#define EFUSE_PAD_DISABLE_START 4065
#define EFUSE_PAD_DISABLE_SIZE 1
#define EFUSE_HISEE_EFUSE4_START 4068
#define EFUSE_HISEE_EFUSE4_SIZE 2
#define EFUSE_HUKRD_DISABLE_START 4070
#define EFUSE_HUKRD_DISABLE_SIZE 1
#define EFUSE_SCPRD_DISABLE_START 4071
#define EFUSE_SCPRD_DISABLE_SIZE 1
#define EFUSE_DFTRD_DISABLE_START 4072
#define EFUSE_DFTRD_DISABLE_SIZE 1
#define EFUSE_SECDBG_CTRL_START 4073
#define EFUSE_SECDBG_CTRL_SIZE 2
#define EFUSE_SECDBG_DBGEN_START 4075
#define EFUSE_SECDBG_DBGEN_SIZE 1
#define EFUSE_SECDBG_NIDEN_START 4076
#define EFUSE_SECDBG_NIDEN_SIZE 1
#define EFUSE_SECDBG_SPIDEN_START 4077
#define EFUSE_SECDBG_SPIDEN_SIZE 1
#define EFUSE_SECDBG_SPNIDEN_START 4078
#define EFUSE_SECDBG_SPNIDEN_SIZE 1
#define EFUSE_SECDBG_DSPJTAGDIS_START 4079
#define EFUSE_SECDBG_DSPJTAGDIS_SIZE 1
#define EFUSE_SECENG_EKCSTRDEN_START 4083
#define EFUSE_SECENG_EKCSTRDEN_SIZE 1
#define EFUSE_KPRTLRD_DISABLE_START 4084
#define EFUSE_KPRTLRD_DISABLE_SIZE 1
#define EFUSE_DX_CLKEN_START 4092
#define EFUSE_DX_CLKEN_SIZE 1
#define EFUSE_DICE_EN_START 3120
#define EFUSE_DICE_EN_SIZE 2
#define EFUSE_DCIE_SECENGINE_START 3124
#define EFUSE_DCIE_SECENGINE_SIZE 1
#define EFUSE_GPU_VDDPC_START 1860
#define EFUSE_GPU_VDDPC_SIZE 2
#define EFUSE_MEMORYREPAIR_BYPN_START 4035
#define EFUSE_MEMORYREPAIR_BYPN_SIZE 1
#define EFUSE_ONLINE_REPAIR_START 2141
#define EFUSE_ONLINE_REPAIR_SIZE 3
#define EFUSE_OTP_SEVD_ENABLE_START 3129
#define EFUSE_OTP_SEVD_ENABLE_SIZE 1
#define EFUSE_CHIPID_VLD_START 4032
#define EFUSE_CHIPID_VLD_SIZE 1
#define EFUSE_DFTKEY_ZEROES_START 3992
#define EFUSE_DFTKEY_ZEROES_SIZE 8
#define EFUSE_HISEE_EFUSE1_START 4000
#define EFUSE_HISEE_EFUSE1_SIZE 32
#define EFUSE_HISEE_EFUSE2_START 4036
#define EFUSE_HISEE_EFUSE2_SIZE 9
#define EFUSE_HISEE_EFUSE3_START 4046
#define EFUSE_HISEE_EFUSE3_SIZE 2
#define EFUSE_KCST_DIS_START 335
#define EFUSE_KCST_DIS_SIZE 1
#define EFUSE_SEC_DIS_START 336
#define EFUSE_SEC_DIS_SIZE 4
#define EFUSE_DIEID_LOT_START 1188
#define EFUSE_DIEID_LOT_SIZE 36
#define EFUSE_DIEID_WAFER_START 1224
#define EFUSE_DIEID_WAFER_SIZE 5
#define EFUSE_DIEID_X_START 1229
#define EFUSE_DIEID_X_SIZE 8
#define EFUSE_DIEID_Y_START 1237
#define EFUSE_DIEID_Y_SIZE 8
#define EFUSE_BIG_CLUSTER_IDDQ_START 1344
#define EFUSE_BIG_CLUSTER_IDDQ_SIZE 10
#define EFUSE_LITTLE_CLUSTER_IDDQ_START 1354
#define EFUSE_LITTLE_CLUSTER_IDDQ_SIZE 10
#define EFUSE_GPU_IDDQ_START 1364
#define EFUSE_GPU_IDDQ_SIZE 10
#define EFUSE_SYS_IDDQ_START 1374
#define EFUSE_SYS_IDDQ_SIZE 10
#define EFUSE_PERI_IDDQ_START 1384
#define EFUSE_PERI_IDDQ_SIZE 10
#define EFUSE_TSENSOR_REF_START 1394
#define EFUSE_TSENSOR_REF_SIZE 11
#define EFUSE_ATE_FLAG_START 1312
#define EFUSE_ATE_FLAG_SIZE 1
#define EFUSE_HEALTH_LEVEL_START 3396
#define EFUSE_HEALTH_LEVEL_SIZE 8
#define EFUSE_MEMORY_REPAIR1_START 3840
#define EFUSE_MEMORY_REPAIR1_SIZE 32
#define EFUSE_MODEMAVS_PASENSOR_START 2252
#define EFUSE_MODEMAVS_PASENSOR_SIZE 20
#define EFUSE_MODEMAVS_START 2272
#define EFUSE_MODEMAVS_SIZE 4
#define EFUSE_SVFD_VMIN_START 1631
#define EFUSE_SVFD_VMIN_SIZE 201
#define EFUSE_REMOTE_TSENSOR_START 1459
#define EFUSE_REMOTE_TSENSOR_SIZE 162
#define EFUSE_REMOTE_TSENSOR_DIG_START 2144
#define EFUSE_REMOTE_TSENSOR_DIG_SIZE 108
#define EFUSE_UDS_VALUE_START 2464
#define EFUSE_UDS_VALUE_SIZE 256
#define EFUSE_ROM_WDT_START 3422
#define EFUSE_ROM_WDT_SIZE 2
#define EFUSE_UFSBOOTROMMODE_SEL_START 4062
#define EFUSE_UFSBOOTROMMODE_SEL_SIZE 1
#define EFUSE_PARTIAL_PASSP1_START 1921
#define EFUSE_PARTIAL_PASSP1_SIZE 39
#define EFUSE_PARTIAL_PASSP2_START 2276
#define EFUSE_PARTIAL_PASSP2_SIZE 92
#define EFUSE_PASENSOR_A73_START 1621
#define EFUSE_PASENSOR_A73_SIZE 10
#define EFUSE_PASENSOR_A53GPU_START 1832
#define EFUSE_PASENSOR_A53GPU_SIZE 20
#define EFUSE_MBIST_DIS_START 3976
#define EFUSE_MBIST_DIS_SIZE 1
#define EFUSE_AOMEMORY_REPAIR_START 3832
#define EFUSE_AOMEMORY_REPAIR_SIZE 40
#define EFUSE_PERI_MEMORY_REPAIR_START 3936
#define EFUSE_PERI_MEMORY_REPAIR_SIZE 40
#define EFUSE_CC712_MBIST_DIS_START 3978
#define EFUSE_CC712_MBIST_DIS_SIZE 1
#define EFUSE_MAX_SIZE 4096
#define EFUSE_ITEM_MAX 264
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
