#ifndef __SOC_MID_H__
#define __SOC_MID_H__ 
#define SOC_LPMCU_ATGS_MID 0x0
#define SOC_IOMCU_M7_MID 0x1
#define SOC_PCIE_1_MID 0x2
#define SOC_PERF_STAT_LATMON_MID 0x3
#define SOC_IPF_MID 0x4
#define SOC_DJTAG_M_TOP_CSSYS_MID 0x5
#define SOC_IOMCU_DMA_AO_TCP_BB_DRX_MID 0x6
#define SOC_UFS_MID 0x7
#define SOC_SD_MID 0x8
#define SOC_HSDT0_HSDT1_TRACE_MID 0x9
#define SOC_CC712_MID 0xa
#define SOC_FD_UL_MID 0xb
#define SOC_DPC_MID 0xc
#define SOC_SOCP_MID 0xd
#define SOC_USB31OTG_MID 0xe
#define SOC_ASP_DMA_USB_HDMI_MID 0xf
#define SOC_DMAC_MID 0x10
#define SOC_ASP_HIFI_MID 0x11
#define SOC_PCIE_0_MID 0x12
#define SOC_HSDT0_HSDT1_TCU_MID 0x13
#define SOC_MODEM5G_CPU5G_EICC1_EICC_MID 0x14
#define SOC_MODEM_AP_SIDE_MAA_MID 0x15
#define SOC_MODEM5G_L2CPU_CFG_L2C_MID 0x20
#define SOC_MODEM5G_L2HAC_CIPHER_MID 0x21
#define SOC_MODEM5G_LATENCY_MONITOR_MID 0x22
#define SOC_MODEM5G_CPU5G_CFG_L2C_MID 0x23
#define SOC_MODEM5G_LL1C_BBE3_SPE_MID 0x24
#define SOC_MODEM5G_L2HAC_EICC0_MID 0x25
#define SOC_MODEM5G_L2HAC_EICC1_MID 0x26
#define SOC_MODEM5G_LL1C_BBE0_MID 0x27
#define SOC_MODEM5G_LL1C_BBE1_MID 0x28
#define SOC_MODEM5G_LL1C_EDMA0_MID 0x29
#define SOC_MODEM5G_LL1C_EDMA1_MID 0x2a
#define SOC_MODEM5G_LL1C_EICC0_MID 0x2b
#define SOC_MODEM5G_LL1C_EICC1_MID 0x2c
#define SOC_MODEM5G_LL1C_FASTDMA_MID 0x2d
#define SOC_MODEM5G_BBP5G_FASTDMA_MID 0x2e
#define SOC_MODEM5G_CPU5G_EICC0_MID 0x2f
#define SOC_MODEM5G_BBP5G_COMDMA2SOC_MID 0x30
#define SOC_MODEM5G_BBP5G_COMDMA2DDR_MID 0x31
#define SOC_MODEM5G_BBP5G_PDE_PDS_MID 0x32
#define SOC_MODEM5G_BBP5G_PDE_CSI_MID 0x33
#define SOC_MODEM5G_MODEM_BBIC_MID 0x34
#define SOC_MODEM5G_BBP5G_NLDL2SOC_MID 0x35
#define SOC_MODEM_CIPHER_MID 0x16
#define SOC_MODEM_HDLC_MID 0x36
#define SOC_MODEM_CICOM0_MID 0x17
#define SOC_MODEM_CICOM1_MID 0x37
#define SOC_MODEM5G_LL1C_BBE2_NXDSP_MID 0x18
#define SOC_MODEM5G_BBP5G_NLDL2DDR_MID 0x38
#define SOC_MODEM_TL_BBP_DMA_TCM_MID 0x19
#define SOC_MODEM_TL_BBP_DMA_DDR_MID 0x39
#define SOC_MODEM_GU_BBP_MST_TCM_MID 0x1a
#define SOC_MODEM_GU_BBP_MST_DDR_MID 0x3a
#define SOC_MODEM5G_MODEM_MDM5G_EDMA0_MID 0x1b
#define SOC_MODEM5G_MODEM_MDM5G_EDMA1_MID 0x3b
#define SOC_MODEM5G_MODEM_BBP5G_UL_HARQ_L_MID 0x1c
#define SOC_MODEM_HARQ_H_MID 0x3c
#define SOC_MODEM_UPACC_MID 0x1d
#define SOC_MODEM5G_MODEM_MDM5G_RSR_ACC_MID 0x3d
#define SOC_MODEM_CIPHER_WRITE_THOUGH_MID 0x1e
#define SOC_MODEM_CCPU_CFG_L2C_MID 0x3f
#define SOC_MODEM_EDMA2_MID 0x1f
#define SOC_NPU_AICORE0_MID 0x40
#define SOC_NPU_AICORE1_MID 0x41
#define SOC_NPU_SYSDMA_0_MID 0x42
#define SOC_NPU_SYSDMA_1_MID 0x43
#define SOC_NPU_TS_0_MID 0x44
#define SOC_NPU_TS_1_MID 0x45
#define SOC_NPU_TINY_MID 0x46
#define SOC_NPU_TCU_MID 0x47
#define SOC_ISP_ISP_CORE_0_MID 0x48
#define SOC_ISP_ISP_CORE_1_MID 0x49
#define SOC_ISP_ISP_CORE_2_MID 0x4a
#define SOC_ISP_ISP_CORE_3_MID 0x4b
#define SOC_ISP_ARC_CBU_DMA_MID 0x4c
#define SOC_IDI2AXI_MID 0x4f
#define SOC_DSS_CMDLIST_MID 0x50
#define SOC_DSS_WR_CH1_MDC_RCH1_MID 0x51
#define SOC_DSS_WR_CH0_MDC_RCH0_MID 0x52
#define SOC_DSS_RD_CH8_MID 0x53
#define SOC_DSS_RD_CH7_MID 0x54
#define SOC_DSS_RD_CH6_MID 0x55
#define SOC_DSS_RD_CH5_MID 0x56
#define SOC_DSS_RD_CH4_MID 0x57
#define SOC_DSS_RD_CH3_MID 0x58
#define SOC_DSS_RD_CH2_MID 0x59
#define SOC_DSS_RD_CH1_MID 0x5a
#define SOC_DSS_RD_CH0_ATGM_MID 0x5b
#define SOC_MEDIA1_TCU_MID 0x5c
#define SOC_MEDIA_COMMON_RCH6_MID 0x5d
#define SOC_MEDIA_COMMON_CMDLIST_WCH0_MID 0x5e
#define SOC_MEDIA_COMMON_RCH2_WCH1_MID 0x5f
#define SOC_VENC_0_MID 0x60
#define SOC_VENC_1_MID 0x61
#define SOC_VDEC1_MID 0x62
#define SOC_VDEC2_MID 0x63
#define SOC_HIEPS_HIEPS_SCE2_MID 0x65
#define SOC_SYSTEM_CACHE_0_MID 0x66
#define SOC_SYSTEM_CACHE_1_MID 0x67
#define SOC_IPP_SUBSYS_JPGENC_MID 0x68
#define SOC_IPP_SUBSYS_JPGDEC_CMDLIST_MID 0x69
#define SOC_IPP_SUBSYS_VBK_ANF_PAC0_MID 0x6a
#define SOC_IPP_SUBSYS_GF_MID 0x6b
#define SOC_IPP_SUBSYS_SLAM_MID 0x6c
#define SOC_SYSTEM_CACHE_2_MID 0x6d
#define SOC_SYSTEM_CACHE_3_MID 0x6e
#define SOC_SYSTEM_CACHE_4_MID 0x6f
#define SOC_IVP32_DSP0_DSP_CORE_DATA_MID 0x70
#define SOC_IVP32_DSP0_DSP_CORE_INST_IVP_ATGM_MID 0x71
#define SOC_IVP32_DSP0_DSP_DMA_MID 0x72
#define SOC_IVP32_DSP1_DSP_CORE_DATA_MID 0x73
#define SOC_IVP32_DSP1_DSP_CORE_INST_IVP_ATGM_MID 0x74
#define SOC_IVP32_DSP1_DSP_DMA_MID 0x75
#define SOC_FCM_SYSNOC_FCM2SYSNOC_MID 0x76
#define SOC_MEDIA2_TCU_TCU_MID 0x77
#define SOC_FCM_M0_MID 0x78
#define SOC_FCM_M1_MID 0x79
#define SOC_GPU0_NON_DRM_MID 0x7a
#define SOC_GPU0_DRM_MID 0x7b
#define SOC_ARPP_CORE0_MID 0x7c
#define SOC_ARPP_CORE1_MID 0x7d
#define SOC_HIEPS_HIEPS_SCE_MID 0x7f
#define SOC_MAX_MID 0x80
#define SEC_ASI0_MASK 0x1F
#define SEC_ASI1_MASK 0x1F
#define SEC_ASI3_MASK 0x1F
#define SEC_ASI5_MASK 0x1F
#define SEC_ASI6_MASK 0x1
#define SEC_ASI8_MASK 0x1F
#define SEC_ASI9_MASK 0x1F
#define SEC_ASIA_MASK 0x1
#define SEC_ASIB_MASK 0x7
#define SEC_ASIF_MASK 0x3
#define TZMP2_ASI0_MASK 0x1F
#define TZMP2_ASI1_MASK 0x1F
#define TZMP2_ASI3_MASK 0x1F
#define TZMP2_ASI5_MASK 0x3F
#define TZMP2_ASI6_MASK 0x1F
#define TZMP2_ASI8_MASK 0x1F
#define TZMP2_ASI9_MASK 0x1F
#define TZMP2_ASIA_MASK 0x1F
#define TZMP2_ASIB_MASK 0x1F
#define TZMP2_ASIF_MASK 0x1F
#define BBIC_ASI0_MID (SOC_MODEM5G_MODEM_BBIC_MID & SEC_ASI0_MASK)
#define LL1C_BBE2_NXDSP_ASI0_MID (SOC_MODEM5G_LL1C_BBE2_NXDSP_MID & SEC_ASI0_MASK)
#define BBP5G_UL_HARQ_L_ASI0_MID (SOC_MODEM5G_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASI0_MASK)
#define HARQ_H_ASI0_MID (SOC_MODEM_HARQ_H_MID & SEC_ASI0_MASK)
#define CCPU_CFG_CCPU_L2C_MID (SOC_MODEM_CCPU_CFG_L2C_MID & SEC_ASI0_MASK)
#define VENC_0_MID (SOC_VENC_0_MID & SEC_ASI1_MASK)
#define VENC_1_MID (SOC_VENC_1_MID & SEC_ASI1_MASK)
#define VDEC1_MID (SOC_VDEC1_MID & SEC_ASI1_MASK)
#define VDEC2_MID (SOC_VDEC2_MID & SEC_ASI1_MASK)
#define VENC_ALL (BIT(VENC_0_MID) | BIT(VENC_1_MID))
#define VDEC_ALL (BIT(VDEC1_MID) | BIT(VDEC2_MID))
#define HIEPS_SCE2_MID (SOC_HIEPS_HIEPS_SCE2_MID & SEC_ASI1_MASK)
#define IPP_SUBSYS_JPGENC_MID (SOC_IPP_SUBSYS_JPGENC_MID & SEC_ASI1_MASK)
#define IPP_SUBSYS_JPGDEC_CMDLIST_MID (SOC_IPP_SUBSYS_JPGDEC_CMDLIST_MID & SEC_ASI1_MASK)
#define IPP_SUBSYS_VBK_ANF_PAC0_MID (SOC_IPP_SUBSYS_VBK_ANF_PAC0_MID& SEC_ASI1_MASK)
#define IPP_SUBSYS_GF_MID (SOC_IPP_SUBSYS_GF_MID & SEC_ASI1_MASK)
#define IPP_SUBSYS_SLAM_MID (SOC_IPP_SUBSYS_SLAM_MID & SEC_ASI1_MASK)
#define IPP_SUBSYS_ALL (BIT(IPP_SUBSYS_JPGENC_MID) | BIT(IPP_SUBSYS_JPGDEC_CMDLIST_MID) | \
  BIT(IPP_SUBSYS_VBK_ANF_PAC0_MID) | BIT(IPP_SUBSYS_GF_MID) | BIT(IPP_SUBSYS_SLAM_MID))
#define IVP32_DSP0_DSP_CORE_DATA_MID (SOC_IVP32_DSP0_DSP_CORE_DATA_MID & SEC_ASI1_MASK)
#define IVP32_DSP0_DSP_CORE_INST_MID (SOC_IVP32_DSP0_DSP_CORE_INST_IVP_ATGM_MID & SEC_ASI1_MASK)
#define IVP32_DSP0_DSP_DMA_MID (SOC_IVP32_DSP0_DSP_DMA_MID & SEC_ASI1_MASK)
#define IVP32_DSP1_DSP_CORE_DATA_MID (SOC_IVP32_DSP1_DSP_CORE_DATA_MID & SEC_ASI1_MASK)
#define IVP32_DSP1_DSP_CORE_INST_MID (SOC_IVP32_DSP1_DSP_CORE_INST_IVP_ATGM_MID & SEC_ASI1_MASK)
#define IVP32_DSP1_DSP_DMA_MID (SOC_IVP32_DSP1_DSP_DMA_MID & SEC_ASI1_MASK)
#define IVP_ALL (BIT(IVP32_DSP0_DSP_CORE_INST_MID) | BIT(IVP32_DSP0_DSP_DMA_MID) | \
  BIT(IVP32_DSP0_DSP_CORE_DATA_MID) | BIT(IVP32_DSP1_DSP_CORE_INST_MID) | \
  BIT(IVP32_DSP1_DSP_DMA_MID) | BIT(IVP32_DSP1_DSP_CORE_DATA_MID))
#define MEDIA2_TCU_MID (SOC_MEDIA2_TCU_TCU_MID & SEC_ASI1_MASK)
#define ARPP_CORE0_MID (SOC_ARPP_CORE0_MID & SEC_ASI1_MASK)
#define ARPP_CORE1_MID (SOC_ARPP_CORE1_MID & SEC_ASI1_MASK)
#define ARPP_ALL_MID (BIT(ARPP_CORE0_MID) | BIT(ARPP_CORE1_MID))
#define HIEPS_SCE_MID (SOC_HIEPS_HIEPS_SCE_MID & SEC_ASI1_MASK)
#define ISP_ISP_CORE_0_MID (SOC_ISP_ISP_CORE_0_MID & SEC_ASI3_MASK)
#define ISP_ISP_CORE_1_MID (SOC_ISP_ISP_CORE_1_MID & SEC_ASI3_MASK)
#define ISP_ISP_CORE_2_MID (SOC_ISP_ISP_CORE_2_MID & SEC_ASI3_MASK)
#define ISP_ISP_CORE_3_MID (SOC_ISP_ISP_CORE_3_MID & SEC_ASI3_MASK)
#define ISP_ARC_CBU_DMA_MID (SOC_ISP_ARC_CBU_DMA_MID & SEC_ASI3_MASK)
#define IDI2AXI_MID (SOC_IDI2AXI_MID & SEC_ASI3_MASK)
#define DSS_CMDLIST_MID (SOC_DSS_CMDLIST_MID & SEC_ASI3_MASK)
#define DSS_WR_1_MID (SOC_DSS_WR_CH1_MDC_RCH1_MID & SEC_ASI3_MASK)
#define DSS_WR_0_MID (SOC_DSS_WR_CH0_MDC_RCH0_MID & SEC_ASI3_MASK)
#define DSS_RD_8_MID (SOC_DSS_RD_CH8_MID & SEC_ASI3_MASK)
#define DSS_RD_7_MID (SOC_DSS_RD_CH7_MID & SEC_ASI3_MASK)
#define DSS_RD_6_MID (SOC_DSS_RD_CH6_MID & SEC_ASI3_MASK)
#define DSS_RD_5_MID (SOC_DSS_RD_CH5_MID & SEC_ASI3_MASK)
#define DSS_RD_4_MID (SOC_DSS_RD_CH4_MID & SEC_ASI3_MASK)
#define DSS_RD_3_MID (SOC_DSS_RD_CH3_MID & SEC_ASI3_MASK)
#define DSS_RD_2_MID (SOC_DSS_RD_CH2_MID & SEC_ASI3_MASK)
#define DSS_RD_1_MID (SOC_DSS_RD_CH1_MID & SEC_ASI3_MASK)
#define DSS_RD_0_MID (SOC_DSS_RD_CH0_ATGM_MID & SEC_ASI3_MASK)
#define ISP_ALL (BIT(ISP_ISP_CORE_0_MID) | BIT(ISP_ISP_CORE_1_MID) | BIT(ISP_ISP_CORE_2_MID) | \
 BIT(ISP_ISP_CORE_3_MID) | BIT(ISP_ARC_CBU_DMA_MID))
#define ISP_CORE_ALL (BIT(ISP_ISP_CORE_0_MID) | BIT(ISP_ISP_CORE_1_MID) | BIT(ISP_ISP_CORE_2_MID) | \
 BIT(ISP_ISP_CORE_3_MID))
#define DSS_ALL (BIT(DSS_CMDLIST_MID) | BIT(DSS_WR_1_MID) | BIT(DSS_WR_0_MID) | BIT(DSS_RD_8_MID) | \
 BIT(DSS_RD_7_MID) | BIT(DSS_RD_6_MID) | BIT(DSS_RD_5_MID) | BIT(DSS_RD_4_MID) | \
 BIT(DSS_RD_3_MID) | BIT(DSS_RD_2_MID) | BIT(DSS_RD_1_MID) | BIT(DSS_RD_0_MID))
#define MEDIA1_TCU_MID (SOC_MEDIA1_TCU_MID & SEC_ASI3_MASK)
#define MEDIA_COMMON_RCH6_MID (SOC_MEDIA_COMMON_RCH6_MID & SEC_ASI3_MASK)
#define MEDIA_COMMON_CMDLIST_WCH0_MID (SOC_MEDIA_COMMON_CMDLIST_WCH0_MID & SEC_ASI3_MASK)
#define MEDIA_COMMON_RCH2_WCH1_MID (SOC_MEDIA_COMMON_RCH2_WCH1_MID & SEC_ASI3_MASK)
#define MEDIA_COMMON_ALL (BIT(MEDIA_COMMON_CMDLIST_WCH0_MID) | BIT(MEDIA_COMMON_RCH2_WCH1_MID) | \
 BIT(MEDIA_COMMON_RCH6_MID))
#define LPMCU_ATGS_MID (SOC_LPMCU_ATGS_MID & SEC_ASI5_MASK)
#define IOMCU_M7_MID (SOC_IOMCU_M7_MID & SEC_ASI5_MASK)
#define PCIE_1_MID (SOC_PCIE_1_MID & SEC_ASI5_MASK)
#define PERF_STAT_LATMON_MID (SOC_PERF_STAT_LATMON_MID & SEC_ASI5_MASK)
#define IPF_MID (SOC_IPF_MID & SEC_ASI5_MASK)
#define DJTAG_M_TOP_CSSYS_MID (SOC_DJTAG_M_TOP_CSSYS_MID & SEC_ASI5_MASK)
#define IOMCU_DMA_AO_TCP_BB_DRX_MID (SOC_IOMCU_DMA_AO_TCP_BB_DRX_MID & SEC_ASI5_MASK)
#define UFS_MID (SOC_UFS_MID & SEC_ASI5_MASK)
#define SD_MID (SOC_SD_MID & SEC_ASI5_MASK)
#define HSDT0_HSDT1_TRACE_MID (SOC_HSDT0_HSDT1_TRACE_MID & SEC_ASI5_MASK)
#define CC712_MID (SOC_CC712_MID & SEC_ASI5_MASK)
#define FD_UL_MID (SOC_FD_UL_MID & SEC_ASI5_MASK)
#define DPC_MID (SOC_DPC_MID & SEC_ASI5_MASK)
#define SOCP_MID (SOC_SOCP_MID & SEC_ASI5_MASK)
#define USB31OTG_MID (SOC_USB31OTG_MID & SEC_ASI5_MASK)
#define ASP_DMA_USB_HDMI_MID (SOC_ASP_DMA_USB_HDMI_MID & SEC_ASI5_MASK)
#define DMAC_MID (SOC_DMAC_MID & SEC_ASI5_MASK)
#define ASP_HIFI_MID (SOC_ASP_HIFI_MID & SEC_ASI5_MASK)
#define PCIE_0_MID (SOC_PCIE_0_MID & SEC_ASI5_MASK)
#define HSDT0_TCU_HSDT1_TCU_MID (SOC_HSDT0_HSDT1_TCU_MID & SEC_ASI5_MASK)
#define CPU5G_EICC1_EICC_ASI5_MID (SOC_MODEM5G_CPU5G_EICC1_EICC_MID & SEC_ASI5_MASK)
#define MODEM_MAA_MID (SOC_MODEM_AP_SIDE_MAA_MID & SEC_ASI5_MASK)
#define LL1C_BBE3_SPE_ASI5_MID (SOC_MODEM5G_LL1C_BBE3_SPE_MID & SEC_ASI5_MASK)
#define MODEM_CIPHER_MID (SOC_MODEM_CIPHER_MID & SEC_ASI5_MASK)
#define MODEM_HDLC_MID (SOC_MODEM_HDLC_MID & SEC_ASI5_MASK)
#define MODEM_CICOM0_MID (SOC_MODEM_CICOM0_MID & SEC_ASI5_MASK)
#define MODEM_CICOM1_MID (SOC_MODEM_CICOM1_MID & SEC_ASI5_MASK)
#define TL_BBP_DMA_TCM_MID (SOC_MODEM_TL_BBP_DMA_TCM_MID & SEC_ASI5_MASK)
#define TL_BBP_DMA_DDR_MID (SOC_MODEM_TL_BBP_DMA_DDR_MID & SEC_ASI5_MASK)
#define GU_BBP_MST_TCM_MID (SOC_MODEM_GU_BBP_MST_TCM_MID & SEC_ASI5_MASK)
#define GU_BBP_MST_DDR_MID (SOC_MODEM_GU_BBP_MST_DDR_MID & SEC_ASI5_MASK)
#define MDM5G_EDMA0_EDMA0_ASI5_MID (SOC_MODEM5G_MODEM_MDM5G_EDMA0_MID & SEC_ASI5_MASK)
#define MDM5G_EDMA1_EDMA1_ASI5_MID (SOC_MODEM5G_MODEM_MDM5G_EDMA1_MID & SEC_ASI5_MASK)
#define BBP5G_UL_HARQ_L_ASI5_MID (SOC_MODEM5G_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASI5_MASK)
#define HARQ_H_ASI5_MID (SOC_MODEM_HARQ_H_MID & SEC_ASI5_MASK)
#define MODEM_UPACC_MID (SOC_MODEM_UPACC_MID & SEC_ASI5_MASK)
#define MDM5G_RSR_ACC_RSR_ACC_ASI5_MID (SOC_MODEM5G_MODEM_MDM5G_RSR_ACC_MID & SEC_ASI5_MASK)
#define CIPHER_WRITE_THOUGH_MID (SOC_MODEM_CIPHER_WRITE_THOUGH_MID & SEC_ASI5_MASK)
#define MODEM_EDMA2_MID (SOC_MODEM_EDMA2_MID & SEC_ASI5_MASK)
#define FCM_SYSNOC_FCM2SYSNOC_MID (SOC_FCM_SYSNOC_FCM2SYSNOC_MID & SEC_ASI5_MASK)
#define FCM_M0_MID (SOC_FCM_M0_MID & SEC_ASI6_MASK)
#define FCM_M1_MID (SOC_FCM_M1_MID & SEC_ASI6_MASK)
#define CPU_ALL (BIT(FCM_M0_MID) | BIT(FCM_M1_MID))
#define CPU5G_CFG_CPU5G_L2C_MID (SOC_MODEM5G_CPU5G_CFG_L2C_MID & SEC_ASI8_MASK)
#define BBP5G_FASTDMA_MID (SOC_MODEM5G_BBP5G_FASTDMA_MID & SEC_ASI8_MASK)
#define BBP5G_COMDMA2SOC_MID (SOC_MODEM5G_BBP5G_COMDMA2SOC_MID & SEC_ASI8_MASK)
#define BBP5G_COMDMA2DDR_MID (SOC_MODEM5G_BBP5G_COMDMA2DDR_MID & SEC_ASI8_MASK)
#define BBP5G_PDE_PDS_MID (SOC_MODEM5G_BBP5G_PDE_PDS_MID & SEC_ASI8_MASK)
#define BBP5G_PDE_CSI_MID (SOC_MODEM5G_BBP5G_PDE_CSI_MID & SEC_ASI8_MASK)
#define BBIC_ASI8_MID (SOC_MODEM5G_MODEM_BBIC_MID & SEC_ASI8_MASK)
#define BBP5G_NLDL2SOC_MID (SOC_MODEM5G_BBP5G_NLDL2SOC_MID & SEC_ASI8_MASK)
#define BBP5G_UL_HARQ_L_ASI8_MID (SOC_MODEM5G_MODEM_BBP5G_UL_HARQ_L_MID & SEC_ASI8_MASK)
#define CPU5G_EICC1_EICC_ASI9_MID (SOC_MODEM5G_CPU5G_EICC1_EICC_MID & SEC_ASI9_MASK)
#define L2CPU_CFG_L2CPU_L2C_MID (SOC_MODEM5G_L2CPU_CFG_L2C_MID & SEC_ASI9_MASK)
#define L2HAC_CIPHER_MID (SOC_MODEM5G_L2HAC_CIPHER_MID & SEC_ASI9_MASK)
#define LATENCY_MONITOR_MID (SOC_MODEM5G_LATENCY_MONITOR_MID & SEC_ASI9_MASK)
#define L2HAC_EICC0_MID (SOC_MODEM5G_L2HAC_EICC0_MID & SEC_ASI9_MASK)
#define L2HAC_EICC1_MID (SOC_MODEM5G_L2HAC_EICC1_MID & SEC_ASI9_MASK)
#define LL1C_BBE0_MID (SOC_MODEM5G_LL1C_BBE0_MID & SEC_ASI9_MASK)
#define LL1C_BBE1_MID (SOC_MODEM5G_LL1C_BBE1_MID & SEC_ASI9_MASK)
#define LL1C_BBE3_SPE_ASI9_MID (SOC_MODEM5G_LL1C_BBE3_SPE_MID & SEC_ASI9_MASK)
#define LL1C_EDMA0_MID (SOC_MODEM5G_LL1C_EDMA0_MID & SEC_ASI9_MASK)
#define LL1C_EDMA1_MID (SOC_MODEM5G_LL1C_EDMA1_MID & SEC_ASI9_MASK)
#define LL1C_EICC0_MID (SOC_MODEM5G_LL1C_EICC0_MID & SEC_ASI9_MASK)
#define LL1C_EICC1_MID (SOC_MODEM5G_LL1C_EICC1_MID & SEC_ASI9_MASK)
#define LL1C_FASTDMA_MID (SOC_MODEM5G_LL1C_FASTDMA_MID & SEC_ASI9_MASK)
#define CPU5G_EICC0_MID (SOC_MODEM5G_CPU5G_EICC0_MID & SEC_ASI9_MASK)
#define LL1C_BBE2_NXDSP_ASI9_MID (SOC_MODEM5G_LL1C_BBE2_NXDSP_MID & SEC_ASI9_MASK)
#define MDM5G_EDMA0_EDMA0_ASI9_MID (SOC_MODEM5G_MODEM_MDM5G_EDMA0_MID & SEC_ASI9_MASK)
#define MDM5G_EDMA1_EDMA1_ASI9_MID (SOC_MODEM5G_MODEM_MDM5G_EDMA1_MID & SEC_ASI9_MASK)
#define MDM5G_RSR_ACC_RSR_ACC_ASI9_MID (SOC_MODEM5G_MODEM_MDM5G_RSR_ACC_MID & SEC_ASI9_MASK)
#define BBP5G_NLDL2DDR_MID (SOC_MODEM5G_BBP5G_NLDL2DDR_MID & SEC_ASIA_MASK)
#define NPU_AICORE0_MID (SOC_NPU_AICORE0_MID & SEC_ASIB_MASK)
#define NPU_AICORE1_MID (SOC_NPU_AICORE1_MID & SEC_ASIB_MASK)
#define NPU_SYSDMA_TINY_MID (SOC_NPU_SYSDMA_0_MID & SEC_ASIB_MASK)
#define NPU_SYSDMA_LITE_MID (SOC_NPU_SYSDMA_1_MID & SEC_ASIB_MASK)
#define NPU_TS_CPU_MID (SOC_NPU_TS_0_MID & SEC_ASIB_MASK)
#define NPU_TS_HWTS_MID (SOC_NPU_TS_1_MID & SEC_ASIB_MASK)
#define NPU_TINY_MID (SOC_NPU_TINY_MID & SEC_ASIB_MASK)
#define NPU_TCU_MID (SOC_NPU_TCU_MID & SEC_ASIB_MASK)
#define NPU_ALL (BIT(NPU_AICORE0_MID) | BIT(NPU_AICORE1_MID) | BIT(NPU_SYSDMA_TINY_MID) | \
 BIT(NPU_SYSDMA_LITE_MID) | BIT(NPU_TS_CPU_MID) | BIT(NPU_TS_HWTS_MID) | BIT(NPU_TINY_MID) | \
 BIT(NPU_TCU_MID))
#define GPU0_NON_DRM_MID (SOC_GPU0_NON_DRM_MID & SEC_ASIF_MASK)
#define GPU0_DRM_MID (SOC_GPU0_DRM_MID & SEC_ASIF_MASK)
#define GPU_ALL (BIT(GPU0_NON_DRM_MID) | BIT(GPU0_DRM_MID))
#define FORBID_MID 0x0
#define ALL_MID 0xFFFFFFFF
#endif
