obj-$(CONFIG_HUAWEI_CHARGER_AP) += huawei_charger_common.o
obj-$(CONFIG_HUAWEI_CHARGER_AP) += huawei_charger_uevent.o

obj-$(CONFIG_HUAWEI_CHARGER_AP) += charger_ap/
obj-$(CONFIG_HUAWEI_WATCH_CHARGER) += watch_charger/
