#ifndef __HI_EFUSE_H__
#define __HI_EFUSE_H__ 
#define HI_K3_EFUSE 
#define EFUSE_MAX_SIZE (64)
#define EFUSE_AVS_VALUE 
#define EFUSE_GRP_AVS (0)
#define EFUSE_AVS_GROUP_SIZE (1)
#define EFUSE_AVS_GROUP_START (0)
#define EFUSE_GRP_DIEID (32)
#define EFUSE_DIEID_SIZE (5)
#define EFUSE_GRP_HUK (28)
#define EFUSE_HUK_SIZE (4)
#define EFUSE_HUK_LEN (EFUSE_HUK_SIZE * EFUSE_GROUP_SIZE)
#define HUK_SEC_DDR_SIZE (0x1000U)
#define BL31_BASE_ADDR (0x13000000U)
#define BL31_SHM_OFFSET (0x1001b0U)
#define HUK_SEC_DDR_ADDR ((BL31_BASE_ADDR + BL31_SHM_OFFSET) & ~(HUK_SEC_DDR_SIZE-1))
#define HUK_SEC_DDR_OFFSET ((BL31_BASE_ADDR + BL31_SHM_OFFSET) & (HUK_SEC_DDR_SIZE-1))
#endif
