EXTRA_CFLAGS += -Idrivers/hisi/hi6xxx/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Idrivers/hisi/soc_mad/

snd-soc-hi6555-store-objs :=hi6555_store.o
snd-soc-hi6555-core-path-objs :=hi6555_core_path.o
snd-soc-hi6555-audio-path-objs :=hi6555_audio_path.o
snd-soc-hi6555-ultr-path-objs :=hi6555_ultr_path.o
snd-soc-hi6555-voice-path-objs :=hi6555_voice_path.o
snd-soc-hi6555-smpa-path-objs :=hi6555_smpa_path.o
snd-soc-hi6555-third-codec-path-objs :=hi6555_third_codec_path.o
snd-soc-hi6555-btfm-path-objs :=hi6555_btfm_path.o
snd-soc-hi6555-mad-path-objs :=hi6555_mad_path.o

snd-soc-hi6555-i2s-objs :=hi6555_i2s.o
snd-soc-hi6555-codec-objs :=hi6555_codec.o
snd-soc-hi6555-utils-objs :=hi6555_utils.o
snd-soc-hi6555v3-objs :=hi6555v3.o
snd-soc-hi6555v5-objs :=hi6555v5.o

obj-$(CONFIG_SND_SOC_HI6555_STORE) += snd-soc-hi6555-store.o
obj-$(CONFIG_SND_SOC_HI6555_CORE_PATH) += snd-soc-hi6555-core-path.o
obj-$(CONFIG_SND_SOC_HI6555_AUDIO_PATH) += snd-soc-hi6555-audio-path.o
obj-$(CONFIG_SND_SOC_HI6555_ULTR_PATH) += snd-soc-hi6555-ultr-path.o
obj-$(CONFIG_SND_SOC_HI6555_VOICE_PATH) += snd-soc-hi6555-voice-path.o
obj-$(CONFIG_SND_SOC_HI6555_SMPA_PATH) += snd-soc-hi6555-smpa-path.o
obj-$(CONFIG_SND_SOC_HI6555_THIRD_CODEC_PATH) += snd-soc-hi6555-third-codec-path.o
obj-$(CONFIG_SND_SOC_HI6555_BTFM_PATH) += snd-soc-hi6555-btfm-path.o
obj-$(CONFIG_SND_SOC_HI6555_MAD_PATH) += snd-soc-hi6555-mad-path.o
obj-$(CONFIG_SND_SOC_HI6555_I2S) += snd-soc-hi6555-i2s.o
obj-$(CONFIG_SND_SOC_HI6555_CODEC) += snd-soc-hi6555-codec.o
obj-$(CONFIG_SND_SOC_HI6555_UTILITY) += snd-soc-hi6555-utils.o
obj-$(CONFIG_SND_SOC_CODEC_HI6555V3) += snd-soc-hi6555v3.o
obj-$(CONFIG_SND_SOC_CODEC_HI6555V5) += snd-soc-hi6555v5.o

