obj-$(CONFIG_SCHARGER_V200)             += schargerV200/
obj-$(CONFIG_SCHARGER_V300)             += schargerV300/
obj-$(CONFIG_SCHARGER_V600)             += schargerV600/
obj-$(CONFIG_HISI_CHARGER_SYS_WDG)      += hisi_charging_watchdog.o
