obj-$(CONFIG_HUAWEI_CHARGER_AP) += charger_ic/
obj-$(CONFIG_BOOST_5V) += boost_5v/
obj-$(CONFIG_CHARGE_PUMP) += charge_pump/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_ic/
obj-$(CONFIG_LOADSWITCH) += load_switch/
obj-$(CONFIG_SWITCHCAP) += switch_capacitor/
obj-$(CONFIG_CHARGE_ADC_MONITOR) += charge_adc_monitor/
