ccflags-y += -Wall -Werror
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver

obj-$(CONFIG_HISI_BB_DIAGINFO) += bbox_lpmcu_diaginfo.o
obj-$(CONFIG_HISI_BB_DIAGINFO) += bbox_ap_ipc.o
obj-$(CONFIG_HISI_BB_DIAGINFO) += bbox_diaginfo.o mntn_diaginfo_record.o bbox_user_diaginfo.o
obj-$(CONFIG_HISI_HW_DIAG) += hisi_hw_diag.o
