#
# Makefile for wifi Tcp-ipv4
#
obj-$(CONFIG_HW_WIFIPRO) += wifipro_tcp_monitor.o
obj-$(CONFIG_HW_SNIFFER) += sysctl_sniffer.o
obj-$(CONFIG_HW_CHR_TCP_SMALL_WIN_MONITOR) += tcp_small_window_chr_monitor.o