obj-$(CONFIG_VBUS_CHANNEL) += vbus_channel.o
obj-$(CONFIG_VBUS_CHANNEL) += vbus_channel_error_handle.o

obj-$(CONFIG_VBUS_CHANNEL_CHARGER) += vbus_channel_charger/
obj-$(CONFIG_VBUS_CHANNEL_BOOST_GPIO) += vbus_channel_boost_gpio/
obj-$(CONFIG_VBUS_CHANNEL_POGOPIN_BOOST) += vbus_channel_pogopin_boost/
