#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_mdmext_area.o 
obj-y				+= dump_mdmext_baseinfo.o
obj-y				+= dump_mdmext_comm.o
obj-y				+= dump_mdmext_config.o 
obj-y				+= dump_mdmext_fastboot_agent.o
obj-y				+= dump_mdmext_field.o
obj-y				+= dump_mdmext_kernel_agent.o
obj-y				+= dump_mdmext_pcie_comm.o
obj-y				+= dump_mdmext_core.o
obj-y               += dump_mdmext_pstore_dump.o
obj-y				+= dump_mdmext_logzip.o
obj-y				+= dump_mdmext_uart.o
obj-y				+= dump_mdmext_uart_comm.o
obj-y				+= dump_mdmext_uart_comm.o
obj-y				+= dump_mdmext_uart_escape.o
obj-y				+= dump_mdmext_boot_log.o
obj-y				+= dump_mdmext_boot_check.o
