#
# Makefile for kernel echub driver.
#

obj-$(CONFIG_HUAWEI_ECHUB_I2C)	+= echub_i2c.o
obj-$(CONFIG_HUAWEI_ECHUB_MUTELED)	+= keyboard/
obj-$(CONFIG_HUAWEI_ECHUB_PMSYNC)	  += power/
obj-$(CONFIG_HUAWEI_ECHUB_BATTERY)	  += battery/
