obj-$(CONFIG_USB_F_BALONG_ACM)	+= usb_f_balong_acm.o
usb_f_balong_acm-y		:= f_balong_acm.o balong_acm.o usb_vendor.o
usb_f_balong_acm-y		+= hisi_adp_acm.o hisi_adp_usb.o hisi_adp_acm_test.o
usb_f_balong_acm-y	+= hiusb_acm_debug.o

obj-y += hisi_adp_interface_fake.o

