# MD5: 363ee87adcd74687e0192f71e332619e
CFG_BBIC_CHIP_ES := YES
CFG_ZSP_DSP_CHIP_BB_TYPE		:=53
CFG_NV_VERSION :=baltimore
CFG_ZSP_DSP_PRODUCT_FORM		:=4
CFG_BOARD                               := ASIC
CFG_UPHY_BOARD_TYPE                     := 2
CFG_FEATURE_TEMP_MULTI_MODE_LP          := FEATURE_ON
CFG_FEATURE_GSM_SDR                     := FEATURE_ON
CFG_FEATURE_GSM_SDR_DAIC                := FEATURE_ON
CFG_FEATURE_GSM_WHOLE_SDR		:= FEATURE_ON
CFG_FEATURE_XBBE16_NEW_MAIL		:= FEATURE_ON
CFG_FEATURE_SRAM_400K                   := FEATURE_OFF
CFG_FEATURE_EXTERNAL_32K_CLK		    := FEATURE_ON
CFG_FEATURE_SOCP_ON_DEMAND			    := FEATURE_OFF
CFG_FEATURE_TAS				:= FEATURE_ON
ifeq ($(CFG_EMU_TYPE_ESLPS),FEATURE_ON)
CFG_FEATURE_NPHY_ESLPS := YES
endif
ifeq ($(CFG_EMU_TYPE_ESL),FEATURE_ON)
CFG_FEATURE_NPHY_ESL := YES
endif
CFG_FEATURE_VIRTUAL_BAND			    := FEATURE_ON
CFG_FEATURE_HI6363                		:= FEATURE_ON
CFG_FEATURE_RTT_TEST:=FEATURE_OFF
CFG_FEATURE_RTT_RANDOM_TEST                     := FEATURE_OFF
CFG_FEATURE_GUTLC_ONE_DSP               := FEATURE_ON
CFG_FEATURE_NX_CORE_OPEN                := FEATURE_ON
CFG_FEATURE_CSDR                        := FEATURE_ON
CFG_FEATURE_HITUNE                      := FEATURE_OFF
CFG_CPHY_PUB_DTCM_GLB_MINUS_LOCAL	    := 0x00800000
CFG_GUC_RTT_TEST_ENABLED:=NO
CFG_PHY_CBT_ENABLED:=NO
CFG_MODEM_GUPHY_LTO                       := YES
CFG_UPHY_NSCS_CTRL:=NO
