obj-$(CONFIG_LCD_KIT_MTK) += backlight_linear_to_exp.o
obj-$(CONFIG_LCD_KIT_MTK) += ktd3133.o
obj-$(CONFIG_LCD_KIT_MTK) += lm3697.o
obj-$(CONFIG_LCD_KIT_MTK) += sgm37603a.o
obj-$(CONFIG_LCD_KIT_MTK) += lm36923.o
obj-$(CONFIG_LCD_KIT_MTK) += ktz8864.o
obj-$(CONFIG_LCD_KIT_MTK) += lm36274.o
obj-$(CONFIG_LCD_KIT_MTK) += rt4831.o
obj-$(CONFIG_LCD_KIT_MTK) += nt50356.o
obj-$(CONFIG_LCD_KIT_MTK) += aw99703.o
obj-$(CONFIG_LCD_KIT_MTK) += sm5350.o
obj-$(CONFIG_LCD_KIT_MTK) += ktd3136.o

EXTRA_CFLAGS +=-Idrivers/staging/android \
		-Idrivers/atfdriver \
		-Idrivers/devkit/lcdkit/lcdkit3.0 \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/mtk/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/mtk/adapt \
		-Idrivers/misc/mediatek/lcm/inc
