# MD5: 87100926bd33627e08a074fc13e28be0
CFG_TENSILICA_BUILDS_HIFI   :=$(ROOT_XTENSA_PATH_W)/XtDevTools/install/builds/RF-2015.3-linux
CFG_TENSILICA_TOOLS_HIFI    :=$(ROOT_XTENSA_PATH_W)/XtDevTools/install/tools/RF-2015.3-linux
CFG_FEATURE_HIFI                                := FEATURE_ON
CFG_FEATURE_HIFI_USE_ICC                        := FEATURE_ON
CFG_MBB_HIFI_ENABLE_PACK_IMAGE := YES
CFG_FEATURE_MBB_MODULE_AUDIO                    := FEATURE_ON
CFG_FEATURE_VOICE_UP                            := FEATURE_OFF
CFG_FEATURE_DTMF                                := FEATURE_ON
CFG_FEATURE_VOICE_INBAND_DTMF_ELIMINATE         := FEATURE_ON
CFG_PLATFORM_CHIP_TYPE :=p532
