# MD5: 24ec653425c674ee59ae561e36a08635
CFG_TLPHY_CSU_DATA_SAMPLE_ENABLED      := YES
CFG_TLPHY_OM_RPT_ENABLED               := YES
CFG_TL_RFD_READ_ENABLED               := YES
CFG_TLPHY_DESENSITIZATION_OFF           := YES
CFG_TLPHY_ASSERT_ENABLED               := YES
