obj-$(CONFIG_HISI_PROC_HARDWARE) += hardware_info.o
obj-$(CONFIG_HISI_PROC_MEMORYINFO_FAST) += meminfo_lite.o
obj-$(CONFIG_HISI_SWAP_ZDATA) += process_reclaim_info.o
obj-$(CONFIG_HISI_LOWMEM_DBG) += lmkd_dbg_trigger.o
