#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= nrrdr_agent.o 
obj-y				+= nrrdr_core.o
obj-y				+= nrrdr_logs.o