obj-$(CONFIG_HW_RTG_SCHED) += iaware_rtg.o
obj-$(CONFIG_HW_RTG_SCHED) += proc_state.o
obj-$(CONFIG_HW_RTG_SCHED) += set_rtg.o
obj-$(CONFIG_HW_RTG_SCHED) += trans_rtg.o
obj-$(CONFIG_HW_RTG_SCHED) += frame_timer.o
obj-$(CONFIG_HW_RTG_SCHED) += aux_info.o
obj-$(CONFIG_FRAME_RTG_DEBUG) += aux_debug.o
