obj-$(CONFIG_HISI_CLK)                  += clk.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-gate.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-ppll.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-div.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-xfreq.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-clkpmu.o
obj-$(CONFIG_HISI_CLK)                  += hisi-kirin-fast-dvfs.o

obj-$(CONFIG_HISI_CLK)                  += platform/

obj-$(CONFIG_HISI_CLK_DEBUG)            += debug/
obj-$(CONFIG_HISI_CLK_MAILBOX_SUPPORT)	+= hisi-clk-mailbox.o

obj-$(CONFIG_HISI_CLK)                  += clk-dvfs.o
obj-$(CONFIG_HISI_CLK_PM_MONITOR)       += hisi-clk-pm-monitor.o
obj-$(CONFIG_HISI_CLK)                  += hisi-clk-intr.o

obj-$(CONFIG_HISI_PERIDVFS)             += dvfs/
obj-$(CONFIG_HISI_CKM_MODULE)	+= hisi-clk-monitor.o
obj-$(CONFIG_HISI_CLK_SMC_SUPPORT) += hisi-clk-smc.o
