obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_pwr_src.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_pwr_ctrl.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_vset.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_cap.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_open_by_client.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_auth.o
