obj-$(CONFIG_HI3650_DDRC_FLUX) += hi3650_ddr_ddrcflux.o
obj-$(CONFIG_HISI_DDRC_FLUX) += hisi_ddr_ddrcflux.o
obj-$(CONFIG_HISI_DDR_TRACKING) += hisi_ddr_tracking.o

obj-$(CONFIG_HISI_DDRC_SEC) += hisi_ddr_secprotect.o
obj-$(CONFIG_DDR_AUTO_FSGT) += ddr_autofsgt_proxy_kernel.o
obj-$(CONFIG_HISI_DDR_PERF_CTRL) += ddr_perf_ctrl.o
subdir-ccflags-$(CONFIG_HISI_BB) += 	-Idrivers/hisi/mntn/blackbox

