/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019.
 * All rights reserved.
 * Description: hisi sub pmic vibrator head File.
 * Author: hisilicon
 * Create: 2019-10-10
 */

#ifndef _HISI_PMIC_VIBRATOR_HI6423_H
#define _HISI_PMIC_VIBRATOR_HI6423_H

#define HISI_PMIC_VIBRATOR_DEFAULT_NAME "vibrator"
#define HISI_PMIC_VIBRATOR_CDEVIE_NAME "haptics"
#define HISI_PMIC_VIBRATOR_HAPTIC_CFG_STR "haptics-cfg"

#define HISI_PMIC_VIBRATOR_CLK_GATE 0x4E

#define HISI_PMIC_VIBRATOR_ON 0x1000
#define HISI_PMIC_VIBRATOR_BRAKE 0x1001

#define HISI_PMIC_VIBRATOR_DUTY_NORMAL_CFG_L 0x1010
#define HISI_PMIC_VIBRATOR_DUTY_NORMAL_CFG_H 0x1011

#define HISI_PMIC_VIBRATOR_OUT_NML_VBEMF_L 0x1041
#define HISI_PMIC_VIBRATOR_OUT_NML_VBEMF_H 0x1042
#define HISI_PMIC_VIBRATOR_UREAL_DATA_L 0x1045
#define HISI_PMIC_VIBRATOR_UREAL_DATA_H 0x1046
#define HISI_PMIC_VIBRATOR_ADC_ZERO_L 0x104B
#define HISI_PMIC_VIBRATOR_ADC_ZERO_H 0x104C
#define HISI_PMIC_VIBRATOR_KFIT_DATA_L 0x104D
#define HISI_PMIC_VIBRATOR_KFIT_DATA_H 0x104E
#define HISI_PMIC_VIBRATOR_LRA_NML_TIME_L 0x10AF
#define HISI_PMIC_VIBRATOR_LRA_NML_TIME_M 0x10B0
#define HISI_PMIC_VIBRATOR_LRA_NML_TIME_H 0x10B1
#define HISI_PMIC_VIBRATOR_LRA_NML_BEML_L 0x10B2
#define HISI_PMIC_VIBRATOR_LRA_NML_BEML_H 0x10B3

#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG0 0x1050
#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG6 0x1056
#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG_NUM 4
#define HISI_PMIC_VIBRATOR_LADD_PARA_REG 0x102B
#define HISI_PMIC_VIBRATOR_LADD_PARA_REG_NUM 20
#define HISI_PMIC_VIBRATOR_SPEL_DUTY_REG 0x1065
#define HISI_PMIC_VIBRATOR_REG_CFG_NUM HISI_PMIC_VIBRATOR_LADD_PARA_REG_NUM

#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG2 0x1052
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE2_6 0x2A
#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG3 0x1053
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE3_6 0x23
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE3_8 0x2E
#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG4 0x1054
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE4_8 0x23
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE4_10 0x30
#define HISI_PMIC_VIBRATOR_SPEL_TIME_REG5 0x1055
#define HISI_PMIC_VIBRATOR_SPEL_TIME_VALUE5_10 0x23
#define HISI_PMIC_VIBRATOR_HAPTIC_NUM 10
#define HISI_PMIC_VIBRATOR_HAPTIC_1 1
#define HISI_PMIC_VIBRATOR_HAPTIC_2 2
#define HISI_PMIC_VIBRATOR_HAPTIC_3 3
#define HISI_PMIC_VIBRATOR_HAPTIC_4 4
#define HISI_PMIC_VIBRATOR_HAPTIC_5 5

#define HISI_PMIC_VIBRATOR_LRA_ANA_CFG2 0x108F
#define HISI_PMIC_VIBRATOR_LRA_ANA_VALUE 0x0

#define HISI_PMIC_VIBRATOR_MODE_STANDBY 0x00
#define HISI_PMIC_VIBRATOR_MODE_RTP 0x01
#define HISI_PMIC_VIBRATOR_MODE_HAPTICS 0x02
#define HISI_PMIC_VIBRATOR_BRK_EN 0x01

#define HISI_PMIC_VIBRATOR_OVDR_DUTY_L 0x100D
#define HISI_PMIC_VIBRATOR_OVDR_DUTY_H 0x100E

#define HISI_PMIC_VIBRATOR_TH_BOOST_L 0x101A
#define HISI_PMIC_VIBRATOR_TH_BOOST_H 0x101B

#define HISI_PMIC_VIBRATOR_DRV_NMU 0x1002
#define HISI_PMIC_VIBRATOR_DRV_NUM_VALUE 0x94

#define HISI_PMIC_VIBRATOR_BRAKE_DUTY_L 0x1013
#define HISI_PMIC_VIBRATOR_BRAKE_DUTY_H 0x1014

#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE1_L 0x101C
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE1_VALUE_L 0xA0
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE1_H 0x101D
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE1_VALUE_H 0x0
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE2_L 0x101E
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE2_VALUE_L 0x60
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE2_H 0x101F
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE2_VALUE_H 0x0
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE3_L 0x1020
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE3_VALUE_L 0x20
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE3_H 0x1021
#define HISI_PMIC_VIBRATOR_GATE_VOLTAGE3_VALUE_H 0x0
#define HISI_PMIC_VIBRATOR_STATUS 0x104F

#define OVDR_DUTY_A 94060
#define OVDR_DUTY_B 35914000

#define TH_BOOST_A 273147
#define TH_BOOST_B 371927000

#define BRAKE_DUTY_A 135169
#define BRAKE_DUTY_B 40406000

#define LRA_NML_TIME 0x411
#define LRA_CYCLE_NUM 0x10
#define LRA_TIME_NUM 0x3D090
#define LRA_TIME_NUM1 0x61A8
#define LRA_HAPTIC_NUM 0xA
#define LRA_HAPTIC_NUM1 0x5
#define LRA_DEFAULT_FREQ 0x4FC97

#define PMIC_VIBRATOR_BRAKE_TIME_OUT 100
#define POWER_USED_BOOST_5V 1
#define POWER_NOTUSED_BOOST_5V 0
#define PMIC_VIBRATOR_POWER_ON 1
#define PMIC_VIBRATOR_POWER_OFF 0
#define LED_VIBRATOR_OFF 0

#define PMIC_VIBRATOR_FREQ_MAX 0x53554
#define PMIC_VIBRATOR_FREQ_MIN 0x4C87C

#define DUTY_NUM 240
#define VOLTAGE_NUM 3200

#define PMIC_VIBRATOR_HAP_BUF_LENGTH 16
#define PMIC_VIBRATOR_VOL_LEVEL_1 1
#define PMIC_VIBRATOR_VOL_LEVEL_10 10
#define PMIC_VIBRATOR_VOL_LEVEL_16 16
#define PMIC_VIBRATOR_STRENGTH_STEP1 200 // 200mv
#define PMIC_VIBRATOR_STRENGTH_STEP2 500 // 500mv

#define HISI_PMIC_VIBRATOR_IRQ_COUNTS 5

/* ERM REG */
#define HISI_PMIC_VIBRATOR_ERM_LOCK              0x10BC
#define HISI_PMIC_VIBRATOR_ERM_MODE_CFG          0x10BD
#define HISI_PMIC_VIBRATOR_FRQC_SEL_CFG          0x10BE
#define HISI_PMIC_VIBRATOR_ERM_DUTY_OVDR_CFG_L   0x10BF
#define HISI_PMIC_VIBRATOR_ERM_DUTY_OVDR_CFG_H   0x10C0
#define HISI_PMIC_VIBRATOR_ERM_DUTY_NML_CFG_L    0x10C1
#define HISI_PMIC_VIBRATOR_ERM_DUTY_NML_CFG_H    0x10C2
#define HISI_PMIC_VIBRATOR_ERM_DUTY_BRK_CFG_L    0x10C3
#define HISI_PMIC_VIBRATOR_ERM_DUTY_BRK_CFG_H    0x10C4

#define ERM_OVDR_VAL_L     0x0
#define ERM_OVDR_VAL_H     0x8
#define ERM_BREAK_VAL_L    0x40
#define ERM_BREAK_VAL_H    0x6

#define ERM_UNLOCK             0x7D
#define ERM_MODE_CLOSE_LOOP    0x1
#define ERM_MODE_NO_SAMPL      0x2
#define ERM_MODE_OPEN_LOOP     0x3
#define ERM_PWM_150K      0x0
#define ERM_PWM_300K      0x1
#define ERM_PWM_600K      0x2
#define ERM_PWM_1200K     0x3

#define ERM_DUTY_NUM      128
#define ERM_VOLTAGE_IN    5000

#define HISI_VIBRATOR_TIMEOUT_MIN 50
#define VIBRATOR_TIMEOUT_MIN_SIZE 16

/* for duty change */
#define HISI_PMIC_WEAK_TYPE_DEFULT 0
#define HISI_PMIC_STRENGTH_DEFULT 1400
#define HISI_PMIC_WEAK_TYPE_1 -1
#define HISI_PMIC_WEAK_STRENGTH_1 800
#define HISI_PMIC_WEAK_TYPE_2 -2
#define HISI_PMIC_WEAK_STRENGTH_2 600

#ifndef UNUSED
#define UNUSED(x) (void)(x)
#endif
#endif
