#
# Makefile for the memory technology device drivers.
#
# Core functionality.
ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif
obj-y				+= dump_core.o 
obj-y				+= dump_exc_handle.o 
obj-y				+= dump_boot_check.o 
