# Hisilicon IPP Makefile
ccflags-$(CONFIG_HISPIPP_V200) += -Idrivers/hisi/ipp/v200
ccflags-$(CONFIG_HISPIPP_V210) += -Idrivers/hisi/ipp/v210
ccflags-$(CONFIG_HISPIPP_V300) += -Idrivers/hisi/ipp/v300
ccflags-$(CONFIG_HISPIPP_V250) += -Idrivers/hisi/ipp/v250
ccflags-$(CONFIG_HISPIPP_V350) += -Idrivers/hisi/ipp/v350
obj-$(CONFIG_HISPIPP_V200) += v200/
obj-$(CONFIG_HISPIPP_V210) += v210/
obj-$(CONFIG_HISPIPP_V300) += v300/
obj-$(CONFIG_HISPIPP_V250) += v250/
obj-$(CONFIG_HISPIPP_V350) += v350/
