# Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
# Description: Makefile for the Huawei kshield
# Author: ducuixia <ducuixia@huawei.com>
# Create: 2019-11-09

obj-$(CONFIG_SECURITY_KSHIELD) += event.o
obj-$(CONFIG_SECURITY_KSHIELD) += kshield.o
obj-$(CONFIG_SECURITY_KSHIELD) += hook_exp.o
obj-$(CONFIG_SECURITY_KSHIELD) += hook_sock_spray.o
obj-$(CONFIG_SECURITY_KSHIELD) += hook_charact.o
obj-$(CONFIG_SECURITY_KSHIELD) += hook_spray.o
obj-$(CONFIG_SECURITY_KSHIELD) += dev.o
