
ccflags-y  += -I$(srctree)/drivers/contexthub/



obj-$(CONFIG_SENSOR_CHANNEL) += sensor_channel.o
obj-$(CONFIG_SENSOR_CHANNEL) += sensor_feima.o
obj-$(CONFIG_SENSOR_CHANNEL) += sensor_sysfs.o
obj-$(CONFIG_SENSOR_CHANNEL) += acc_feima_demo.o
obj-$(CONFIG_CTXHUB_AS_GYRO) += gyro_feima.o
obj-$(CONFIG_CTXHUB_AS_AR) += ar_feima.o
obj-$(CONFIG_CTXHUB_AS_AR) += ar.o
obj-$(CONFIG_CTXHUB_AS_PEDOMETER) += pedometer.o
obj-$(CONFIG_CTXHUB_AS_PEDOMETER) += pedo_feima.o
