obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_dts.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_rx.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_tx.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_fw.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_qi.o
obj-$(CONFIG_WIRELESS_STWLC88) += stwlc88_hw_test.o
