obj-$(CONFIG_PHY_HI6220_USB)		+= phy-hi6220-usb.o
obj-$(CONFIG_PHY_HIX5HD2_SATA)		+= phy-hix5hd2-sata.o
obj-$(CONFIG_PHY_PLAT_MAY_USB2)		+= phy-plat-may-usb2.o
obj-$(CONFIG_PHY_HISI_COMBOPHY)		+= phy-hisi-combophy.o hisi-combophy-mcu.o
