# huawei audio driver

obj-$(CONFIG_ANA_HS_EXTERN_OPS) += ana_hs_extern_ops/
obj-$(CONFIG_ANC_HS_MODULE) += anc_hs_module/
obj-$(CONFIG_INVERT_HS) += invert_hs/
obj-$(CONFIG_AK4376) += ak4376/
obj-$(CONFIG_HIFI_VIR_DAI) += hifi_vir_dai/
obj-$(CONFIG_USB_ANALOG_HS_MODULE) += usb_analog_hs_module/
obj-$(CONFIG_DIG_HS_MODULE) += dig_hs_module/
obj-$(CONFIG_USB_AUDIO_POWER) += usb_audio_power/
obj-$(CONFIG_USB_AUDIO_COMMON) += usb_audio_common/
obj-$(CONFIG_USB_AUDIO_POWER_V600) += usb_audio_power_v600/
obj-$(CONFIG_USB_AUDIO_POWER) += usb_headset_core/
obj-$(CONFIG_HIGH_RESISTANCE_HS_DET) += high_resistance_hs_det/
obj-y += tf_agent/
obj-$(CONFIG_VIRTUAL_VOICE_PROXY) += virtual_voice_proxy/
obj-$(CONFIG_CODEC_CHECK) += codec_check/
