/* Copyright (c) 2018-2019, Hisilicon Tech. Co., Ltd. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include "hisi_drm_dss_global.h"

/* number of smrx idx for each channel */
const uint32_t g_dss_chn_sid_num[DSS_CHN_MAX_DEFINE] = {
	4, 1, 4, 4, 4, 4, 1, 1, 3, 4, 3, 3
};

/* start idx of each channel */
/* smrx_idx = g_dss_smmu_smrx_idx[chn_idx] + (0 ~ g_dss_chn_sid_num[chn_idx]) */
const uint32_t g_dss_smmu_smrx_idx[DSS_CHN_MAX_DEFINE] = {
	0, 4, 5, 9, 13, 17, 21, 22, 26, 29, 23, 36
};

const uint32_t g_dss_module_ovl_base[DSS_MCTL_IDX_MAX][MODULE_OVL_MAX] = {
	{DSS_OVL0_OFFSET, DSS_MCTRL_CTL0_OFFSET},
	{DSS_OVL1_OFFSET, DSS_MCTRL_CTL1_OFFSET},
	{DSS_OVL2_OFFSET, DSS_MCTRL_CTL2_OFFSET},
	{DSS_OVL3_OFFSET, DSS_MCTRL_CTL3_OFFSET},
	{0, DSS_MCTRL_CTL4_OFFSET},
	{0, DSS_MCTRL_CTL5_OFFSET},
};

const uint32_t g_dss_module_base[DSS_CHN_MAX_DEFINE][MODULE_CHN_MAX] = {
	// D0
	{
		MIF_CH0_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH0_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH0_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH0,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH0_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH0_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH0_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD0_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_D0_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_D0_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_D0_CSC_OFFSET,  //MODULE_CSC
	},

	// D1
	{
		MIF_CH1_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH1_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH1_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH1,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH1_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH1_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH1_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD1_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_D1_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_D1_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_D1_CSC_OFFSET,  //MODULE_CSC
	},

	// V0
	{
		MIF_CH2_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH2_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH2_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH2,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH2_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH2_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH2_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD2_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_VG0_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_VG0_DFC_OFFSET,  //MODULE_DFC
		DSS_RCH_VG0_SCL_OFFSET,  //MODULE_SCL
		DSS_RCH_VG0_SCL_LUT_OFFSET,  //MODULE_SCL_LUT
		DSS_RCH_VG0_ARSR_OFFSET,  //MODULE_ARSR2P
		DSS_RCH_VG0_ARSR_LUT_OFFSET,  //MODULE_ARSR2P_LUT
		DSS_RCH_VG0_POST_CLIP_OFFSET,  //MODULE_POST_CLIP
		DSS_RCH_VG0_PCSC_OFFSET,  //MODULE_PCSC
		DSS_RCH_VG0_CSC_OFFSET,  //MODULE_CSC
	},

	// G0
	{
		MIF_CH3_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH3_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH3_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH3,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH3_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH3_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH3_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD3_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_G0_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_G0_DFC_OFFSET,  //MODULE_DFC
		DSS_RCH_G0_SCL_OFFSET,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		DSS_RCH_G0_POST_CLIP_OFFSET,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_G0_CSC_OFFSET,  //MODULE_CSC
	},

	// V1
	{
		MIF_CH4_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH4_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH4_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH4,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH4_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH4_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH4_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD4_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_VG1_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_VG1_DFC_OFFSET,  //MODULE_DFC
		DSS_RCH_VG1_SCL_OFFSET,  //MODULE_SCL
		DSS_RCH_VG1_SCL_LUT_OFFSET,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		DSS_RCH_VG1_POST_CLIP_OFFSET,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_VG1_CSC_OFFSET,  //MODULE_CSC
	},

	// G1
	{
		MIF_CH5_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH5_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH5_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH5,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH5_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH5_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH5_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD5_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_G1_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_G1_DFC_OFFSET,  //MODULE_DFC
		DSS_RCH_G1_SCL_OFFSET,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		DSS_RCH_G1_POST_CLIP_OFFSET,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_G1_CSC_OFFSET,  //MODULE_CSC
	},

	// D2
	{
		MIF_CH6_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH6_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH6_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH6,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH6_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH6_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH6_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD6_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_D2_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_D2_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_D2_CSC_OFFSET,  //MODULE_CSC
	},

	// D3
	{
		MIF_CH7_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH7_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH7_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH7,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH7_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH7_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH7_STARTY,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD7_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_D3_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_D3_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_D3_CSC_OFFSET,  //MODULE_CSC
	},

	// W0
	{
		MIF_CH8_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH8_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH8_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_WCH0,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_WCH0_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_WCH0_OV_IEN,  //MODULE_MCTL_CHN_OV_OEN
		0,  //MODULE_MCTL_CHN_STARTY
		0,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_WCH0_DMA_OFFSET,  //MODULE_DMA
		DSS_WCH0_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_WCH0_CSC_OFFSET,  //MODULE_CSC
	},

	// W1
	{
		MIF_CH9_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH9_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH9_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_WCH1,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_WCH1_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_WCH1_OV_IEN,  //MODULE_MCTL_CHN_OV_OEN
		0,  //MODULE_MCTL_CHN_STARTY
		0,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_WCH1_DMA_OFFSET,  //MODULE_DMA
		DSS_WCH1_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_WCH1_CSC_OFFSET,  //MODULE_CSC
	},

	// V2
	{
		MIF_CH10_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH11_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH11_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_RCH8,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH8_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		DSS_MCTRL_SYS_OFFSET + MCTL_RCH8_OV_OEN,  //MODULE_MCTL_CHN_OV_OEN
		0,  //MODULE_MCTL_CHN_STARTY
		DSS_MCTRL_SYS_OFFSET + MCTL_MOD8_DBG,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_RCH_VG2_DMA_OFFSET,  //MODULE_DMA
		DSS_RCH_VG2_DFC_OFFSET,  //MODULE_DFC
		DSS_RCH_VG2_SCL_OFFSET,  //MODULE_SCL
		DSS_RCH_VG2_SCL_LUT_OFFSET,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		DSS_RCH_VG2_POST_CLIP_OFFSET,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_RCH_VG2_CSC_OFFSET,  //MODULE_CSC
	},
	// W2
	{
		MIF_CH11_OFFSET,   //MODULE_MIF_CHN
		AIF0_CH12_OFFSET,  //MODULE_AIF0_CHN
		AIF1_CH12_OFFSET,  //MODULE_AIF1_CHN
		MCTL_CTL_MUTEX_WCH2,  //MODULE_MCTL_CHN_MUTEX
		DSS_MCTRL_SYS_OFFSET + MCTL_WCH2_FLUSH_EN,  //MODULE_MCTL_CHN_FLUSH_EN
		0,  //MODULE_MCTL_CHN_OV_OEN
		0,  //MODULE_MCTL_CHN_STARTY
		0,  //MODULE_MCTL_CHN_MOD_DBG
		DSS_WCH2_DMA_OFFSET,  //MODULE_DMA
		DSS_WCH2_DFC_OFFSET,  //MODULE_DFC
		0,  //MODULE_SCL
		0,  //MODULE_SCL_LUT
		0,  //MODULE_ARSR2P
		0,  //MODULE_ARSR2P_LUT
		0,  //MODULE_POST_CLIP
		0,  //MODULE_PCSC
		DSS_WCH2_CSC_OFFSET,  //MODULE_CSC
	},
};

bool check_yuv_planar(uint32_t format)
{
	switch (format) {
	case HISI_DSS_FORMAT_YCBCR422_P: // fall-through
	case HISI_DSS_FORMAT_YCRCB422_P: // fall-through
	case HISI_DSS_FORMAT_YCBCR420_P: // fall-through
	case HISI_DSS_FORMAT_YCRCB420_P: // fall-through
	case HISI_DSS_FORMAT_YCBCR420_P_10BIT: // fall-through
	case HISI_DSS_FORMAT_YCBCR422_P_10BIT:
		return true;

	default:
		return false;
	}
}

bool check_yuv_semi_planar(uint32_t format)
{
	switch (format) {
	case HISI_DSS_FORMAT_YCBCR422_SP: // fall-through
	case HISI_DSS_FORMAT_YCRCB422_SP: // fall-through
	case HISI_DSS_FORMAT_YCBCR420_SP: // fall-through
	case HISI_DSS_FORMAT_YCRCB420_SP: // fall-through
	case HISI_DSS_FORMAT_YCRCB420_SP_10BIT: // fall-through
	case HISI_DSS_FORMAT_YCBCR420_SP_10BIT: // fall-through
	case HISI_DSS_FORMAT_YCBCR422_SP_10BIT:
		return true;

	default:
		return false;
	}
}

/********************************** END **********************************************/
