

#ifndef DBV_CURVE_NOLINER_TO_LINER_MAP_H
#define DBV_CURVE_NOLINER_TO_LINER_MAP_H

#define DBV_MAP_TYPE_COUNT1 2
#define DBV_MAP_TYPE_COUNT2 3
#define DBV_MAP_10BIT  1024
#define DBV_MAP_12BIT 4096

#endif
