#
# Makefile for hisilicon camera buck driver
#
ccflags-y += -Idrivers/media/huawei/camera

obj-$(CONFIG_HUAWEI_CAMERA_BUCK) += hw_buck.o
obj-$(CONFIG_HUAWEI_CAMERA_BUCK) += fan53526.o
obj-$(CONFIG_HUAWEI_CAMERA_BUCK) += rt5748b.o
obj-$(CONFIG_HUAWEI_CAMERA_BUCK) += ktb8330.o