# Hisilicon IPP v300 Makefile

obj-$(CONFIG_HISPIPP_V300) += gf.o
obj-$(CONFIG_HISPIPP_V300) += orb.o
obj-$(CONFIG_HISPIPP_V300) += mc.o
obj-$(CONFIG_HISPIPP_V300) += vbk.o
obj-$(CONFIG_HISPIPP_V300) += reorder.o
obj-$(CONFIG_HISPIPP_V300) += compare.o
obj-$(CONFIG_HISPIPP_V300) += orb_enh.o

