#ifndef __SOC_SOCP_ADAPTER_H__
#define __SOC_SOCP_ADAPTER_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#define SOCP_BBA_RFIC0_RPTR_IMAGE_ADDR 0xff9841b8
#define SOCP_BBA_RFIC1_RPTR_IMAGE_ADDR 0xff984208
#define SOCP_BASEADDR_ESL_EMU_HYBRID 0xe38d8000
#define SOC_SOCP_CODER_SRC_CHAN 0x00
#define SOC_SOCP_CHAN_DEF(chan_type,chan_id) ((chan_type<<16)|chan_id)
enum SOCP_CODER_SRC_ENUM
{
    SOCP_CODER_SRC_ACPU_CNF = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,0),
    SOCP_CODER_SRC_ACPU_MDM_BSP_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,1),
    SOCP_CODER_SRC_ACPU_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,2),
    SOCP_CODER_SRC_ACPU_USER_MODE_APP_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,3),
    SOCP_CODER_SRC_ACPU_AP_BSP_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,4),
    SOCP_CODER_SRC_ACPU_TEE_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,5),
    SOCP_CODER_SRC_LPM3_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,6),
    SOCP_CODER_SRC_HIFI_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,7),
    SOCP_CODER_SRC_CCPU_CNF = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,8),
    SOCP_CODER_SRC_CCPU_BSP_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,9),
    SOCP_CODER_SRC_CCPU_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,10),
    SOCP_CODER_SRC_GUDSP1 = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,11),
    SOCP_CODER_SRC_GUDSP2 = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,12),
    SOCP_CODER_SRC_GC_SDR_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,13),
    SOCP_CODER_SRC_TLPHY_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,14),
    SOCP_CODER_SRC_LTEVPHY_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,15),
    SOCP_CODER_SRC_BBP_LOG = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,16),
    SOCP_CODER_SRC_BBP_DS = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,17),
    SOCP_CODER_SRC_EASYRF0_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,18),
    SOCP_CODER_SRC_5G_CCPU_CNF = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,19),
    SOCP_CODER_SRC_5G_CCPU_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,20),
    SOCP_CODER_SRC_5G_CCPU_BSP_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,21),
    SOCP_CODER_SRC_5G_HL1C_0_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,22),
    SOCP_CODER_SRC_5G_HL1C_1_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,23),
    SOCP_CODER_SRC_5G_L2HAC_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,24),
    SOCP_CODER_SRC_LL1C_CORE0_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,25),
    SOCP_CODER_SRC_LL1C_CORE1_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,26),
    SOCP_CODER_SRC_LL1C_CORE2_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,27),
    SOCP_CODER_SRC_LL1C_CORE3_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,28),
    SOCP_CODER_SRC_LL1C_CORE4_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,29),
    SOCP_CODER_SRC_LL1C_CORE5_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,30),
    SOCP_CODER_SRC_SDR_CORE0_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,31),
    SOCP_CODER_SRC_SDR_CORE1_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,32),
    SOCP_CODER_SRC_SDR_CORE2_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,33),
    SOCP_CODER_SRC_SDR_CORE3_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,34),
    SOCP_CODER_SRC_5G_BBP_BUS = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,35),
    SOCP_CODER_SRC_5G_BBP_DATA = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,36),
    SOCP_CODER_SRC_BBP_RFIC0_BUS = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,37),
    SOCP_CODER_SRC_BBP_RFIC1_BUS = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,38),
    SOCP_CODER_SRC_BBP_ACCESS_DATA = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,39),
    SOCP_CODER_SRC_EASYRF1_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,40),
    SOCP_CODER_SRC_PDE0_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,41),
    SOCP_CODER_SRC_PDE1_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,42),
    SOCP_CODER_SRC_PDE2_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,43),
    SOCP_CODER_SRC_PDE3_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,44),
    SOCP_CODER_SRC_PDE4_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,45),
    SOCP_CODER_SRC_PDE5_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,46),
    SOCP_CODER_SRC_LOG_SERVER = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,47),
    SOCP_CODER_SRC_5G_LOG_SERVER = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,48),
    SOCP_CODER_SRC_AP_HIFI_IND = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,49),
    SOCP_CODER_SRC_BUTT = SOC_SOCP_CHAN_DEF(SOC_SOCP_CODER_SRC_CHAN,64)
};
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
