
obj-$(CONFIG_HISI_THERMAL_TSENSOR)	+= hisi_tsens.o
obj-$(CONFIG_HISI_THERMAL_PERIPHERAL)	+= hisi_peripheral_tm.o hisi_ntc_tm_table.o
obj-$(CONFIG_HISI_IPA_THERMAL)	+= hisi_ipa_thermal.o
obj-$(CONFIG_HISI_IPA_THERMAL)	+= board_cooling.o
obj-$(CONFIG_HISI_THERMAL_SHELL) += hisi_shell_temp.o
obj-$(CONFIG_HISI_THERMAL_AMBIENT) += hisi_ambient_temp.o
obj-$(CONFIG_HISI_HKADC_MODEM) += modem_hkadc_temp.o
obj-$(CONFIG_HISI_ITS) += its.o
obj-$(CONFIG_HISI_THERMAL_NPU) += hisi_npu_thermal.o
obj-$(CONFIG_HISI_PERF_CTRL) += thermal_perf_ctrl.o
obj-y += hw_dpm/
