#
# Makefile for hisilicon camera vcm driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/sensor/vcm
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -Idrivers/media/huawei/cci/
EXTRA_CFLAGS += -fno-pic

obj-y += hwvcm.o
