obj-$(CONFIG_HISI_ENABLE_GET_VAL) += cpufreq_get_volt.o
obj-$(CONFIG_HISI_CPUFREQ_DT)	+= hisi_cpufreq_dt.o
obj-$(CONFIG_HISI_FREQ_LINK)	+= hisi_cpuddr_freq_link.o
obj-$(CONFIG_HISI_CPUFREQ_LOWTEMP)	+= hisi_cpufreq_lowtemp.o
obj-$(CONFIG_HISI_FREQ_STATS_COUNTING_IDLE) += time_in_state.o
