ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform
obj-$(CONFIG_HUAWEI_CAMERA_USE_CAMKIT) += hisensor.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_CAMKIT) += tofsensor.o

