ccflags-y  += -I$(srctree)/drivers/contexthub/
ccflags-y  += -I$(srctree)/drivers/contexthub/inputhub_as

obj-$(CONFIG_INPUTHUB_AS) += device_common.o
obj-$(CONFIG_CONTEXTHUB_DEVICE_DEMO) += acc_device_demo.o
obj-$(CONFIG_CONTEXTHUB_DEVICE_GYRO) += gyro_device.o
obj-$(CONFIG_CONTEXTHUB_DEVICE_DEMO) += airpress_device_demo.o
obj-$(CONFIG_CONTEXTHUB_DEVICE_DEMO) += connectivity_device_demo.o
obj-$(CONFIG_FINGERPRINT_CHANNEL) += fingerprint_device_demo.o
