ccflags-y += -Wall -Werror
EXTRA_CFLAGS += -Idrivers/hisi/mntn/blackbox/
EXTRA_CFLAGS += -Idrivers/hisi/load_image/
EXTRA_CFLAGS += -Idrivers/hisi/hifi_mailbox/mailbox/
EXTRA_CFLAGS += -Idrivers/hisi/hifi_dsp/

obj-$(CONFIG_HISI_AP_CP_DECOUPL) += modem_symbol.o

