obj-$(CONFIG_HUAWEI_BATTERY_TYPE_IDENTIFY) += battery_type_identify/
obj-$(CONFIG_HUAWEI_BATTERY_INFORMATION) += battery_ct/
obj-$(CONFIG_HUAWEI_BATTERY_VOLTAGE) += battery_voltage/
obj-$(CONFIG_HUAWEI_BATTERY_TEMP) += battery_temp/
obj-$(CONFIG_HUAWEI_BATTERY_TEMP_FITTING) += battery_temp_fitting/
obj-$(CONFIG_HUAWEI_BATTERY_CAPACITY) += battery_capacity/
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_soh/