obj-$(CONFIG_WIRELESS_CHARGER) += wireless_sc.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_direct_charge.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_dc_error_handle.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_dc_ic.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_dc_cp.o