obj-y += wireless.o

obj-$(CONFIG_WIRELESS_CHARGER) += wireless_test/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_firmware/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_reverse_charge/
obj-$(CONFIG_WIRELESS_PROTOCOL) += wireless_protocol/
obj-$(CONFIG_WIRELESS_ALIGNMENT_DETECT) += wireless_alignment_detect/
