obj-$(CONFIG_HISI_DEVFREQ)      += hisi_devfreq.o
obj-y += ddr_devfreq/
obj-y += gpu_devfreq/
obj-y += npu_devfreq/
obj-y += mem_lat/
obj-$(CONFIG_ARM64_DSU_PCTRL_DEVFREQ)      += dsu_pctrl/
obj-$(CONFIG_HISI_L3C_DEVFREQ)      	   += l3c_devfreq/
