#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_baseinfo.o
obj-y				+= dump_mdmap_core.o
obj-y				+= dump_area.o 
obj-y				+= dump_hook.o