OAMDIR = ..

MODEM_DIR := $(srctree)/drivers/hisi/modem
-include $(MODEM_DIR)/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/balong_product_config.mk

ifeq ($(TARGET_ARM_TYPE), arm64)
EXTRA_CFLAGS += -Iarch/arm64/include/asm
else
EXTRA_CFLAGS += -Iarch/arm/include/asm
endif
EXTRA_CFLAGS += -Iinclude/linux
EXTRA_CFLAGS += -Iinclude/generated
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/nvim/include/gu/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/osa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/errlog/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/nvim/include/lt/tlps/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/
EXTRA_CFLAGS += -I$(MODEM_DIR)/config/product/$(OBB_PRODUCT_NAME)/include/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/drv/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/drv/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/med/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/acore/cbtcpm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/comm/osa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/scm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/comm/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/socp/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/comm/usimm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/gu/hpa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/oam/lt/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/phy/wphy/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/gups/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/gups/ccore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/gups/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/tlps/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/tlps/ccore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/tlps/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/ps/nas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/taf/acore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/taf/ccore/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/taf/common/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/tag/apss/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/tag/cpss/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/tools/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/common/pam/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/common/msp/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/common/guc_nas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/common/guc_as/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/acore/guc_nas/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/tool/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/ttf/
EXTRA_CFLAGS += -I$(MODEM_DIR)/include/nv/gu/was/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/acore/dms/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/ccore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/acore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/usimm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/ccore/xml/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/comm/comm/ppm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/si/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/pih/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtcpm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtppm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtfun/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/acore/cbtscm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/hpa/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/om/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/pstool/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/ccore/sc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/om/
#lt only INC
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/gu/comm/sc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/list/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/acore/diag/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/drx/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/cfg/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/diag/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/ipc/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/nvim/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/sdm/
EXTRA_CFLAGS += -I$(MODEM_DIR)/oam/inc/lt/comm/type/

EXTRA_CFLAGS += -I$(MODEM_DIR)/tafnew/acore/at/inc/

EXTRA_CFLAGS += -DVOS_LINUX=4 -DOSA_CPU_ACPU=1 -DVOS_OS_VER=VOS_LINUX -DVOS_OSA_CPU=OSA_CPU_ACPU -DVOS_DOPRA_VER=2 -DNDIS_RELEASE -DMSP_GUNAS_AT_UNITE

ifneq ($(TARGET_ARM_TYPE), arm64)
EXTRA_CFLAGS += -D__LINUX_ARM_ARCH__=7 -march=armv7-a -Uarm
endif

EXTRA_CFLAGS += -DPRODUCT_CFG_MULTIMODE_LTE -DHAL_DIAG_SDM_USE

EXTRA_CFLAGS += -fsigned-char
ifneq ($(CONFIG_M533_HINGDFE_SEPARATE),y)
gumsp-objs += $(OAMDIR)/gu/acore/usimm/usimm_app_base.o
gumsp-objs += $(OAMDIR)/gu/acore/si/pcsc_proc.o
gumsp-objs += $(OAMDIR)/gu/acore/si/si_acore_api.o
gumsp-objs += $(OAMDIR)/gu/acore/stk/stk_external_api.o
gumsp-objs += $(OAMDIR)/gu/acore/pih/pih_external_api.o
gumsp-objs += $(OAMDIR)/gu/acore/emat/emat_external_api.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pb_api.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pb_msg.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pb_data.o
gumsp-objs += $(OAMDIR)/gu/comm/si/pb_api_phone.o
else
gumsp-objs += $(OAMDIR)/gu/acore/cbtfun/g200_stub.o
endif

gumsp-objs += $(OAMDIR)/gu/acore/om/pam_app_om.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtcpm/cbt_cpm.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtppm/cbt_ppm.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtscm/cbt_scm_soft_decode.o
gumsp-objs += $(OAMDIR)/gu/acore/cbtfun/cbt_app_function.o
gumsp-objs += $(OAMDIR)/gu/acore/osa/linux_sem.o
gumsp-objs += $(OAMDIR)/gu/acore/osa/linux_task.o
gumsp-objs += $(OAMDIR)/gu/comm/om/om_ring_buffer.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_blk_mem.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_private.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_int.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/rtc_timer.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_queue.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_timer.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_msg.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_lib.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/vos_id.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/vos_main.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_nsprintf.o
gumsp-objs += $(OAMDIR)/gu/comm/osa/v_sprintf.o



ifneq ($(strip $(CONFIG_HISI_BALONG_MODEM)),m)
obj-y  := gumsp.o
endif


