obj-y := media_dfx.o
media_dfx-objs := \
	mdfx_actor.o \
	mdfx.o \
	mdfx_dumper.o \
	mdfx_event.o \
	mdfx_file.o \
	mdfx_logger.o \
	mdfx_saver.o \
	mdfx_tracing.o \
	mdfx_utils.o \
	mdfx_visitor.o \
	mdfx_debug.o

clean:
	rm *.o .*cmd

