obj-$(CONFIG_HISI_MODULE_ALLOC) += hhee_module.o
obj-$(CONFIG_HISI_HHEE)	 += hhee_log.o hhee_dev.o hhee_msg.o
obj-$(CONFIG_HISI_HHEE)		+= hkip/
obj-$(CONFIG_HISI_HHEE_DEBUG) += hhee_debugfs.o
obj-y += mm/
