ccflags-y += -I$(srctree)/drivers/block/zram
obj-y += hyperhold_core.o hyperhold_manager.o hyperhold_schedule.o hyperhold_list.o hyperhold_area.o hyperhold_perf.o hyperhold_stats.o hyperhold_ctrl.o hyperhold_lru_rmap.o
