#
# Copyright (c) Huawei Technologies Co., Ltd. 2014-2020. All rights reserved.
# Description: This file describe HISI GPU hardware related features
# Author: Huawei Technologies Co., Ltd.
# Create: 2014-2-24
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

# Compile the hisilicon last buffer implementation.
include $(src)/$(MALI_PLATFORM_DIR)/base/lb/Kbuild

# Compile the hisilicon memory group manager implementation.
include $(src)/$(MALI_PLATFORM_DIR)/base/mgm/Kbuild
