# Hisilicon IPP modules Makefile

obj-$(CONFIG_HISPIPP_V350) += anf_drv.o
obj-$(CONFIG_HISPIPP_V350) += arfeature_drv.o
obj-$(CONFIG_HISPIPP_V350) += cmdlst_drv.o
obj-$(CONFIG_HISPIPP_V350) += compare_drv.o
obj-$(CONFIG_HISPIPP_V350) += cvdr_drv.o
obj-$(CONFIG_HISPIPP_V350) += cvdr_opt.o
obj-$(CONFIG_HISPIPP_V350) += gf_drv.o
obj-$(CONFIG_HISPIPP_V350) += hiof_drv.o
obj-$(CONFIG_HISPIPP_V350) += mc_drv.o
obj-$(CONFIG_HISPIPP_V350) += orb_enh_drv.o
obj-$(CONFIG_HISPIPP_V350) += reorder_drv.o
obj-$(CONFIG_HISPIPP_V350) += tof_drv.o

