

#ifndef __HISI_CUSTOMIZE_WIFI_HI110X_H__
#define __HISI_CUSTOMIZE_WIFI_HI110X_H__

#if defined(_PRE_PRODUCT_ID_HI110X_HOST)

/* 其他头文件包含 */
#include "mac_vap.h"
#include "hisi_customize_wifi_hi1106.h"

/* 宏定义 */
#define NVRAM_PARAMS_ARRAY "nvram_params"

#define MAC_LEN                     6
#define NV_WLAN_NUM                 193
#define NV_WLAN_VALID_SIZE          12
#define ini_mac2str(a)                  (a)[0], "**", "**", "**", (a)[4], (a)[5]
#define MACFMT                      "%02x:%s:%s:%s:%02x:%02x"
#define ini_mac2str_all(a)              (a)[0], (a)[1], (a)[2], (a)[3], (a)[4], (a)[5]
#define MACFMT_ALL                  "%02x:%02x:%02x:%02x:%02x:%02x"
#define CUS_TAG_INI                 0x11
#define CUS_TAG_DTS                 0x12
#define CUS_TAG_NV                  0x13
#define CUS_TAG_PRIV_INI            0x14
#define CUS_TAG_PRO_LINE_INI        0x15
#define CALI_TXPWR_PA_DC_REF_MIN    1000
#define CALI_TXPWR_PA_DC_REF_MAX    0x8000
#define CALI_TXPWR_PA_DC_FRE_MIN    0
#define CALI_TXPWR_PA_DC_FRE_MAX    78
#define CALI_BT_TXPWR_PA_DC_REF_MAX 15000
#define RF_LINE_TXRX_GAIN_DB_2G_MIN (-100)
#define RF_LINE_TXRX_GAIN_DB_MAX     40
#define RF_LINE_TXRX_GAIN_DB_5G_MIN (-48)
#define PSD_THRESHOLD_MIN           (-15)
#define PSD_THRESHOLD_MAX           (-10)
#define LNA_GAIN_DB_MIN             (-40)
#define LNA_GAIN_DB_MAX             80

/* NVRAM中存储的参数值的总个数，包括4个基准功率 */
#define NUM_OF_NV_PARAMS (NUM_OF_NV_MAX_TXPOWER + NUM_OF_NV_DPD_MAX_TXPOWER + \
                          NUM_OF_NV_11B_DELTA_TXPOWER + NUM_OF_NV_5G_UPPER_UPC + 4)
#define TX_RATIO_MAX                    2000 /* tx占空比的最大有效值 */
#define TX_PWR_COMP_VAL_MAX             50   /* 发射功率补偿值的最大有效值 */
#define MORE_PWR_MAX                    50   /* 根据温度额外补偿的发射功率的最大有效值 */
#define COUNTRY_CODE_LEN                3    /* 国家码位数 */
#define MAX_COUNTRY_COUNT               300  /* 支持定制的国家的最大个数 */
#define DELTA_CCA_ED_HIGH_TH_RANGE      25
#define CUS_NUM_5G_BW                   4    /* 定制化5g带宽数 */
#define CUS_NUM_FCC_CE_2G_PRO           3    /* 定制化2g FCC/CE 11B+OFDM_20M+OFDM_40M */
#define CUS_NUM_5G_20M_SIDE_BAND        6    /* 定制化5g边带数 */
#define CUS_NUM_5G_40M_SIDE_BAND        6
#define CUS_NUM_5G_80M_SIDE_BAND        5
#define CUS_NUM_5G_160M_SIDE_BAND       2
#define CUS_NUM_OF_SAR_PARAMS           8  /* 定制化降SAR参数 5G_BAND1~7 2.4G */
#define CUS_NUM_OF_SAR_PER_BAND_PAR_NUM 5  /* 每个band降SAR定制项数 */
#define CUS_NUM_OF_SAR_LVL              20 /* 定制化降SAR档位数 */
#define CUS_NUM_OF_SAR_ONE_PARAM_NUM    4

#define PRO_LINE_2G_TO_5G_OFFSET        2 /* 定制化读取的顺序和底层解析的顺序差异导致 */

/* 同device侧定义 */
#define WLAN_DEV_ALL_ENABLE             1 /* 平台开低功耗+业务控rf和mac pa */
#define WLAN_DEV_LIGHT_SLEEP_SWITCH_EN  4 /* 平台关深睡+业务控mac pa+rf常开 */

/* 这种情况每个level占有3个定义，所以每次偏移3 */
#define WLAN_CFG_ID_OFFSET              3

#define CUS_MIN_OF_SAR_VAL    0x28 /* 定制化降SAR最小值 4dbm */
#define CUS_PARAMS_LEN_MAX    104  /* 定制项最大长度 */
#define DY_2G_CALI_PARAMS_NUM 4    /* 动态校准参数个数,2.4g */

/* 动态校准参数个数,2.4g 4个(ofdm 20/40 11b cw),5g 5*2(high & low)个band,2.4g(ppa cw) */
#define DY_CALI_PARAMS_NUM        15
#define DY_CALI_PARAMS_BASE_NUM   9 /* 动态校准参数个数,2.4g 4个(ofdm 20/40 11b cw),5g 5(high)个band */
#define DY_CALI_PARAMS_TIMES      3 /* 动态校准参数二次项系数个数 */
#define DY_CALI_NUM_5G_BAND       5 /* 动态校准5g band1 2&3 4&5 6 7 */
#define DY_CALI_FIT_PRECISION_A1  6
#define DY_CALI_FIT_PRECISION_A0  16
#define CUS_MAX_BASE_TXPOWER_VAL  250                 /* 最大基准发送功率的最大有效值 */
#define CUS_MIN_BASE_TXPOWER_VAL  50                  /* 最小基准发送功率的最大有效值 */
#define CUS_BASE_PWR_NUM_5G       DY_CALI_NUM_5G_BAND /* 5g Base power 5个 band1 2&3 4&5 6 7 */
#define CUS_BASE_PWR_NUM_2G       1
#define CUS_MAX_BASE_TXPOWER_DELT_VAL_MIN  (-100)       /* MIMO的最大基准发送功率差值的最小有效值 */
#ifdef _PRE_WLAN_FEATURE_TAS_ANT_SWITCH
#define CUS_MAX_OF_TAS_PWR_CTRL_VAL 40 /* TAS控制抬升功率最大值4db */
#endif
#define CUS_2G_LOW_POW_AMEND_ABS_VAL_MAX 30
#define CUS_RU_DELT_POW_MIN       -20
#define CUS_RU_DELT_POW_MAX       20

#define WLAN_CALI_TXPWR_REF_2G_CH1_VAL    6250
#define WLAN_CALI_TXPWR_REF_2G_CH2_VAL    5362
#define WLAN_CALI_TXPWR_REF_2G_CH3_VAL    4720
#define WLAN_CALI_TXPWR_REF_2G_CH4_VAL    4480
#define WLAN_CALI_TXPWR_REF_2G_CH5_VAL    4470
#define WLAN_CALI_TXPWR_REF_2G_CH6_VAL    4775
#define WLAN_CALI_TXPWR_REF_2G_CH7_VAL    5200
#define WLAN_CALI_TXPWR_REF_2G_CH8_VAL    5450
#define WLAN_CALI_TXPWR_REF_2G_CH9_VAL    5600
#define WLAN_CALI_TXPWR_REF_2G_CH10_VAL   6100
#define WLAN_CALI_TXPWR_REF_2G_CH11_VAL   6170
#define WLAN_CALI_TXPWR_REF_2G_CH12_VAL   6350
#define WLAN_CALI_TXPWR_REF_2G_CH13_VAL   6530
#define WLAN_CALI_TXPWR_REF_5G_BAND1_VAL  2500
#define WLAN_CALI_TXPWR_REF_5G_BAND2_VAL  2800
#define WLAN_CALI_TXPWR_REF_5G_BAND3_VAL  3100
#define WLAN_CALI_TXPWR_REF_5G_BAND4_VAL  3600
#define WLAN_CALI_TXPWR_REF_5G_BAND5_VAL  3600
#define WLAN_CALI_TXPWR_REF_5G_BAND6_VAL  3700
#define WLAN_CALI_TXPWR_REF_5G_BAND7_VAL  3800
#define WLAN_CALI_TONE_GRADE_AMP          1
#define WLAN_BT_PA_REF_BAND1              11000
#define WLAN_BT_PA_REF_BAND2              10000
#define WLAN_BT_PA_REF_BAND3              7000
#define WLAN_BT_PA_REF_BAND4              8000
#define WLAN_BT_PA_REF_BAND5              7000
#define WLAN_BT_PA_REF_BAND6              7000
#define WLAN_BT_PA_REF_BAND7              12000
#define WLAN_BT_PA_REF_BAND8              12000
#define WLAN_BT_PA_NUM                    7
#define WLAN_BT_PA_FRE1                   0
#define WLAN_BT_PA_FRE2                   10
#define WLAN_BT_PA_FRE3                   28
#define WLAN_BT_PA_FRE4                   45
#define WLAN_BT_PA_FRE5                   53
#define WLAN_BT_PA_FRE6                   63
#define WLAN_BT_PA_FRE7                   76
#define WLAN_BT_PA_FRE8                   78
#define WLAN_BT_AMP_GRADE                 2
#define WLAN_ROAM_SWITCH_MODE             1
#define WLAN_SCAN_ORTHOGONAL_VAL          4
#define WLAN_TRIGGER_B_VAL                (-70)
#define WLAN_TRIGGER_A_VAL                (-70)
#define WLAN_DELTA_B_VAL                  10
#define WLAN_DELTA_A_VAL                  10
#define WLAN_MEM_FOR_START                45
#define WLAN_MEM_FOR_STOP                 25
#define WLAN_RX_ACK_LIMIT_VAL             10
#define WLAN_SDIO_H2D_ASSEMBLE_COUNT_VAL  16
#define WLAN_LOSS_THRESHOLD_WLAN_BT       80
#define WLAN_LOSS_THRESHOLD_WLAN_DBAC     80
#define WLAN_LOSS_THRESHOLD_WLAN_NORMAL   40
#define WLAN_IRQ_TH_HIGH                  250
#define WLAN_IRQ_TH_LOW                   150
#define WLAN_IRQ_PPS_TH_HIGH              25000
#define WLAN_IRQ_PPS_TH_LOW               5000
#define WLAN_HW_AMPDU_TH_HIGH             300
#define WLAN_HW_AMPDU_TH_LOW              200
#define WLAN_DEFAULT_TX_SWITCH            0
#define WLAN_AMSDU_AMPDU_TH_HIGH          300
#define WLAN_AMSDU_AMPDU_TH_LOW           200
#define WLAN_AMSDU_AMPDU_TH_MIDDLE        250
#define WLAN_TCP_ACK_FILTER_TH_HIGH       60
#define WLAN_TCP_ACK_FILTER_TH_LOW        20
#define WLAN_SMALL_AMSDU_HIGH             300
#define WLAN_SMALL_AMSDU_LOW              200
#define WLAN_SMALL_AMSDU_PPS_HIGH         25000
#define WLAN_SMALL_AMSDU_PPS_LOW          5000
#define WLAN_TCP_ACK_BUF_HIGH             90
#define WLAN_TCP_ACK_BUF_LOW              50
#define WLAN_TCP_ACK_BUF_HIGH_40M         300
#define WLAN_TCP_ACK_BUF_LOW_40M          150
#define WLAN_TCP_ACK_BUF_HIGH_80M         550
#define WLAN_TCP_ACK_BUF_LOW_80M          450
#define WLAN_TCP_ACK_BUF_HIGH_160M        800
#define WLAN_TCP_ACK_BUF_LOW_160M         700
#define WLAN_RX_DYN_BYPASS_EXTLNA_HIGH    100
#define WLAN_TCP_ACK_BUF_USERCTL_HIGH     30
#define WLAN_TCP_ACK_BUF_USERCTL_LOW      20
#define WLAN_RX_DYN_BYPASS_EXTLNA_LOW     50
#define WLAN_PS_MODE                      1
#define WLAN_MIN_FAST_PS_IDLE             1
#define WLAN_MAX_FAST_PS_IDLE             10
#define WLAN_AUTO_FAST_PS_SCREENON        5
#define WLAN_AUTO_FAST_PS_SCREENOFF       5
#define WLAN_RF_LNA_BYPASS_GAIN_DB_2G     (-12)
#define WLAN_RF_LNA_GAIN_DB_2G            20
#define WLAN_RF_PA_GAIN_DB_B0_2G          (-12)
#define WLAN_EXT_SWITCH_ISEXIST_2G        0
#define WLAN_EXT_PA_ISEXIST_2G            0
#define WLAN_EXT_LNA_ISEXIST_2G           0
#define WLAN_LNA_ON2OFF_TIME_NS_2G        630
#define WLAN_LNA_OFF2ON_TIME_NS_2G        320
#define WLAN_RF_LNA_BYPASS_GAIN_DB_5G     (-12)
#define WLAN_RF_LNA_GAIN_DB_5G            20
#define WLAN_RF_PA_GAIN_DB_B0_5G          (-12)
#define WLAN_EXT_SWITCH_ISEXIST_5G        1
#define WLAN_EXT_PA_ISEXIST_5G            1
#define WLAN_EXT_LNA_ISEXIST_5G           1
#define WLAN_LNA_ON2OFF_TIME_NS_5G        630
#define WLAN_LNA_OFF2ON_TIME_NS_5G        320
#define WLAN_TX_RATIO_LEVEL_0             900
#define WLAN_TX_PWR_COMP_VAL_LEVEL_0      17
#define WLAN_TX_RATIO_LEVEL_1             650
#define WLAN_TX_PWR_COMP_VAL_LEVEL_1      13
#define WLAN_TX_RATIO_LEVEL_2             280
#define WLAN_TX_PWR_COMP_VAL_LEVEL_2      5
#define WLAN_MORE_PWR                     7
#define WLAN_STA_KEEPALIVE_CNT_TH         3
#define WLAN_BTCOEX_THRESHOLD_MCM_DOWN      (-45) /* 修改此值需要同步修改device */
#define WLAN_BTCOEX_THRESHOLD_MCM_UP        (-75) /* 修改此值需要同步修改device */
#define WLAN_RF_RX_INSERTION_LOSS_2G_BAND1  (-12)
#define WLAN_RF_RX_INSERTION_LOSS_2G_BAND2  (-12)
#define WLAN_RF_RX_INSERTION_LOSS_2G_BAND3  (-12)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND1  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND2  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND3  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND4  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND5  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND6  (-8)
#define WLAN_RF_RX_INSERTION_LOSS_5G_BAND7  (-8)
#define WLAN_RF_RSSI_AMEND_TH_HIGH   (10)
#define WLAN_RF_RSSI_AMEND_TH_LOW    (-10)
#define WLAN_DDR_CAHNL_FREQ 8640 /* 向内核申请非415M DDR频率 */
#define WLAN_HIEX_DEV_CAP 0x1000


/* 根据产线delt power更新系数 */
#define cus_flush_nv_ratio_by_delt_pow(_s_pow_par2, _s_pow_par1, _s_pow_par0, _s_delt_power)             \
    do {                                                                                                 \
        (_s_pow_par0) = (((oal_int32)(_s_delt_power) * (_s_delt_power) * (_s_pow_par2)) +                \
                            (((oal_int32)(_s_pow_par1) << DY_CALI_FIT_PRECISION_A1) * (_s_delt_power)) + \
                            ((oal_int32)(_s_pow_par0) << DY_CALI_FIT_PRECISION_A0)) >>                   \
                        DY_CALI_FIT_PRECISION_A0;                                                        \
        (_s_pow_par1) = (((oal_int32)(_s_delt_power) * (_s_pow_par2)*2) +                                \
                            ((oal_int32)(_s_pow_par1) << DY_CALI_FIT_PRECISION_A1)) >>                   \
                        DY_CALI_FIT_PRECISION_A1;                                                        \
    } while (0)

/* 判断当前值是否在合理范围 */
#define cus_val_invalid(val, upper_val, low_val) (((val) > (upper_val)) || ((val) < (low_val)))
#define cus_val_valid(val, upper_val, low_val) (((val) <= (upper_val)) && ((val) >= (low_val)))

/* 计算绝对值 */
#define cus_abs(val) ((val) > 0 ? (val) : -(val))

/* 判断CCA能量门限调整值是否超出范围, 最大调整幅度:DELTA_CCA_ED_HIGH_TH_RANGE */
#define cus_delta_cca_ed_high_th_out_of_range(val) (cus_abs(val) > DELTA_CCA_ED_HIGH_TH_RANGE ? 1 : 0)

/* 取16位数 */
#define cus_get_low_16bits(val)  ((oal_uint16)((oal_uint32)val & 0x0000FFFF))
#define cus_get_high_16bits(val) ((oal_uint16)(((oal_uint32)val & 0xFFFF0000) >> 16))
/* 取8位数 */
#define cus_get_first_byte(val)  (((oal_uint32)val) & 0xFF)
#define cus_get_second_byte(val) (((oal_uint32)val >> 8) & 0xFF)
#define cus_get_third_byte(val)  (((oal_uint32)val >> 16) & 0xFF)
#define cus_get_fourth_byte(val) (((oal_uint32)val >> 24) & 0xFF)

#define hwifi_get_5g_pro_line_delt_pow_per_band(_ps_nv_params, _ps_ini_params) \
    (oal_int16)(((oal_int32)(((_ps_nv_params)[1]) -                            \
                             ((_ps_ini_params)[1]))                            \
                    << DY_CALI_FIT_PRECISION_A1) /                             \
                (2 * ((_ps_nv_params)[0])))

#define hwifi_dyn_cali_get_extre_point(_ps_ini_params) \
    (-(((_ps_ini_params)[1]) << DY_CALI_FIT_PRECISION_A1) / (2 * ((_ps_ini_params)[0])))

/* 开机校准MASK */
#define HI1103_CALI_FIST_POWER_ON_MASK BIT(2)
/* 读取NVRAM MASK */
#define HI1103_CUST_READ_NVRAM_MASK BIT(4)

/* 枚举定义 */
typedef enum {
    HWIFI_CFG_DYN_PWR_CALI_2G_SNGL_MODE_11B = 0,
    HWIFI_CFG_DYN_PWR_CALI_2G_SNGL_MODE_OFDM20,
    HWIFI_CFG_DYN_PWR_CALI_2G_SNGL_MODE_OFDM40,
    HWIFI_CFG_DYN_PWR_CALI_2G_SNGL_MODE_CW,
    HWIFI_CFG_DYN_PWR_CALI_2G_SNGL_MODE_BUTT,
} hwifi_dyn_2g_pwr_sngl_mode_enum;
#ifdef _PRE_WLAN_COUNTRYCODE_SELFSTUDY
/* 枚举定义 */
typedef enum {
    CUS_PARAM_COUNTRYCODE_SELFSTUDY_OPEN0 = BIT0,
    CUS_PARAM_COUNTRYCODE_SELFSTUDY_OPEN1 = BIT1,
    CUS_PARAM_COUNTRYCODE_SELFSTUDY_MODE_BUTT,
} hwifi_country_code_mode_enum;
#endif

/* NV map idx */
typedef enum {
    HWIFI_CFG_NV_WINVRAM_NUMBER = 340,
    HWIFI_CFG_NV_WITXNVCCK_NUMBER = 367,
    HWIFI_CFG_NV_WITXNVC1_NUMBER = 368,
    HWIFI_CFG_NV_WITXNVBWC0_NUMBER = 369,
    HWIFI_CFG_NV_WITXNVBWC1_NUMBER = 370,
    HWIFI_CFG_NV_WITXL2G5G0_NUMBER = 384,
    HWIFI_CFG_NV_WITXL2G5G1_NUMBER = 385,
    HWIFI_CFG_NV_MUFREQ_5G160_C0_NUMBER,
    HWIFI_CFG_NV_MUFREQ_5G160_C1_NUMBER,
    HWIFI_CFG_NV_MUFREQ_2G20_C0_NUMBER = 396,
    HWIFI_CFG_NV_MUFREQ_2G20_C1_NUMBER,
    HWIFI_CFG_NV_MUFREQ_2G40_C0_NUMBER,
    HWIFI_CFG_NV_MUFREQ_2G40_C1_NUMBER,
    HWIFI_CFG_NV_MUFREQ_CCK_C0_NUMBER,
    HWIFI_CFG_NV_MUFREQ_CCK_C1_NUMBER,
} wlan_nvram_idx;

/* 定制化 DTS CONFIG ID */
typedef enum {
    /* 校准 */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN1,
    /* 校准 2g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_START = WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN1,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN2,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN3,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN4,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN5,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN6,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN7,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN8,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN9,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN10,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN11,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN12,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN13,

    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND1,  // 13
    /* 校准 5g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_START = WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND1,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND2,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND3,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND4,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND5,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND6,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND7,
    WLAN_CFG_DTS_CALI_TONE_AMP_GRADE,

    /* DPD校准 */
    WLAN_CFG_DTS_DPD_CALI_CH_CORE0,
    WLAN_CFG_DTS_DPD_CALI_START = WLAN_CFG_DTS_DPD_CALI_CH_CORE0, /* DPD校准定制化配置起始ID */
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX0_CORE0,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX1_CORE0,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX2_CORE0,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX3_CORE0,
    WLAN_CFG_DTS_DPD_CALI_20M_DEL_POW_CORE0,
    WLAN_CFG_DTS_DPD_CALI_40M_DEL_POW_CORE0,
    WLAN_CFG_DTS_DPD_CALI_CH_CORE1,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX0_CORE1,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX1_CORE1,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX2_CORE1,
    WLAN_CFG_DTS_DPD_USE_CALI_CH_IDX3_CORE1,
    WLAN_CFG_DTS_DPD_CALI_20M_DEL_POW_CORE1,
    WLAN_CFG_DTS_DPD_CALI_40M_DEL_POW_CORE1,
    /* 动态校准 */
    WLAN_CFG_DTS_DYN_CALI_DSCR_ITERVL,
    WLAN_CFG_DTS_DYN_CALI_OPT_SWITCH,
    WLAN_CFG_DTS_DYN_CALI_GM0_DB10_AMEND,

    /* DPN 40M 20M 11b */
    WLAN_CFG_DTS_2G_CORE0_DPN_CH1,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH2,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH3,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH4,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH5,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH6,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH7,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH8,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH9,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH10,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH11,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH12,
    WLAN_CFG_DTS_2G_CORE0_DPN_CH13,
    WLAN_CFG_DTS_5G_CORE0_DPN_B0,
    WLAN_CFG_DTS_5G_CORE0_DPN_B1,
    WLAN_CFG_DTS_5G_CORE0_DPN_B2,
    WLAN_CFG_DTS_5G_CORE0_DPN_B3,
    WLAN_CFG_DTS_5G_CORE0_DPN_B4,
    WLAN_CFG_DTS_5G_CORE0_DPN_B5,
    WLAN_CFG_DTS_5G_CORE0_DPN_B6,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH1,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH2,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH3,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH4,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH5,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH6,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH7,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH8,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH9,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH10,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH11,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH12,
    WLAN_CFG_DTS_2G_CORE1_DPN_CH13,
    WLAN_CFG_DTS_5G_CORE1_DPN_B0,
    WLAN_CFG_DTS_5G_CORE1_DPN_B1,
    WLAN_CFG_DTS_5G_CORE1_DPN_B2,
    WLAN_CFG_DTS_5G_CORE1_DPN_B3,
    WLAN_CFG_DTS_5G_CORE1_DPN_B4,
    WLAN_CFG_DTS_5G_CORE1_DPN_B5,
    WLAN_CFG_DTS_5G_CORE1_DPN_B6,

    WLAN_CFG_DTS_BUTT,
} WLAN_CFG_DTS;

/* 私有定制化 PRIV CONFIG ID */
typedef enum {
    /* 校准开关 */
    WLAN_CFG_PRIV_CALI_MASK,
    WLAN_CFG_PRIV_CALI_DATA_MASK,
    WLAN_CFG_PRIV_CALI_AUTOCALI_MASK,

    WLAN_CFG_PRIV_BW_MAX_WITH,
    WLAN_CFG_PRIV_LDPC_CODING,
    WLAN_CFG_PRIV_RX_STBC,
    WLAN_CFG_PRIV_TX_STBC,
    WLAN_CFG_PRIV_SU_BFER,
    WLAN_CFG_PRIV_SU_BFEE,
    WLAN_CFG_PRIV_MU_BFER,
    WLAN_CFG_PRIV_MU_BFEE,
    WLAN_CFG_PRIV_11N_TXBF,
    WLAN_CFG_PRIV_1024_QAM,
    /* DBDC */
    WLAN_CFG_PRIV_DBDC_RADIO_0,
    WLAN_CFG_PRIV_DBDC_RADIO_1,
    WLAN_CFG_PRIV_FASTSCAN_SWITCH,

    /* 天线切换功能 */
    WLAN_CFG_ANT_SWITCH,
    /* 国家码自学习开关 */
    WLAN_CFG_PRIV_COUNRTYCODE_SELFSTUDY_CFG,

    /* M2S */
    WLAN_CFG_PRIV_M2S_FUNCTION_EXT_MASK,
    WLAN_CFG_PRIV_M2S_FUNCTION_MASK,

    /* MCM */
    WLAN_CFG_PRIV_MCM_CUSTOM_FUNCTION_MASK,
    WLAN_CFG_PRIV_MCM_FUNCTION_MASK,

    /* linkloss门限固定开关 */
    WLAN_CFG_PRRIV_LINKLOSS_THRESHOLD_FIXED,

    /* 160M APUT使能 */
    WLAN_CFG_APUT_160M_ENABLE,
    /* 屏蔽硬件上报的雷达信号 */
    WLAN_CFG_RADAR_ISR_FORBID,

    /* 限流 */
    WLAN_CFG_PRIV_DOWNLOAD_RATE_LIMIT_PPS,
#ifdef _PRE_WLAN_FEATURE_TXOPPS
    WLAN_CFG_PRIV_TXOPPS_SWITCH,
#endif
    WLAN_CFG_PRIV_OVER_TEMPER_PROTECT_THRESHOLD,
    WLAN_CFG_PRIV_OVER_TEMP_PRO_ENABLE,
    WLAN_CFG_PRIV_OVER_TEMP_PRO_REDUCE_PWR_ENABLE,
    WLAN_CFG_PRIV_OVER_TEMP_PRO_SAFE_TH,
    WLAN_CFG_PRIV_OVER_TEMP_PRO_OVER_TH,
    WLAN_CFG_PRIV_OVER_TEMP_PRO_PA_OFF_TH,

    WLAN_DSSS2OFDM_DBB_PWR_BO_VAL,
    WLAN_CFG_PRIV_EVM_PLL_REG_FIX,

    /* VOE */
    WLAN_CFG_PRIV_VOE_SWITCH,
    /* 11ax */
    WLAN_CFG_PRIV_11AX_SWITCH,
    WLAN_CFG_PRIV_HTC_SWITCH,

    /* M_BSSID */
    WLAN_CFG_PRIV_MULTI_BSSID_SWITCH,
    WLAN_CFG_PRIV_AC_SUSPEND,

    /* 动态bypass外置LNA方案 */
    WLAN_CFG_PRIV_DYN_BYPASS_EXTLNA,

    WLAN_CFG_PRIV_CTRL_FRAME_TX_CHAIN,

    WLAN_CFG_PRIV_CTRL_UPC_FOR_18DBM_CO,
    WLAN_CFG_PRIV_CTRL_UPC_FOR_18DBM_C1,
    WLAN_CFG_PRIV_CTRL_11B_DOUBLE_CHAIN_BO_POW,

    /* 非高优先级hcc流控类型 0:SDIO 1:GPIO */
    WLAN_CFG_PRIV_HCC_FLOWCTRL_TYPE,

    /* 注册WiFi动态锁频麒麟接口 */
    WLAN_CFG_PRIV_LOCK_CPU_FREQ,

    /* MBO(Multiband Operation)定制化 */
    WLAN_CFG_PRIV_MBO_SWITCH,
    /* 动态dbac 定制化 */
    WLAN_CFG_PRIV_DYNAMIC_DBAC_SWITCH,

    /* DC流控特性定制化开关 */
    WLAN_CFG_PRIV_DC_FLOWCTL_SWITCH,
    /* phy相关能力定制化 */
    WLAN_CFG_PRIV_PHY_CAP_SWITCH,

    WLAN_CFG_PRIV_HAL_PS_RSSI_PARAM,
    WLAN_CFG_PRIV_HAL_PS_PPS_PARAM,
    /* 优化特性开关 */
    WLAN_CFG_PRIV_OPTIMIZED_FEATURE_SWITCH,

    /* ddr */
    WLAN_CFG_PRIV_DDR_SWITCH,

    /* FEM pow saving 50 */
    WLAN_CFG_PRIV_FEM_DELT_POW,
    WLAN_CFG_PRIV_FEM_ADJ_TPC_TBL_START_IDX,
    /* dev hiex cap定制化 */
    WLAN_CFG_PRIV_HIEX_CAP,
    WLAN_CFG_PRIV_TX_SWITCH,
    /* FTM cap定制化 */
    WLAN_CFG_PRIV_FTM_CAP,

    WLAN_CFG_PRIV_BUTT,
} WLAN_CFG_PRIV;
typedef oal_uint8 wlan_cfg_priv_id_uint8;

/* 定制化 INI CONFIG ID */
typedef enum {
    /* ROAM */
    WLAN_CFG_INIT_ROAM_SWITCH = 0,
    WLAN_CFG_INIT_SCAN_ORTHOGONAL,
    WLAN_CFG_INIT_TRIGGER_B,
    WLAN_CFG_INIT_TRIGGER_A,
    WLAN_CFG_INIT_DELTA_B,
    WLAN_CFG_INIT_DELTA_A,
    WLAN_CFG_INIT_DENSE_ENV_TRIGGER_B,
    WLAN_CFG_INIT_DENSE_ENV_TRIGGER_A,
    WLAN_CFG_INIT_SCENARIO_ENABLE,
    WLAN_CFG_INIT_CANDIDATE_GOOD_RSSI,
    WLAN_CFG_INIT_CANDIDATE_GOOD_NUM,
    WLAN_CFG_INIT_CANDIDATE_WEAK_NUM,
    WLAN_CFG_INIT_INTERVAL_VARIABLE,

    /* 性能 */
    WLAN_CFG_INIT_AMPDU_TX_MAX_NUM,  // 7
    WLAN_CFG_INIT_USED_MEM_FOR_START,
    WLAN_CFG_INIT_USED_MEM_FOR_STOP,
    WLAN_CFG_INIT_RX_ACK_LIMIT,
    WLAN_CFG_INIT_SDIO_D2H_ASSEMBLE_COUNT,
    WLAN_CFG_INIT_SDIO_H2D_ASSEMBLE_COUNT,
    /* LINKLOSS */
    WLAN_CFG_INIT_LINK_LOSS_THRESHOLD_BT,  // 13,这里不能直接赋值
    WLAN_CFG_INIT_LINK_LOSS_THRESHOLD_DBAC,
    WLAN_CFG_INIT_LINK_LOSS_THRESHOLD_NORMAL,
    /* 自动调频 */
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_0,  // 16
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_0,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_0,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_1,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_1,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_1,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_2,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_2,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_2,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_3,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_3,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_3,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_0,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_1,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_2,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_3,
    WLAN_CFG_PRIV_DMA_LATENCY,
    WLAN_CFG_PRIV_LOCK_CPU_TH_HIGH,
    WLAN_CFG_PRIV_LOCK_CPU_TH_LOW,
    WLAN_CFG_INIT_IRQ_AFFINITY,
    WLAN_CFG_INIT_IRQ_TH_LOW,
    WLAN_CFG_INIT_IRQ_TH_HIGH,
    WLAN_CFG_INIT_IRQ_PPS_TH_LOW,
    WLAN_CFG_INIT_IRQ_PPS_TH_HIGH,
#ifdef _PRE_WLAN_FEATURE_AMPDU_TX_HW
    WLAN_CFG_INIT_HW_AMPDU,
    WLAN_CFG_INIT_HW_AMPDU_TH_LOW,
    WLAN_CFG_INIT_HW_AMPDU_TH_HIGH,
#endif
#ifdef _PRE_WLAN_FEATURE_MULTI_NETBUF_AMSDU
    WLAN_CFG_INIT_AMPDU_AMSDU_SKB,
    WLAN_CFG_INIT_AMSDU_AMPDU_TH_LOW,
    WLAN_CFG_INIT_AMSDU_AMPDU_TH_MIDDLE,
    WLAN_CFG_INIT_AMSDU_AMPDU_TH_HIGH,
#endif
#ifdef _PRE_WLAN_TCP_OPT
    WLAN_CFG_INIT_TCP_ACK_FILTER,
    WLAN_CFG_INIT_TCP_ACK_FILTER_TH_LOW,
    WLAN_CFG_INIT_TCP_ACK_FILTER_TH_HIGH,
#endif
    WLAN_CFG_INIT_TX_SMALL_AMSDU,
    WLAN_CFG_INIT_SMALL_AMSDU_HIGH,
    WLAN_CFG_INIT_SMALL_AMSDU_LOW,
    WLAN_CFG_INIT_SMALL_AMSDU_PPS_HIGH,
    WLAN_CFG_INIT_SMALL_AMSDU_PPS_LOW,

    WLAN_CFG_INIT_TX_TCP_ACK_BUF,
    WLAN_CFG_INIT_TCP_ACK_BUF_HIGH,
    WLAN_CFG_INIT_TCP_ACK_BUF_LOW,
    WLAN_CFG_INIT_TCP_ACK_BUF_HIGH_40M,
    WLAN_CFG_INIT_TCP_ACK_BUF_LOW_40M,
    WLAN_CFG_INIT_TCP_ACK_BUF_HIGH_80M,
    WLAN_CFG_INIT_TCP_ACK_BUF_LOW_80M,
    WLAN_CFG_INIT_TCP_ACK_BUF_HIGH_160M,
    WLAN_CFG_INIT_TCP_ACK_BUF_LOW_160M,

    WLAN_CFG_INIT_TX_TCP_ACK_BUF_USERCTL,
    WLAN_CFG_INIT_TCP_ACK_BUF_USERCTL_HIGH,
    WLAN_CFG_INIT_TCP_ACK_BUF_USERCTL_LOW,

    WLAN_CFG_INIT_RX_DYN_BYPASS_EXTLNA,
    WLAN_CFG_INIT_RX_DYN_BYPASS_EXTLNA_HIGH,
    WLAN_CFG_INIT_RX_DYN_BYPASS_EXTLNA_LOW,

    /* 接收ampdu+amsdu */
    WLAN_CFG_INIT_RX_AMPDU_AMSDU_SKB,
    WLAN_CFG_INIT_RX_AMPDU_BITMAP,

    /* 低功耗 */
    WLAN_CFG_INIT_POWERMGMT_SWITCH,  // 31
    WLAN_CFG_INIT_PS_MODE,
    WLAN_CFG_INIT_MIN_FAST_PS_IDLE,  // How many 20ms
    WLAN_CFG_INIT_MAX_FAST_PS_IDLE,
    WLAN_CFG_INIT_AUTO_FAST_PS_THRESH_SCREENON,
    WLAN_CFG_INIT_AUTO_FAST_PS_THRESH_SCREENOFF,

    /* 可维可测 */
    WLAN_CFG_INIT_LOGLEVEL,
    /* 2G RF前端 */
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND_START,  // 33
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND1 = WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND_START,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND2,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND3,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND_END = WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_2G_BAND3,
    /* 5G RF前端 */
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND_START,  // 37
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND1 = WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND_START,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND2,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND3,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND4,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND5,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND6,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND7,
    WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND_END = WLAN_CFG_INIT_RF_RX_INSERTION_LOSS_5G_BAND7,

    /* 用于定制化计算PWR RF值的偏差 */
    WLAN_CFG_INIT_RF_PWR_REF_RSSI_2G_C0_MULT4,
    WLAN_CFG_INIT_RF_PWR_REF_RSSI_2G_C1_MULT4,
    WLAN_CFG_INIT_RF_PWR_REF_RSSI_5G_C0_MULT4,
    WLAN_CFG_INIT_RF_PWR_REF_RSSI_5G_C1_MULT4,

    /* 用于定制化计算RSSI的偏差 */
    WLAN_CFG_INIT_RF_AMEND_RSSI_2G_C0,
    WLAN_CFG_INIT_RF_AMEND_RSSI_2G_C1,
    WLAN_CFG_INIT_RF_AMEND_RSSI_5G_C0,
    WLAN_CFG_INIT_RF_AMEND_RSSI_5G_C1,

    /* FEM 03考虑2g */
    WLAN_CFG_INIT_RF_LNA_BYPASS_GAIN_DB_2G,
    WLAN_CFG_INIT_RF_LNA_GAIN_DB_2G,
    WLAN_CFG_INIT_RF_PA_GAIN_DB_B0_2G,
    WLAN_CFG_INIT_RF_PA_GAIN_DB_B1_2G,
    WLAN_CFG_INIT_RF_PA_GAIN_LVL_2G,
    WLAN_CFG_INIT_EXT_SWITCH_ISEXIST_2G,
    WLAN_CFG_INIT_EXT_PA_ISEXIST_2G,
    WLAN_CFG_INIT_EXT_LNA_ISEXIST_2G,
    WLAN_CFG_INIT_LNA_ON2OFF_TIME_NS_2G,
    WLAN_CFG_INIT_LNA_OFF2ON_TIME_NS_2G,
    WLAN_CFG_INIT_RF_LNA_BYPASS_GAIN_DB_5G,
    WLAN_CFG_INIT_RF_LNA_GAIN_DB_5G,
    WLAN_CFG_INIT_RF_PA_GAIN_DB_B0_5G,
    WLAN_CFG_INIT_RF_PA_GAIN_DB_B1_5G,
    WLAN_CFG_INIT_RF_PA_GAIN_LVL_5G,
    WLAN_CFG_INIT_EXT_SWITCH_ISEXIST_5G,
    WLAN_CFG_INIT_EXT_PA_ISEXIST_5G,
    WLAN_CFG_INIT_EXT_LNA_ISEXIST_5G,
    WLAN_CFG_INIT_LNA_ON2OFF_TIME_NS_5G,
    WLAN_CFG_INIT_LNA_OFF2ON_TIME_NS_5G,
    /* SCAN */
    WLAN_CFG_INIT_RANDOM_MAC_ADDR_SCAN,
    /* 11AC2G */
    WLAN_CFG_INIT_11AC2G_ENABLE,
    /* 11ac2g开关 */                    // 56
    WLAN_CFG_INIT_DISABLE_CAPAB_2GHT40, /* 2ght40禁止开关 */
    WLAN_CFG_INIT_DUAL_ANTENNA_ENABLE,  /* 双天线开关 */

    /* probe req应答模式功能配置 */
    WLAN_CFG_INIT_PROBE_RESP_MODE, /* BIT7~BIT4:动态功能开关 ;BIT3~BIT0:功能模式(mac_probe_resp_mode_enum_uint8) , 目前此配置仅针对p2p dev设备有效 */
    WLAN_CFG_INIT_MIRACAST_SINK_ENABLE, /* miracast_sink特性开关 */
    WLAN_CFG_INIT_REDUCE_MIRACAST_LOG, /* miracast log 降级开关 */
    WLAN_CFG_INIT_CORE_BIND_CAP, /* 是否支持cpu绑定 */
    WLAN_CFG_INIT_FAST_MODE, /* BUCK stay in fastmode */

    /* sta keepalive */
    WLAN_CFG_INIT_STA_KEEPALIVE_CNT_TH, /* sta keepalive th */
    WLAN_CFG_INIT_FAR_DIST_POW_GAIN_SWITCH,
    WLAN_CFG_INIT_FAR_DIST_DSSS_SCALE_PROMOTE_SWITCH, /* 超远距11b 1m 2m dbb scale提升使能开关 */
    WLAN_CFG_INIT_CHANN_RADIO_CAP, /* 通道0、1 2g 5g频道能力 */

    WLAN_CFG_LTE_GPIO_CHECK_SWITCH, /* lte?????? */
    WLAN_ATCMDSRV_ISM_PRIORITY,
    WLAN_ATCMDSRV_LTE_RX,
    WLAN_ATCMDSRV_LTE_TX,
    WLAN_ATCMDSRV_LTE_INACT,
    WLAN_ATCMDSRV_ISM_RX_ACT,
    WLAN_ATCMDSRV_BANT_PRI,
    WLAN_ATCMDSRV_BANT_STATUS,
    WLAN_ATCMDSRV_WANT_PRI,
    WLAN_ATCMDSRV_WANT_STATUS,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_1,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_2,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_3,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_4,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_5,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_6,
    WLAN_TX5G_UPC_MIX_GAIN_CTRL_7,

    WLAN_TX2G_PA_GATE_VCTL_REG236,
    WLAN_TX2G_PA_GATE_VCTL_REG237,
    WLAN_TX2G_PA_GATE_VCTL_REG238,
    WLAN_TX2G_PA_GATE_VCTL_REG239,
    WLAN_TX2G_PA_GATE_VCTL_REG240,
    WLAN_TX2G_PA_GATE_VCTL_REG241,
    WLAN_TX2G_PA_GATE_VCTL_REG242,
    WLAN_TX2G_PA_GATE_VCTL_REG243,
    WLAN_TX2G_PA_GATE_VCTL_REG244,

    WLAN_TX2G_PA_VRECT_GATE_THIN_REG253,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG254,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG255,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG256,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG257,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG258,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG259,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG260,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG261,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG262,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG263,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG264,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG265,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG266,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG267,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG268,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG269,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG270,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG271,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG272,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG273,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG274,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG275,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG276,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG277,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG278,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG279,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG280_BAND1,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG281,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG282,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG283,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG284,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG280_BAND2,
    WLAN_TX2G_PA_VRECT_GATE_THIN_REG280_BAND3,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_20TH_2G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_40TH_2G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_20TH_5G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_40TH_5G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_80TH_5G,
    WLAN_CFG_INIT_VOE_SWITCH,
    WLAN_CFG_INIT_11AX_SWITCH,
    WLAN_CFG_INIT_HTC_SWITCH,
    WLAN_CFG_INIT_MULTI_BSSID_SWITCH,

    /* ldac m2s rssi */
    WLAN_CFG_INIT_LDAC_THRESHOLD_M2S,
    WLAN_CFG_INIT_LDAC_THRESHOLD_S2M,

    /* btcoex mcm rssi */
    WLAN_CFG_INIT_BTCOEX_THRESHOLD_MCM_DOWN,
    WLAN_CFG_INIT_BTCOEX_THRESHOLD_MCM_UP,

#ifdef _PRE_WLAN_FEATURE_NRCOEX
    /* 5g nr coex */
    WLAN_CFG_INIT_NRCOEX_ENABLE,
    WLAN_CFG_INIT_NRCOEX_RULE0_FREQ,
    WLAN_CFG_INIT_NRCOEX_RULE0_40M_20M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE0_160M_80M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE0_40M_20M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE0_160M_80M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE0_40M_20M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE0_160M_80M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE0_SMALLGAP0_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE0_GAP01_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE0_GAP12_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE0_RXSLOT_RSSI,
    WLAN_CFG_INIT_NRCOEX_RULE1_FREQ,
    WLAN_CFG_INIT_NRCOEX_RULE1_40M_20M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE1_160M_80M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE1_40M_20M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE1_160M_80M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE1_40M_20M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE1_160M_80M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE1_SMALLGAP0_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE1_GAP01_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE1_GAP12_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE1_RXSLOT_RSSI,
    WLAN_CFG_INIT_NRCOEX_RULE2_FREQ,
    WLAN_CFG_INIT_NRCOEX_RULE2_40M_20M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE2_160M_80M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE2_40M_20M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE2_160M_80M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE2_40M_20M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE2_160M_80M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE2_SMALLGAP0_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE2_GAP01_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE2_GAP12_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE2_RXSLOT_RSSI,
    WLAN_CFG_INIT_NRCOEX_RULE3_FREQ,
    WLAN_CFG_INIT_NRCOEX_RULE3_40M_20M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE3_160M_80M_GAP0,
    WLAN_CFG_INIT_NRCOEX_RULE3_40M_20M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE3_160M_80M_GAP1,
    WLAN_CFG_INIT_NRCOEX_RULE3_40M_20M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE3_160M_80M_GAP2,
    WLAN_CFG_INIT_NRCOEX_RULE3_SMALLGAP0_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE3_GAP01_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE3_GAP12_ACT,
    WLAN_CFG_INIT_NRCOEX_RULE3_RXSLOT_RSSI,
#endif
    WLAN_CFG_INIT_DYNAMIC_DBAC_SWITCH,

#ifdef _PRE_WLAN_FEATURE_MBO
    WLAN_CFG_INIT_MBO_SWITCH,
#endif

    WLAN_CFG_INIT_DDR_FREQ,
    WLAN_CFG_INIT_HIEX_CAP,
    WLAN_CFG_INIT_FTM_CAP,
    /* 用于修正由于phy mode滤波器收窄导致的rssi偏差 */
    WLAN_CFG_INIT_RF_FILTER_NARROW_RSSI_AMEND_2G_C0,
    WLAN_CFG_INIT_RF_FILTER_NARROW_RSSI_AMEND_2G_C1,
    WLAN_CFG_INIT_RF_FILTER_NARROW_RSSI_AMEND_5G_C0,
    WLAN_CFG_INIT_RF_FILTER_NARROW_RSSI_AMEND_5G_C1,

    WLAN_CFG_INIT_BUTT,
} WLAN_CFG_INIT;

/* 定制化 NVRAM PARAMS INDEX */
typedef enum {
    NVRAM_PARAMS_INDEX_0,
    NVRAM_PARAMS_INDEX_1,
    NVRAM_PARAMS_INDEX_2,
    NVRAM_PARAMS_INDEX_3,
    NVRAM_PARAMS_INDEX_4,
    NVRAM_PARAMS_INDEX_5,
    NVRAM_PARAMS_INDEX_6,
    NVRAM_PARAMS_INDEX_7,
    NVRAM_PARAMS_INDEX_8,
    NVRAM_PARAMS_INDEX_9,
    NVRAM_PARAMS_INDEX_10,
    NVRAM_PARAMS_INDEX_11,
    /* 2.4g 5g 20M mcs9
      2.4g 5g 20M mcs10 11
      2.4g 5g 40M mcs10 11
      2.4g 5g 80M mcs10 11
      5g 160M mcs0~3
      5g 160M mcs10~11 */
    NVRAM_PARAMS_INDEX_12,
    NVRAM_PARAMS_INDEX_13,
    NVRAM_PARAMS_INDEX_14,
    NVRAM_PARAMS_INDEX_15,
    NVRAM_PARAMS_INDEX_16,
    NVRAM_PARAMS_INDEX_17,
    /* DPD打开时mcs7~mcs11
       发射功率 */
    NVRAM_PARAMS_INDEX_DPD_0,
    NVRAM_PARAMS_INDEX_DPD_1,
    NVRAM_PARAMS_INDEX_DPD_2,
    /* 11B与OFDM功率差 */
    NVRAM_PARAMS_INDEX_11B_OFDM_DELT_POW,
    /* 5G 功率与IQ校准UPC上限值 */
    NVRAM_PARAMS_INDEX_IQ_MAX_UPC,
    /* 2G 低功率修正值 */
    NVRAM_PARAMS_INDEX_2G_LOW_POW_AMEND,
    NVRAM_PARAMS_TXPWR_INDEX_BUTT,
    NVRAM_PARAMS_INDEX_19, /* 2.4g基准发射功率 */
    NVRAM_PARAMS_INDEX_20, /* 5g基准发射功率 */
    NVRAM_PARAMS_INDEX_21, /* 双rf，slave 2.4g基准发射功率 */
    NVRAM_PARAMS_INDEX_22, /* 双rf，slave 5g基准发射功率 */
    NVRAM_PARAMS_BASE_INDEX_BUTT,
    /* MIMO基准发射功率差值 */
    NVRAM_PARAMS_INDEX_DELT_BASE_POWER_23,
    NVRAM_PARAMS_INDEX_24_RSV,
    /* FCC边带最大目标发射功率 */
    NVRAM_PARAMS_FCC_START_INDEX,
    NVRAM_PARAMS_INDEX_25 = NVRAM_PARAMS_FCC_START_INDEX,
    NVRAM_PARAMS_INDEX_26,
    NVRAM_PARAMS_INDEX_27,
    NVRAM_PARAMS_INDEX_28,
    NVRAM_PARAMS_INDEX_29,
    NVRAM_PARAMS_INDEX_30,
    NVRAM_PARAMS_INDEX_31,
    NVRAM_PARAMS_INDEX_32,
    NVRAM_PARAMS_INDEX_33,
    NVRAM_PARAMS_INDEX_34,
    NVRAM_PARAMS_INDEX_35,
    NVRAM_PARAMS_INDEX_36,
    NVRAM_PARAMS_INDEX_37,
    NVRAM_PARAMS_INDEX_38,
    NVRAM_PARAMS_INDEX_39,
    NVRAM_PARAMS_INDEX_40,
    NVRAM_PARAMS_INDEX_41,
    NVRAM_PARAMS_INDEX_42,
    NVRAM_PARAMS_INDEX_43,
    NVRAM_PARAMS_INDEX_44,
    NVRAM_PARAMS_FCC_END_INDEX_BUTT,
    /* CE边带最大目标发射功率 */
    NVRAM_PARAMS_CE_START_INDEX,
    NVRAM_PARAMS_INDEX_CE_0 = NVRAM_PARAMS_CE_START_INDEX,
    NVRAM_PARAMS_INDEX_CE_1,
    NVRAM_PARAMS_INDEX_CE_2,
    NVRAM_PARAMS_INDEX_CE_3,
    NVRAM_PARAMS_INDEX_CE_4,
    NVRAM_PARAMS_INDEX_CE_5,
    NVRAM_PARAMS_INDEX_CE_6,
    NVRAM_PARAMS_INDEX_CE_7,
    NVRAM_PARAMS_INDEX_CE_8,
    NVRAM_PARAMS_INDEX_CE_9,
    NVRAM_PARAMS_INDEX_CE_10,
    NVRAM_PARAMS_INDEX_CE_11,
    NVRAM_PARAMS_INDEX_CE_12,
    NVRAM_PARAMS_INDEX_CE_13,
    NVRAM_PARAMS_INDEX_CE_14,
    NVRAM_PARAMS_INDEX_CE_15,
    NVRAM_PARAMS_INDEX_CE_16,
    NVRAM_PARAMS_INDEX_CE_17,
    NVRAM_PARAMS_INDEX_CE_18,
    NVRAM_PARAMS_INDEX_CE_19,
    NVRAM_PARAMS_CE_END_INDEX_BUTT,
    /* FCC C1边带最大目标发射功率 */
    NVRAM_PARAMS_FCC_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_25_C1 = NVRAM_PARAMS_FCC_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_26_C1,
    NVRAM_PARAMS_INDEX_27_C1,
    NVRAM_PARAMS_INDEX_28_C1,
    NVRAM_PARAMS_INDEX_29_C1,
    NVRAM_PARAMS_INDEX_30_C1,
    NVRAM_PARAMS_INDEX_31_C1,
    NVRAM_PARAMS_INDEX_32_C1,
    NVRAM_PARAMS_INDEX_33_C1,
    NVRAM_PARAMS_INDEX_34_C1,
    NVRAM_PARAMS_INDEX_35_C1,
    NVRAM_PARAMS_INDEX_36_C1,
    NVRAM_PARAMS_INDEX_37_C1,
    NVRAM_PARAMS_INDEX_38_C1,
    NVRAM_PARAMS_INDEX_39_C1,
    NVRAM_PARAMS_INDEX_40_C1,
    NVRAM_PARAMS_INDEX_41_C1,
    NVRAM_PARAMS_INDEX_42_C1,
    NVRAM_PARAMS_INDEX_43_C1,
    NVRAM_PARAMS_INDEX_44_C1,
    NVRAM_PARAMS_FCC_C1_END_INDEX_BUTT,
    /* CE C1边带最大目标发射功率 */
    NVRAM_PARAMS_CE_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_CE_0_C1 = NVRAM_PARAMS_CE_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_CE_1_C1,
    NVRAM_PARAMS_INDEX_CE_2_C1,
    NVRAM_PARAMS_INDEX_CE_3_C1,
    NVRAM_PARAMS_INDEX_CE_4_C1,
    NVRAM_PARAMS_INDEX_CE_5_C1,
    NVRAM_PARAMS_INDEX_CE_6_C1,
    NVRAM_PARAMS_INDEX_CE_7_C1,
    NVRAM_PARAMS_INDEX_CE_8_C1,
    NVRAM_PARAMS_INDEX_CE_9_C1,
    NVRAM_PARAMS_INDEX_CE_10_C1,
    NVRAM_PARAMS_INDEX_CE_11_C1,
    NVRAM_PARAMS_INDEX_CE_12_C1,
    NVRAM_PARAMS_INDEX_CE_13_C1,
    NVRAM_PARAMS_INDEX_CE_14_C1,
    NVRAM_PARAMS_INDEX_CE_15_C1,
    NVRAM_PARAMS_INDEX_CE_16_C1,
    NVRAM_PARAMS_INDEX_CE_17_C1,
    NVRAM_PARAMS_INDEX_CE_18_C1,
    NVRAM_PARAMS_INDEX_CE_19_C1,
    NVRAM_PARAMS_CE_C1_END_INDEX_BUTT,
    /* SAR CONTROL */
    NVRAM_PARAMS_SAR_START_INDEX,
    NVRAM_PARAMS_INDEX_45 = NVRAM_PARAMS_SAR_START_INDEX,
    NVRAM_PARAMS_INDEX_46,
    NVRAM_PARAMS_INDEX_47,
    NVRAM_PARAMS_INDEX_48,
    NVRAM_PARAMS_INDEX_49,
    NVRAM_PARAMS_INDEX_50,
    NVRAM_PARAMS_INDEX_51,
    NVRAM_PARAMS_INDEX_52,
    NVRAM_PARAMS_INDEX_53,
    NVRAM_PARAMS_INDEX_54,
    NVRAM_PARAMS_INDEX_55,
    NVRAM_PARAMS_INDEX_56,
    NVRAM_PARAMS_INDEX_57,
    NVRAM_PARAMS_INDEX_58,
    NVRAM_PARAMS_INDEX_59,
    NVRAM_PARAMS_INDEX_60,
    NVRAM_PARAMS_INDEX_61,
    NVRAM_PARAMS_INDEX_62,
    NVRAM_PARAMS_INDEX_63,
    NVRAM_PARAMS_INDEX_64,
    NVRAM_PARAMS_INDEX_65,
    NVRAM_PARAMS_INDEX_66,
    NVRAM_PARAMS_INDEX_67,
    NVRAM_PARAMS_INDEX_68,
    NVRAM_PARAMS_INDEX_69,
    NVRAM_PARAMS_INDEX_70,
    NVRAM_PARAMS_INDEX_71,
    NVRAM_PARAMS_INDEX_72,
    NVRAM_PARAMS_INDEX_73,
    NVRAM_PARAMS_INDEX_74,
    NVRAM_PARAMS_INDEX_75,
    NVRAM_PARAMS_INDEX_76,
    NVRAM_PARAMS_INDEX_77,
    NVRAM_PARAMS_INDEX_78,
    NVRAM_PARAMS_INDEX_79,
    NVRAM_PARAMS_INDEX_80,
    NVRAM_PARAMS_INDEX_81,
    NVRAM_PARAMS_INDEX_82,
    NVRAM_PARAMS_INDEX_83,
    NVRAM_PARAMS_INDEX_84,
    NVRAM_PARAMS_SAR_END_INDEX_BUTT,
    /* SAR CONTROL C1 */
    NVRAM_PARAMS_SAR_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_45_C1 = NVRAM_PARAMS_SAR_C1_START_INDEX,
    NVRAM_PARAMS_INDEX_46_C1,
    NVRAM_PARAMS_INDEX_47_C1,
    NVRAM_PARAMS_INDEX_48_C1,
    NVRAM_PARAMS_INDEX_49_C1,
    NVRAM_PARAMS_INDEX_50_C1,
    NVRAM_PARAMS_INDEX_51_C1,
    NVRAM_PARAMS_INDEX_52_C1,
    NVRAM_PARAMS_INDEX_53_C1,
    NVRAM_PARAMS_INDEX_54_C1,
    NVRAM_PARAMS_INDEX_55_C1,
    NVRAM_PARAMS_INDEX_56_C1,
    NVRAM_PARAMS_INDEX_57_C1,
    NVRAM_PARAMS_INDEX_58_C1,
    NVRAM_PARAMS_INDEX_59_C1,
    NVRAM_PARAMS_INDEX_60_C1,
    NVRAM_PARAMS_INDEX_61_C1,
    NVRAM_PARAMS_INDEX_62_C1,
    NVRAM_PARAMS_INDEX_63_C1,
    NVRAM_PARAMS_INDEX_64_C1,
    NVRAM_PARAMS_INDEX_65_C1,
    NVRAM_PARAMS_INDEX_66_C1,
    NVRAM_PARAMS_INDEX_67_C1,
    NVRAM_PARAMS_INDEX_68_C1,
    NVRAM_PARAMS_INDEX_69_C1,
    NVRAM_PARAMS_INDEX_70_C1,
    NVRAM_PARAMS_INDEX_71_C1,
    NVRAM_PARAMS_INDEX_72_C1,
    NVRAM_PARAMS_INDEX_73_C1,
    NVRAM_PARAMS_INDEX_74_C1,
    NVRAM_PARAMS_INDEX_75_C1,
    NVRAM_PARAMS_INDEX_76_C1,
    NVRAM_PARAMS_INDEX_77_C1,
    NVRAM_PARAMS_INDEX_78_C1,
    NVRAM_PARAMS_INDEX_79_C1,
    NVRAM_PARAMS_INDEX_80_C1,
    NVRAM_PARAMS_INDEX_81_C1,
    NVRAM_PARAMS_INDEX_82_C1,
    NVRAM_PARAMS_INDEX_83_C1,
    NVRAM_PARAMS_INDEX_84_C1,
    NVRAM_PARAMS_SAR_C1_END_INDEX_BUTT,

#ifdef _PRE_WLAN_FEATURE_TAS_ANT_SWITCH
    NVRAM_PARAMS_TAS_ANT_SWITCH_EN,
    /* TAS PWR CONTROL */
    NVRAM_PARAMS_TAS_PWR_CTRL,
#endif
    NVRAM_PARAMS_5G_FCC_CE_HIGH_BAND_MAX_PWR,
    NVRAM_PARAMS_INDEX_IQ_LPF_LVL,

    NVRAM_CFG_TPC_RU_POWER_20M_5G,
    NVRAM_CFG_TPC_RU_POWER_40M_5G,
    NVRAM_CFG_TPC_RU_POWER_80M_L_5G,
    NVRAM_CFG_TPC_RU_POWER_80M_H_5G,
    NVRAM_CFG_TPC_RU_POWER_160M_L_5G,
    NVRAM_CFG_TPC_RU_POWER_160M_H_5G,
    NVRAM_CFG_TPC_RU_POWER_20M_2G,
    NVRAM_CFG_TPC_RU_POWER_40M_0_2G,
    NVRAM_CFG_TPC_RU_POWER_40M_1_2G,

    NVRAM_CFG_TPC_RU_MAX_POWER_0_2G_MIMO,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_2G_MIMO,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_2G_C0,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_2G_C0,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_2G_C1,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_2G_C1,

    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B1,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B2,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B3,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B4,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B5,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B6,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B7,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B1_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B2_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B3_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B4_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B5_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B6_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B7_CE,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B1_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B2_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B3_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B4_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B5_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B6_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_MIMO_B7_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_MIMO_B7_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C0_B7_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C0_B7_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_0_5G_C1_B7_FCC,
    NVRAM_CFG_TPC_RU_MAX_POWER_1_5G_C1_B7_FCC,

    NVRAM_CFG_TPC_RU_MAX_POWER_2G,
    NVRAM_CFG_TPC_RU_MAX_POWER_5G,

    NVRAM_PARAMS_PWR_INDEX_BUTT,
} NVRAM_PARAMS_INDEX;

/* 03产侧nvram参数 */
typedef enum {
    /* pa */
    WLAN_CFG_DTS_NVRAM_RATIO_PA2GCCKA0,
    WLAN_CFG_NVRAM_RATIO_PA2GA0,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2G40A0,
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA0,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2GCCKA1,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2GA1,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2G40A1,
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA1,
    /* add 5g low power part */
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA0_LOW,
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA1_LOW,

    /* DPN */
    WLAN_CFG_DTS_NVRAM_MUFREQ_2GCCK_C0,
    WLAN_CFG_DTS_NVRAM_MUFREQ_2G20_C0,
    WLAN_CFG_DTS_NVRAM_MUFREQ_2G40_C0,
    WLAN_CFG_DTS_NVRAM_MUFREQ_2GCCK_C1,
    WLAN_CFG_DTS_NVRAM_MUFREQ_2G20_C1,
    WLAN_CFG_DTS_NVRAM_MUFREQ_2G40_C1,
    WLAN_CFG_DTS_NVRAM_MUFREQ_5G160_C0,
    WLAN_CFG_DTS_NVRAM_MUFREQ_5G160_C1,
    WLAN_CFG_DTS_NVRAM_END,

    /* just for ini file */
    /* 5g Band1& 2g CW */
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA0_BAND1 = WLAN_CFG_DTS_NVRAM_END,
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA1_BAND1,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2GCWA0,
    WLAN_CFG_DTS_NVRAM_RATIO_PA2GCWA1,
    /* add 5g low power part */
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA0_BAND1_LOW,
    WLAN_CFG_DTS_NVRAM_RATIO_PA5GA1_BAND1_LOW,

    WLAN_CFG_DTS_NVRAM_RATIO_PPA2GCWA0,
    WLAN_CFG_DTS_NVRAM_RATIO_PPA2GCWA1,

    WLAN_CFG_DTS_NVRAM_PARAMS_BUTT,
    /* 新增系数依次往后添加 */
} PRO_LINE_NVRAM_PARAMS_INDEX;
typedef enum {
    CUS_POW_TX_CHAIN_MIMO = 0,
    CUS_POW_TX_CHAIN_SISO_0,
    CUS_POW_TX_CHAIN_SISO_1,

    CUS_POW_TX_CHAIN_BUTT
} cus_pow_chain_sel_no_enum;

/*
  7 STRUCT定义
 */
typedef unsigned char countrycode_t[COUNTRY_CODE_LEN];
typedef struct {
    regdomain_enum_uint8 en_regdomain;
    countrycode_t auc_country_code;
} countryinfo_stru;

/* regdomain <-> plat_tag map structure */
typedef struct regdomain_plat_tag_map {
    regdomain_enum_uint8 en_regdomain;
    int plat_tag;
} regdomain_plat_tag_map_stru;

typedef struct {
    char *name;
    int case_entry;
} wlan_cfg_cmd;

typedef struct {
    oal_int32 l_val;
    oal_bool_enum_uint8 en_value_state;
} wlan_customize_private_stru;

typedef struct wlan_cus_pwr_fit_para_stru {
    oal_int32 l_pow_par2; /* 二次项系数 */
    oal_int32 l_pow_par1; /* 一次 */
    oal_int32 l_pow_par0; /* 常数项 */
} wlan_customize_pwr_fit_para_stru;

typedef struct {
    oal_uint8 *puc_nv_name;
    oal_uint8 *puc_param_name;
    oal_uint32 ul_nv_map_idx;
    oal_uint8 uc_param_idx;
    oal_uint8 auc_rsv[3];
#ifdef _PRE_CONFIG_READ_DYNCALI_E2PROM
    oal_uint32   ul_eeprom_offset;
#endif
} wlan_cfg_nv_map_handler;

/*
 * 不接受cust下发的切换国家码的命令
 * 1、ini文件中国家码被配置成99
 * 2、维测需要:使用hipriv命令修改过国家码
 */
typedef struct {
    oal_bool_enum_uint8 en_country_code_ingore_ini_flag;
    oal_bool_enum_uint8 en_country_code_ingore_hipriv_flag;
#ifdef _PRE_WLAN_COUNTRYCODE_SELFSTUDY
    oal_bool_enum_uint8 en_country_code_study_ingore_hipriv_flag;
#endif
} wlan_cust_country_code_ingore_flag_stru;

typedef struct {
    oal_uint8 auc_sar_ctrl_params_c0;
    oal_uint8 auc_sar_ctrl_params_c1;
} wlan_cust_sar_ctrl_stru;

/* FCC/CE边带功率定制项:4字节对齐 */
typedef struct {
    oal_uint8 auc_5g_fcc_txpwr_limit_params_20M[CUS_NUM_5G_20M_SIDE_BAND];
    oal_uint8 auc_5g_fcc_txpwr_limit_params_40M[CUS_NUM_5G_40M_SIDE_BAND];
    oal_uint8 auc_5g_fcc_txpwr_limit_params_80M[CUS_NUM_5G_80M_SIDE_BAND];
    oal_uint8 auc_5g_fcc_txpwr_limit_params_160M[CUS_NUM_5G_160M_SIDE_BAND];
    oal_uint8 auc_2g_fcc_txpwr_limit_params[MAC_2G_CHANNEL_NUM][CUS_NUM_FCC_CE_2G_PRO];
    oal_uint8 rsv[2]; /* 保留字段:2字节 */
}wlan_cust_cfg_custom_fcc_ce_txpwr_limit_stru;

/* 1字节对齐 */
#pragma pack(push, 1)
typedef struct {
    oal_uint8 auc_tb_ru_5g_max_power[CUS_POW_TX_CHAIN_BUTT][WLAN_HE_RU_SIZE_BUTT];
} wlan_cust_5g_rupwr_limit_stru;

struct wlan_cust_nvram {
    oal_int8 ac_delt_txpwr_params[NUM_OF_NV_MAX_TXPOWER];
    oal_int8 ac_dpd_delt_txpwr_params[NUM_OF_NV_DPD_MAX_TXPOWER];
    oal_int8 ac_11b_delt_txpwr_params[NUM_OF_NV_11B_DELTA_TXPOWER];
    oal_uint8 auc_fem_off_iq_cal_pow_params[NUM_OF_IQ_CAL_POWER];
    oal_uint8 auc_5g_upper_upc_params[NUM_OF_NV_5G_UPPER_UPC];
    oal_int8 ac_2g_low_pow_amend_params[NUM_OF_NV_2G_LOW_POW_DELTA_VAL];
    oal_uint8 auc_2g_txpwr_base_params[WLAN_RF_CHANNEL_NUMS][CUS_BASE_PWR_NUM_2G];
    oal_uint8 auc_5g_txpwr_base_params[WLAN_RF_CHANNEL_NUMS][CUS_BASE_PWR_NUM_5G];
    /* MIMO下最大发射功率差 */
    oal_int8 ac_delt_txpwr_base_params[WLAN_RF_CHANNEL_NUMS][WLAN_BAND_BUTT];

    /* FCC/CE边带功率定制项 */
    wlan_cust_cfg_custom_fcc_ce_txpwr_limit_stru ast_fcc_ce_param[WLAN_RF_CHANNEL_NUMS];
#ifdef _PRE_WLAN_FEATURE_TAS_ANT_SWITCH
    /* TAS CTRL */
    oal_uint8 auc_tas_ctrl_params[WLAN_RF_CHANNEL_NUMS][WLAN_BAND_BUTT];
#endif
    /* 5g ce/fcc国家高band的最大发射功率 */
    oal_uint8 uc_5g_max_pwr_fcc_ce_for_high_band;
    oal_uint8 auc_5g_iq_cali_lpf_params[NUM_OF_NV_5G_LPF_LVL];
    oal_int8  ac_fullbandwidth_to_ru_power_5g[WLAN_BW_CAP_BUTT][WLAN_HE_RU_SIZE_BUTT];
    oal_int8  ac_fullbandwidth_to_ru_power_2g[WLAN_BW_CAP_80M][WLAN_HE_RU_SIZE_996];
#if defined(_PRE_WLAN_FEATURE_11AX)
    oal_uint8 auc_tpc_tb_ru_2g_max_power[CUS_POW_TX_CHAIN_BUTT][WLAN_HE_RU_SIZE_996];
    wlan_cust_5g_rupwr_limit_stru auc_tpc_tb_ru_5g_max_power[MAC_NUM_5G_BAND];
    oal_uint8 auc_tpc_tb_ru_max_power[WLAN_BAND_BUTT];
#endif
    oal_uint8 auc_rsv[1];
} __OAL_DECLARE_PACKED;
typedef struct wlan_cust_nvram wlan_cust_nvram_params;
#pragma pack(pop)

typedef struct {
    wlan_cust_nvram_params st_pow_ctrl_custom_param;
    /* SAR CTRL */
    wlan_cust_sar_ctrl_stru st_sar_ctrl_params[CUS_NUM_OF_SAR_LVL][CUS_NUM_OF_SAR_PARAMS];
} wlan_init_cust_nvram_params;


extern wlan_customize_pwr_fit_para_stru g_pro_line_params[WLAN_RF_CHANNEL_NUMS][DY_CALI_PARAMS_NUM];
extern wlan_cust_country_code_ingore_flag_stru g_cust_country_code_ignore_flag;
extern wlan_customize_stru g_wlan_customize;
extern oal_bool_enum_uint8 g_en_nv_dp_init_is_null; /* NVRAM中dp init置空标志 */
extern oal_int16 g_gs_extre_point_vals[WLAN_RF_CHANNEL_NUMS][DY_CALI_NUM_5G_BAND];
#ifdef _PRE_WLAN_FEATURE_TAS_ANT_SWITCH
extern oal_bool_enum_uint8 g_tas_switch_en[WLAN_RF_CHANNEL_MAX_NUMS];
#endif
extern wlan_customize_stru *g_wlan_cust;
extern int8 g_wifi_country_code[COUNTRY_CODE_LEN];
extern oal_bool_enum_uint8 g_en_fact_cali_completed;

extern int hwifi_config_init(int);
extern int hwifi_get_init_value(int, int);
extern char *hwifi_get_country_code(void);
extern void hwifi_set_country_code(const char *, const unsigned int);
extern int hwifi_get_mac_addr(unsigned char *);
extern void *hwifi_get_init_nvram_params(void);
extern void *hwifi_get_nvram_params(void);
extern int hwifi_is_regdomain_changed(const countrycode_t, const countrycode_t);
extern int hwifi_get_cfg_params(void);
extern int hwifi_hcc_customize_h2d_data_cfg(void);
extern int hwifi_custom_host_read_cfg_init(void);
extern int32 ini_file_check_conf_update(void);
extern int32 hwifi_get_init_priv_value(oal_int32 l_cfg_id, oal_int32 *pl_priv_value);
extern regdomain_enum_uint8 hwifi_get_regdomain_from_country_code(const countrycode_t country_code);
extern oal_uint8 *hwifi_get_nvram_param(oal_uint32 ul_nvram_param_idx);
extern oal_uint8 hwifi_custom_cali_ini_param(oal_uint8 uc_priv_cfg_value);
extern oal_int32 hwifi_read_conf_from(oal_uint8 *puc_buffer_cust_nvram, oal_uint8 uc_idx);
extern oal_netbuf_stru* hwifi_hcc_custom_netbuf_alloc(void);
#endif  // #if defined(_PRE_PRODUCT_ID_HI110X_HOST)

#endif  // hisi_customize_wifi.h
