obj-$(CONFIG_HISI_CLK_DEBUG)        += clk-unit-test.o
obj-$(CONFIG_HISI_CLK_DEBUG)        += hisi-clk-test.o
obj-$(CONFIG_HISI_CLK_DEBUG)        += hisi-clk-debug.o

subdir-ccflags-$(CONFIG_HISI_CLK_DEBUG)  += -I$(srctree)/drivers/clk/hisi/
subdir-ccflags-$(CONFIG_HISI_CLK_DEBUG)  += -I$(srctree)/drivers/clk/
