-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/balong_product_config.mk
ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif


obj-y	+= chr_om.o
obj-y	+= chr_cfg.o 