#
# Copyright (c) Huawei Technologies Co., Ltd. 2017-2018. All rights reserved.
# Description: Makefile for the Huawei kernel mdpp selfverify.
# Author: wangtienan <wangtienan@huawei.com>
# Create: 2017-09-23
#

obj-$(CONFIG_HUAWEI_CRYPTO_TEST_MDPP) += tcrypt_mdpp_selfverify.o
ccflags-$(CONFIG_HUAWEI_CRYPTO_TEST_MDPP) += -Ivendor/hisi/bsp/libc_sec/include
